### ISSUE TITLE
Bruma - Convenient Horses - The Reach - Patch not recognized (SSE)

### ISSUE THREAD

**Issue by sdpragequit** [loot/loot#1069]
The Combination Patch for Bruma, Beyond Reach and Convenient Horses is not recognized as such 
![loot_2019-01-16_10-52-02](https://user-images.githubusercontent.com/24487483/51240929-0eb72200-197d-11e9-9572-2cf1745cad3b.png)
I used the installer found at https://www.nexusmods.com/skyrimspecialedition/mods/13812 to install patches for Convenient Horses. I selected the options for Beyond Reach and Bruma and got this combined esp:
![modorganizer_2019-01-16_10-53-33](https://user-images.githubusercontent.com/24487483/51241456-2511ad80-197e-11e9-929e-48e5d996d574.png)
This esp does not stop the above warning from appearing.

(Beyond Reach also never gave a warning like Bruma does)

**Comment by CptMcSplody** [comment]
Hi @sdpragequit,

That message was added in april 2018 before the other patches were added, so it's a bit out of date. I'll be updating it, but since it has quite a few patches now it will take some time to test it.

Keep in mind these are hardcoded checks added by hand. If there are any changes to the patch names it will break the condition used to check.

Thanks for letting me know it was updated.
I'll post a reference when the change is commited to the masterlist.
