### ISSUE TITLE
Handle references to invalid group

### ISSUE THREAD

**Issue by CptMcSplody** [loot/loot#1082]
Brought up in #1075 

Current general message for invalid group.
![image](https://user-images.githubusercontent.com/1944639/51806038-cd701d80-226c-11e9-8f08-69356685f3d6.png)

So a few thoughts on ways to handle it:
- Add error message to each plugin referencing an invalid group.
- Add clear invalid user metadata to general message, without affecting other userdata.
- Automatically clear invalid groups from userlist.

**Comment by CptMcSplody** [comment]
Metadata editor display for plugin with invalid group.
![image](https://user-images.githubusercontent.com/1944639/51806167-72d7c100-226e-11e9-9ad5-02125f67bd33.png)

**Comment by Ortham** [comment]
I like the idea of an error message on each plugin that references a group that doesn't exist. I imagine that the user would want to choose the next closest group for each plugin, and they might not all map to the same group, so "clear invalid user metadata" probably isn't so useful. I don't like the idea of clearing invalid groups automatically, because that's messing with data the user's created themselves.

Thinking about the cases where this can occur, they are:

1. User assigned a masterlist group, which was then removed from the masterlist
2. User assigned a user group, which they then deleted using the groups editor
3. User assigned a group, which was removed from masterlist.yaml or userlist.yaml

There's no way to guard against the first or third within LOOT, but the second could be prevented by preventing deletion of a group that has plugins in it. There would have to be some UI for indicating which plugins are in a given group - opening the metadata editor displays them in the sidebar, but something within the groups editor would be much better.

**Comment by CptMcSplody** [comment]
>Thinking about the cases where this can occur, they are:
> 1. User assigned a masterlist group, which was then removed from the masterlist
> 2. User assigned a user group, which they then deleted using the groups editor
> 3. User assigned a group, which was removed from masterlist.yaml or userlist.yaml

Could one be mitigated by copying referenced groups to the `userlist.yaml`?

> There would have to be some UI for indicating which plugins are in a given group - opening the metadata editor displays them in the sidebar, but something within the groups editor would be much better.

Maybe having a context menu for right clicks on groups?
So instead of just deleting a group with a right click, it gives a list of options.
Such as:
`Delete Group`
`View Group Plugins`
And grey out invalid selections, might be a bit much for only two options though.
Could maybe have an edit group, to modify a group name/description.

How would the plugins be displayed within the group editor?
Similar to groups in a separate section like, only fewer lines and maybe a different shape for plugins:
![image](https://user-images.githubusercontent.com/1944639/51862980-c5c97b00-2337-11e9-9419-ac62ca6e3fb8.png)

Or by having the sidebar display with the group editor?

![image](https://user-images.githubusercontent.com/1944639/51863614-69675b00-2339-11e9-8c98-63b2c9cb4f06.png)

**Comment by Ortham** [comment]
> Could one be mitigated by copying referenced groups to the `userlist.yaml`?

Yes, but then you run the risk of changing the meaning of a group: if a user adds a plugin to a group because it loads after another group in the masterlist, but that other group is removed, the behaviour has changed but it wouldn't be clear to the user.

> How would the plugins be displayed within the group editor?

I was thinking of having a listbox to the side of the groups editor that lists the plugins that you have installed which are in the currently-selected group, so just clicking on a group populates the list. So similar to your mockup with the sidebar, but integrated into the same dialog.

**Comment by Ortham** [comment]
@CptMcSplody In [this build](https://bintray.com/loot/snapshots/download_file?file_path=loot_0.14.3-20-g2aada92_morrowind-support.7z) I've added error messages for plugins that belong to nonexistent groups, prevented deleting a group in the groups editor if it still has plugins, and added a list of plugins belonging to the selected group in the editor. Can you give it a spin and see what you think?

**Comment by CptMcSplody** [comment]
@Ortham Looks good to me, everything worked as expected from your description.
- Couldn't delete a group with plugins.
- Got an error if an assigned group was missing.
- List was displaying correctly.

**Comment by Ortham** [comment]
OK, closing this as the changes are merged as of 1ca6dc300e5957dd7d69f76ccf866f63f36bbede.

**Comment by CptMcSplody** [comment]
@Ortham Thanks.
