### ISSUE TITLE
Add MS-Corefonts to requirements for Wine users

### ISSUE THREAD

**Issue by t14462** [loot/loot#1097]
Now linux running games good.
FPS in NV/FO3/Oblivion same as native.

DXVK running DX11 games good to, so add note for wine users: "MS-Corefonts required, you can install it trough winetricks"

**Comment by Ortham** [comment]
Where would you want this to be noted?

**Comment by t14462** [comment]
At readme page? Linux people are advanced, so they find this information.

Also, LOOT working good on linux, thanks.

**Comment by pStyl3** [comment]
[DXVK](https://github.com/doitsujin/dxvk)
```
A Vulkan-based translation layer for Direct3D 9/10/11 which allows running 3D applications on Linux using Wine.
```
Am I correct with my assumption, that DXVK is only mentioned here in order to convey the notion, that Linux based systems are now performing quite well in running games? And as such, that it would be beneficial for LOOT to further extend it's documentation towards Linux users?

In any case, am I also correct on the assumption that @t14462 is of the opinion that `MS-Corefonts` are *required* for Linux users, so that LOOT is displayed correctly / adequately? If so and we would want to mention those `MS-Corefonts` within the documentation, where would I need to download them?

I also think that `winetricks` should be further explained, either directly or by linking to some other site. What about [this one](https://wiki.winehq.org/Winetricks)?

**Comment by Ortham** [comment]
Personally, I can't get LOOT to run under Wine at all (even after installing corefonts), and I'm not really interested in spending any more time poking around to try to get it working. If anyone running LOOT under Wine wants to provide the documentation, I'd be happy to incorporate it though.

**Comment by Ruedii** [comment]
Corefonts should not be required for Wine use now.  Wine has an extensive substitute font list and most Linux distros ship at least one.

I am currently running into a lot of issues with Direct X errors in Proton Wine, but I need to retry on the newer version of LOOT (new one just came out a few hours ago) and a newer version Proton Wine.

**Comment by Ortham** [comment]
I'm able to install and run LOOT v0.18.0 under Wine with just wine installed (no winetricks or MS-Corefonts), so I'm closing this.
