### ISSUE TITLE
Failed To Sort Plugins - Cyclic Interaction Detected

### ISSUE THREAD

**Issue by 0pLuS0** [loot/loot#1174]
Hello,

Starting at version 15.0, also 15.1 has this issue, when I install plugins and then try to sort them, sometimes I get this type of message.

The last time this happened, I was testing various mods, then reinstalled ELFX Enhancer and then I needed to sort the load order manually and have nwsFollowerFramework loaded last after RealisticWaterTwo, but then when I tried, I kept getting this popup message.

14.6 is not having this issue.

![LOOT](https://user-images.githubusercontent.com/36190223/71573655-f59b7880-2adc-11ea-8fa1-281169ed8e3d.jpg)

**Comment by CptMcSplody** [comment]
> The last time this happened, I was testing various mods, then reinstalled ELFX Enhancer 

###### Group order
_Default_ -> _Low Priority Overrides_ -> _High Priority Overrides_ -> _Late Loaders_

`nwsFollowerFramework.esp` (Low Priority Overrides)
`ELFXEnhancer.esp` (High Priority Overrides)
`Immersive Citizens - ELFXEnhancer patch.esp` (Default)
`RealisticWaterTwo.esp` (Late Loaders)

@0pLuS0 You're trying to sort through a group with an after, and that's causing a sorting error because LOOT can't decide which plugins should sort later.

`ELFXEnhancer.esp` and `Immersive Citizens - ELFXEnhancer patch.esp`
or `RealisticWaterTwo.esp` and `nwsFollowerFramework.esp`

You could solve this a few ways.

Add an after to `RealisticWaterTwo.esp` to sort it after `ELFXEnhancer.esp`.
or
Add an after to `nwsFollowerFramework.esp` to sort it after `ELFXEnhancer.esp`.

Move `nwsFollowerFramework.esp` to the _Late Loaders_ or _default_ group.

![image](https://user-images.githubusercontent.com/1944639/71574037-c128bc00-2ade-11ea-901d-9bd43309de5e.png)

![image](https://user-images.githubusercontent.com/1944639/71574177-883d1700-2adf-11ea-8a23-5502bbf035ed.png)

> 14.6 is not having this issue.

nwsFollowerFramework was added to the _Low Priority Overrides_ group to place it after any mods it conflicts with, most mods are in the _default_ group.

![image](https://user-images.githubusercontent.com/1944639/71574123-44e2a880-2adf-11ea-9000-9cb9ab8d5ea4.png)

Not sure why you'd need to place `nwsFollowerFramework.esp` after `RealisticWaterTwo.esp`, the only only overwrite showing is WRLD maxheight data, which you can safely ignore.

![image](https://user-images.githubusercontent.com/1944639/71574263-e8cc5400-2adf-11ea-982b-8e5c87275b26.png)

**Comment by 0pLuS0** [comment]
I'm no pro when it comes to using LOOT, and with 14.6, I was placing Nether's Follower Framework as last in the load order, which was always after RealisticWaterTwo, which has always been last.

https://www.nexusmods.com/skyrimspecialedition/mods/18076

I wasn't paying attention that Nether's says to actually place it near the end,  not actually at the very end like I was doing.

I edited the Metadata, added a row and placed ReaslisticWaterTwo in it, to have Nether's load after it.

So I'm assuming something has changed in 15.x that this can no longer happen, since I was able to in 14.6?

I thought when it came to using LOOT, if someone wanted to take any mod they could load it anywhere they wanted.

Here's another screen shot showing RealistcWaterTwo as number 24 in the order, as last.

![LOOT_Order](https://user-images.githubusercontent.com/36190223/71605307-be21e000-2b5f-11ea-8f90-cb3f1551e6f9.jpg)

**Comment by CptMcSplody** [comment]
> Keep up the great work LOOT is really awesome and appreciated!

You're welcome.

> THANKS, hope you had a nice Holiday, and Happy New Year!

Happy new year.


> So I'm assuming these Priorities and Load orders have changed in 15.x that this can no longer happen?

Priorities no longer exist those were removed in v0.13, they've been superseded by Groups.

[Editing Plugin Groups](https://loot.readthedocs.io/en/latest/app/usage/groups_editor.html)

> I thought when it came to using LOOT, if someone wanted to take any mod they could load it anywhere they wanted.

You can but within reason, in some cases there are hard load afters that will prevent this.
Less afters increase the chances of a sorting error due to user rules, but it does give you options.
It's possible to sort `nwsFollowerFramework.esp` after `RealisticWaterTwo.esp`.

You could create a new group for `nwsFollowerFramework.esp` and then place that group after `RealisticWaterTwo.esp` group "Late Loaders" in the group editor.

![image](https://user-images.githubusercontent.com/1944639/71605657-92ecc000-2b62-11ea-8f33-2ca14fdc10b8.png)

![image](https://user-images.githubusercontent.com/1944639/71605669-a9931700-2b62-11ea-9647-374a7913b30d.png)

![image](https://user-images.githubusercontent.com/1944639/71605681-b6b00600-2b62-11ea-8667-6c5d1692594c.png)

![image](https://user-images.githubusercontent.com/1944639/71605691-d47d6b00-2b62-11ea-9300-e1eb3b9ecf29.png)

![image](https://user-images.githubusercontent.com/1944639/71605714-0f7f9e80-2b63-11ea-96c0-e0fd5f1e9dfa.png)

> But I guess the name of the game here is 'Conflicts', so as long as it's not doing that, then I'm assuming where LOOT is placing it, it's doing fine.

I'd recommend using [SSEEdit](https://www.nexusmods.com/skyrimspecialedition/mods/164) as well to check for any issues, LOOT is just a utility and requires some help from the user.

**Comment by 0pLuS0** [comment]
Ok, on sorting, for now I'll just leave it, since Nether's says ```Near the end```, this looks pretty near the end in the load order... LOL

I do use SSEEdit as Quick Clean and clean anything LOOT flags, besides Skyrim, YEP I have it all clean...

THANKS

**Comment by CptMcSplody** [comment]
Okay I'll close this since it's resolved.
