### ISSUE TITLE
"Failed to check for LOOT updates" and more.

### ISSUE THREAD

**Issue by BrodyHands** [loot/loot#1176]
So, I recently finished my list of F4 mods, then I install LOOT to finish it up, but when I open it, it says it failed to check for updates, along with only the main game and DLC ESMs appearing in the application, along with FO4Edit notifications for each ESM except the main game. Log is attached. https://drive.google.com/file/d/1fpGDz74YTwFCis4ALvvDOUS6Bmm3_r6I/view?usp=sharing

**Comment by Ortham** [comment]
As discussed on Discord, the error is due to GitHub rate-limiting the requests LOOT makes to check for updates. Unauthenticated requests (like those LOOT makes) are limited to 60/hour, and each check takes at least 4 requests, so launching LOOT somewhere under 15 times per hour would cause you to get that error. The LOOT update check can be disabled in LOOT's settings if you want to silence the error.

Only seeing the main game and DLC ESMs suggests that LOOT is working fine but you're using a mod manager like MO2 that "installs" plugins without actually putting them in the game's Data folder. In that case, you need to launch LOOT through the mod manager like you would launch the game through it, or LOOT won't be able to see the mods you've "installed".

Note though that I can't provide support for issues that only occur when using LOOT in conjunction with MO2, because the filesystem tricks MO2 employs can cause issues that I can't do anything about.
