### ISSUE TITLE
Cyclic interaction b/t Ordinator & Apocalypse

### ISSUE THREAD

**Issue by Mirrorman95** [loot/loot#1182]
I'm getting this error:

Failed to sort plugins. Details:
Cyclic interaction detected between "ordinator - perks of skyrim.esp" and "apocalypse - vokrii compatibility patch.esp":

ordinator - perks of skyrim.esp
 [Master]
apocalypse - ordinator compatibility patch.esp
 [Master]
YOT - Apocalypse.esp
 [Group]
vokrii - minimalistic perks of skyrim.esp
 [Master]
apocalypse - vokrii compatibility patch.esp
 [Group]
ordinator - perks of skyrim.esp

**Comment by CptMcSplody** [comment]
You'll receive those if LOOT can't decide which plugin should win a tie break.
Since `ordinator - perks of skyrim.esp` and `vokrii - minimalistic perks of skyrim.esp` are normally incompatible, unless you are using [Vokriinator](https://www.nexusmods.com/skyrimspecialedition/mods/26702), there's no set order between those two mods.
You'll need to set an after to decide whether Ordinator or Vokrii is sorted later.

**Comment by CptMcSplody** [comment]
That just a best guess since I can't see your user rules. 
You'd need to provide a full debug log so that I can be sure.

**Enabled** debug logging in LOOT settings and upload a full _LOOTDebugLog.txt_.

![image](https://user-images.githubusercontent.com/1944639/67115390-ff982580-f1d5-11e9-82f1-9202da269976.png)

You can navigate to the from _LOOTDebugLog.txt_ the hamburger menu.

![image](https://user-images.githubusercontent.com/1944639/74393903-40f6b580-4e03-11ea-98cf-b0ed0eb0e759.png)

**Comment by Mirrorman95** [comment]
[LOOTDebugLog.txt](https://github.com/loot/loot/files/4196164/LOOTDebugLog.txt)

**Comment by CptMcSplody** [comment]
> 
> 
> [LOOTDebugLog.txt](https://github.com/loot/loot/files/4196164/LOOTDebugLog.txt)

That's not a full debug log.

**Comment by Mirrorman95** [comment]
I'm sorry. Which file is the full debug log located in?

**Comment by CptMcSplody** [comment]
The same place, you must **Enable** debug logging in LOOT settings first.

![image](https://user-images.githubusercontent.com/1944639/67115390-ff982580-f1d5-11e9-82f1-9202da269976.png)

**Comment by Mirrorman95** [comment]
I'm really sorry, I should've read your instructions in full the first time. But I believe the debug log is no longer necessary, because I installed Vokriinator and activated it and Vokrii and that fixed the problem. Thank you so much.
