### ISSUE TITLE
Display decimal load order indices in sidebar

### ISSUE THREAD

**Issue by RealAntithesis** [loot/loot#1189]
1. It would be useful if the load order number (in decimal format) was included in the right-hand side plugin list. This would assist with long load orders when navigating through the list and trying to figure out the relative positions of various plugins. Also include a decimal load order number for the list on the left.

2. It would also be useful if the plugin name filter could have multiple names that could be used (delimited by commas) to filter the list for multiple plugins (similar to MO2's name filtering). This can help with visualising and understanding where certain plugins are relative to each other (because normally they could scattered all over the load order) to simplify the process of setting 'load after' rules (e.g. if the plugins are in the undesired order).

3. (While I'm at it) Adding the Group name to each plugin in the list would also be useful information.

**Comment by Ortham** [comment]
1. What's wrong with the hex load order numbers in the sidebar plugin list?
2. Are you referring to the conflicting plugins filter or the card text filter? How would you handle plugins which have a comma in their filename?
3. The group names are already listed if you go into edit mode.

**Comment by RealAntithesis** [comment]
1. Some people can't read hexadecimal to figure out whether a plugin is lower or higher in the load order than another plugin they were looking at, especially if that other plugin is not visible in the list (because it's a long list of plugins). Hex is fine to distinguish ESPs from ESLs or ESPFEs and provide the starting digits for form ids from those plugins, but I would think decimals are more relevant for the order in which plugins load compared to each other.
- Also, the list on the right doesn't have numbers at all, and it scrolls independently of the list on the left. So you may be navigating the list on the right and changing metadata etc, but this isn't very useful to determine the load order of these plugins unless they happen to be up on screen.
2. I'm referring to the card text filter. Instead of commas, perhaps can use semi-colons? Regardless, there have been cases where I've been wanting to view certain plugins with different names but they are scattered all over the load order, and I couldn't otherwise get them on the same screen to easily see where they were in relation to each other.
3. There is a groups editor yes (is there another 'edit mode'?), but that doesn't say which plugins are included in those groups. I'm referring to the list of plugins themselves indicating which group they belong to (otherwise you need to open up the metadata tab to check).

**Comment by Ortham** [comment]
Sorry for the delayed reply, but:

- If you want to check if a plugin is higher or lower than another in the load order, you just need to check if it's higher or lower than the other plugin in the UI, the main panel and the sidebar both list plugins in load order (with the exception of ESLs, but they're clearly distinguished in the sidebar and amongst themselves also load in the order they're listed). 

  You don't need to do any arithmetic (hexadecimal or otherwise) to figure it out: even if you ignored the ordering and just used the hex load order indices, you just need to know that hex numbers go 1-9 then A-F, then you can tell that (for example) FE comes after 6C. 

  If you were talking about figuring out how far apart they were, then I could understand wanting decimals, because I don't think in base 16. For example, 0xFE - 0x6C is trivially 0x92, but that doesn't really mean anything to me until I do 9 * 16 + 2 = 146.
- Semicolons wouldn't work because they're also allowed in Windows filenames, but the issue is more general: the card text filter searches for arbitrary text literals, but you're asking for search query support with some kind of boolean OR operator. That's significantly more complex, and I haven't decided yet if I want to implement that or not.
- By edit mode I mean the UI mode LOOT goes into when you have the plugin metadata editor open. When you do, the sidebar lists the plugin's group under each plugin name, unless the group is `default`. Also, whether or not you're in edit mode, if you select a group in the groups editor, it does list what plugins are in that group, if any.

**Comment by sibir-ine** [comment]
I think it'd be beneficial to have a second column in the _Plugins_ sidebar next to the load order index that lists the position of each plugin in the list as a decimal number. With the Qt GUI, light plugins currently only display their light plugin index (e.g., FE 000), which isn't useful when trying to gauge its distance to non-light plugins. It's also a bit inconvenient to gauge the distance between plugins in hexadecimal as most people (me included) will need to convert to decimal first to calculate it.

For the more advanced filtering, I think this would be useful too. Maybe something like a toggle for a regex mode? However, I have no idea how complex that would be to implement or whether it would be used enough to warrant the effort.

For making group names more visible, that has since been addressed & rejected in https://github.com/loot/loot/issues/1476. I agree that the current layout is sufficient.

**Comment by Ortham** [comment]
> With the Qt GUI, light plugins currently only display their light plugin index (e.g., FE 000), which isn't useful when trying to gauge its distance to non-light plugins.

Why isn't that useful? The `FE` part is the normal load order index of the plugin, and the `000` part is the index of the light plugin within the `FE` load order index.

**Comment by sibir-ine** [comment]
> Why isn't that useful? The `FE` part is the normal load order index of the plugin, and the `000` part is the index of the light plugin within the `FE` load order index.

It doesn't communicate how far apart a light plugin & a non-light plugin are in your load order. For instance, you aren't able to tell how far apart `FE 031` & `1F` are without counting how many plugins are in between them in your load order.

**Comment by Ortham** [comment]
Right, but that's not anything specific to light plugins: it's just that as well as calculating `FE - 1F` you also need to calculate `31 - 0` (which are also hex digits), right?

When displaying the load order index as a decimal number, would that example light plugin's decimal index be `dec(FE - 1F + 31 - 0)`, i.e. `272`, or would the two levels of index be kept separate, i.e. `223 49`?

> For the more advanced filtering, I think this would be useful too. Maybe something like a toggle for a regex mode? However, I have no idea how complex that would be to implement or whether it would be used enough to warrant the effort.

I think allowing regex would be doable - there would need to be a checkbox to toggle how the text input is interpreted, so that e.g. entering `.esp` doesn't end up matching `desperate` if you're not intending to use regex.

**Comment by sibir-ine** [comment]
> Right, but that's not anything specific to light plugins: it's just that as well as calculating `FE - 1F` you also need to calculate `31 - 0` (which are also hex digits), right?
> 
> When displaying the load order index as a decimal number, would that example light plugin's decimal index be `dec(FE - 1F + 31 - 0)`, i.e. `272`, or would the two levels of index be kept separate, i.e. `223 49`?

Sorry, I'm referring to the actual order in which the plugins are loaded as defined in `plugins.txt`. For instance, `FE 031` could load any number of plugins before or after `1F` depending on where they're listed in `plugins.txt`.

> I think allowing regex would be doable - there would need to be a checkbox to toggle how the text input is interpreted, so that e.g. entering `.esp` doesn't end up matching `desperate` if you're not intending to use regex.

Yeah, that's what I was thinking.

**Comment by Ortham** [comment]
> Sorry, I'm referring to the actual order in which the plugins are loaded as defined in `plugins.txt`. For instance, `FE 031` could load any number of plugins before or after `1F` depending on where they're listed in `plugins.txt`.

That's not my understanding - AFAIK according to the in-game object IDs of records they add, all light plugins are hoisted up to the `FE` slot regardless of where they are put in `plugins.txt`.

**Comment by sibir-ine** [comment]
> That's not my understanding - AFAIK according to the in-game object IDs of records they add, all light plugins are hoisted up to the `FE` slot regardless of where they are put in `plugins.txt`.

Really? I thought they respected the order in `plugins.txt`, & that's what's stated in [Introduction To Load Orders](https://loot.github.io/docs/help/Introduction-To-Load-Orders.html). I know a new object would have a formID like `FE031xxx` as you say, but I'm pretty sure overrides would respect the order in `plugins.txt`. I'll have to test to double-check.

**Comment by sibir-ine** [comment]
Overrides in light plugins do appear to respect the load order as defined in `plugins.txt`, & new objects are also hoisted up to `FE`. However, the load order number I'm referring to being displayed in decimal would be the one that represents what overrides would win, i.e., the same order represented by the order the plugins & cards are displayed in the _Plugins_ sidebar & card list, respectively.

**Comment by Ortham** [comment]
> Really? I thought they respected the order in `plugins.txt`, & that's what's stated in [Introduction To Load Orders](https://loot.github.io/docs/help/Introduction-To-Load-Orders.html).

I've forgotten my own research, that matches what I wrote in libloadorder's docs...

**Comment by Ortham** [comment]
@sibir-ine Is the implementation in the `plugin-sidebar-indexes` branch as you expect?

**Comment by sibir-ine** [comment]
Yup, it looks great, thanks 👍

**Comment by Ortham** [comment]
Done in c57a62a06d99aaafb74ca9bb9594dc38722c336c.
