### ISSUE TITLE
Loot does not create groups

### ISSUE THREAD

**Issue by loverxxx5** [loot/loot#1327]
Hi,

I've updated loot from an old play and now I constantly receive the error "Mod Group Add-Ons & Expansions" does not exist.  When I go try to edit groups, none are present and I can't add any new ones.  I've deleted and reinstalled several times, run as administrator, rebooted my PC and I'm just out of ideas.  It seems like Loot doesn't load any groups.
![1](https://user-images.githubusercontent.com/38872455/91108395-9971ff80-e63d-11ea-99e7-1d7414a0e1aa.PNG)
![2](https://user-images.githubusercontent.com/38872455/91108401-9c6cf000-e63d-11ea-80f4-2e4d9988dc02.PNG)

**Comment by CptMcSplody** [comment]
@loverxxx5 You have a user rule that's using a group that doesn't exist.
You can remove the rule by editing or deleting `AppData\Local\LOOT\Skyrim Special Edition\userlist.yaml`.

**Comment by loverxxx5** [comment]
Thank you so much!  I kept looking for the file that contained it.  Weirdly, I tried to clear my user metadata and it didn't do anything.  Thanks again.

**Comment by CptMcSplody** [comment]
>  Weirdly, I tried to clear my user metadata and it didn't do anything.

![image](https://user-images.githubusercontent.com/1944639/91189924-ebbd2a00-e6ea-11ea-80c4-77934614a489.png)

Yeah, I don't think that button will clear group metadata from the `userlist.yaml`.
I'm not sure if it's intentional behaviour tbh.

@Ortham Is clear user metadata supposed to ignore group metadata?

**Comment by Ortham** [comment]
It's supposed to clear user-defined group metadata too, sounds like a bug.

**Comment by Ortham** [comment]
I think I've spotted the issue: the groups cached in the UI aren't updated when the metadata is cleared, so they should be gone if you close and re-open LOOT or if you change game in the UI, but without clearing that cache the groups won't be removed otherwise.

**Comment by Ortham** [comment]
This should now be fixed in 34065c5d40f5140803b7ca608241964dda7d158e. 

@loverxxx5 Could you test [this snapshot build](https://bintray.com/loot/snapshots/loot/0.15.1-219-ge3556e1_master#files) to verify that clearing all user metadata removes groups as you'd expect (you might want to create a copy of your userlist.yaml first).

**Comment by Ortham** [comment]
Closing this as the fix has been released.
