### ISSUE TITLE
Support for Windows Store versions

### ISSUE THREAD

**Issue by pStyl3** [loot/loot#1436]
After Microsoft bought Zenimax and as such Bethesda, some of Bethesda's games have been rereleased within the Windows Store.

[The Elder Scrolls III: Morrowind Game of the Year Edition (PC)](https://www.microsoft.com/en-us/p/the-elder-scrolls-iii-morrowind-game-of-the-year-edition-pc/9pp7xsg5ldh1?activetab=pivot:overviewtab)
[The Elder Scrolls IV: Oblivion Game of the Year Edition (PC)](https://www.microsoft.com/en-us/p/the-elder-scrolls-iv-oblivion-game-of-the-year-edition-pc/9p2j5d12gjl5?activetab=pivot:overviewtab)
[Skyrim Special Edition + Fallout 4 G.O.T.Y Bundle (PC)](https://www.microsoft.com/en-us/p/skyrim-special-edition-fallout-4-goty-bundle-pc/9nhn17g0zld1)
[The Elder Scrolls V: Skyrim Special Edition (PC)](https://www.microsoft.com/en-us/p/the-elder-scrolls-v-skyrim-special-edition-pc/9p03jgq4s1gc?activetab=pivot:overviewtab)
[Fallout 4 (PC)](https://www.microsoft.com/en-us/p/fallout-4-pc/9p71mb9qcf77?activetab=pivot:overviewtab)

The question is, how do the Windows Store versions work and what would we need to do so that LOOT can be used to sort load orders for these versions, in case that we want to add support?

If we would add support, it would certainly mean that our settings menu would get potentially even more cluttered, so maybe we can use this opportunity and think about [issue 581](https://github.com/loot/loot/issues/581) once more.

Also, here's Wrye Bash's issue in which support is discussed: [Link](https://github.com/wrye-bash/wrye-bash/issues/585)

**Comment by Ortham** [comment]
> The question is, how do the Windows Store versions work and what would we need to do so that LOOT can be used to sort load orders for these versions, in case that we want to add support?

No idea, and I'm not buying Oblivion *again* to find out - I've already bought it three times (disk, Steam and GOG).

> If we would add support, it would certainly mean that our settings menu would get potentially even more cluttered, so maybe we can use this opportunity and think about [issue 581](https://github.com/loot/loot/issues/581) once more.

Yes, I think I'll pick that improvement up.

**Comment by sibir-ine** [comment]
@FelesNoctis linked an [article](https://github.com/wrye-bash/wrye-bash/wiki/%5Bdev%5D-Microsoft-Store-Games) @lojack5 wrote that will probably be of some use.

**Comment by Infernio** [comment]
We've [merged support for them now](https://github.com/wrye-bash/wrye-bash/commit/0ad88821b19db99eefc7512ded56fe3f70d2b4fd). If you guys want to tackle it, here's a quick summary, based on [Lojack's article](https://github.com/wrye-bash/wrye-bash/wiki/%5Bdev%5D-Microsoft-Store-Games) mentioned above:
 - Finding the game locations is pretty involved, simple registry keys don't exist. [This section](https://github.com/wrye-bash/wrye-bash/wiki/%5Bdev%5D-Microsoft-Store-Games#finding-a-Game) of the article details how to do it.
 - There are two locations for plugins.txt: `%LOCALAPPDATA\{progam_folder}` and `%LOCALAPPDATA\Local\Packages\{full_name}\LocalCache\Local\{program_folder}`. See [the Background section](https://github.com/wrye-bash/wrye-bash/wiki/%5Bdev%5D-Microsoft-Store-Games#background) of the article for more details. WB currently writes to both, preferring the latter (on my system, the former doesn't even exist, but other people have reported that it does exist on theirs).
 - The EXEs are locked down hard, meaning that accessing information from it (including e.g. the version) doesn't really work. Running `os.stat` on it works fine sometimes, but when I restart my PC it will usually go back to not working again.
 - Creating and modifying files in the Data folder works fine, subject to UAC (not really relevant for LOOT).

...but I don't blame you if you just want to reject supporting them, it was a real hassle to get it working.

**Comment by pStyl3** [comment]
I think that whatever decision we agree upon regarding these Windows Store versions, that the potential support for them should not be a milestone for the next official LOOT version. Rather I would argue, that we push out a new version with the changes, fixes and additions that we already got (the last official release was already half a year ago) and then we can take a look at this.

That being said, most of the games are _currently_ on sale and I bought SSE for 15.99 Euro, with money that comes from the Donation Point system on Nexus, which I saved for purposes like this one. I could potentially try to gift one game to other LOOT team members as well (with money that also comes from the DP system), though I think I need to buy the game while the Windows Store is displayed in german (the url includes `de-de` instead of `en-us`). Otherwise the Windows Store doesn't seem to allow me to
go through with the transaction, and I'm not sure if I then will be able to gift the game to someone outside of Germany.

Besides that, I think that it wouldn't be the best idea to try to install the Windows Store version while the game is already installed via Steam, right?

**Comment by Infernio** [comment]
You can install all but Oblivion while having the Steam version installed without problems, that's how I did my testing. Oblivion shares the same My Games subfolder between the Steam and WS versions, whereas the others either have their own folders (SSE and FO4, they both have an ` MS`-suffix on their My Games subfolder) or don't use My Games at all (Morrowind). The load order files are in other places as well, as explained above (and in the article).

**Comment by Ortham** [comment]
Despite what I said above, I've just bought Oblivion from the Windows Store, so between pStyle and me we have most load order mechanisms covered.

**Comment by sibir-ine** [comment]
pStyl3 also gave me Morrowind.

**Comment by Ortham** [comment]
I installed the MS Store Oblivion on my D drive (which is where I put all my games) and was able to run the launcher (I didn't try past that), but then I found that after shutting down my PC and turning it on again, trying to run the launcher would either do nothing or show one of two dialog boxes complaining that it couldn't find my game, quoting a C drive path...

I've uninstalled the game and am now reinstalling it onto my C drive, and have just noticed that:

* it's not even the deluxe GOTY that includes all the DLCs
* it's a 27 GB download! Even the deluxe GOTY installer I have from GOG is only 5 GB, and I've noticed that GOG copies can be significantly larger than Steam backups for the same game. I suspect it's because there are 5 supported languages, and each language is implemented as a complete copy of the game, which is mad.

**Comment by Infernio** [comment]
Yep, it's because they ship all languages as separate copies of the game.

**Comment by Ortham** [comment]
OK, so I can run LOOT for Oblivion if I manually configure the install and local paths in LOOT's settings. However:

* `%LOCALAPPDATA%\Packages\BethesdaSoftworks.TESOblivion-PC_3275kfvn8vcwc\LocalCache\Local\Oblivion` doesn't exist, even after running the game and adjusting what plugins are active in its Data Files launcher dialog. I can only use `%LOCALAPPDATA%\Oblivion`. I wonder if already having the GOG version installed is related.
* When I try to apply a sorted load order, I get an access denied error. It works if I run LOOT as an admin though, it works, and as far as I can tell I've got all the necessary permissions on `%LOCALAPPDATA%\Oblivion` and `%LOCALAPPDATA%\Oblivion\plugins.txt`.

**Comment by Ortham** [comment]
Looking at this again, I've found that MS-Store Oblivion only creates `%LOCALAPPDATA%\Packages\BethesdaSoftworks.TESOblivion-PC_3275kfvn8vcwc\LocalCache\Local\Oblivion` if `%LOCALAPPDATA%\Oblivion` does not exist: it'll use an empty `%LOCALAPPDATA%\Oblivion` folder if you create one.

I also realised my access denied error was due to trying to set plugin timestamps, not because I was trying to edit `plugins.txt`, so I edited my post above to reflect that. I don't know if editing `%LOCALAPPDATA%\Packages\BethesdaSoftworks.TESOblivion-PC_3275kfvn8vcwc\LocalCache\Local\Oblivion\plugins.txt` would work, but from its permissions I don't see why it wouldn't.

One other issue I've found is that when I first boot up my PC, the files in `D:\Program Files\ModifiableWindowsApps\Oblivion GOTY (PC)` are not readable, but they become readable after I run Oblivion. Sending the computer to sleep or restarting doesn't seem to be enough to make them unreadable, only a full shutdown.

I've implemented support for detecting Microsoft Store game locations as detailed in Lojack's wiki page, and have [updated the documentation](https://github.com/loot/loot/blob/microsoft-store/docs/app/usage/initialisation.rst#microsoft-store-compatibility) to include some information about the problems related to that version of the games. That's currently in the `microsoft-store` branch.

@pStyl3 and @sibir-ine can you try that branch with the Microsoft Store games you've got? In particular I'd like to know if they also use `%LOCALAPPDATA%\<game>` if it already exists, or if that's just Oblivion-specific behaviour.

**Comment by pStyl3** [comment]
I have SSE installed through the MS Store (language is German), and I renamed `%localappdata%\Skyrim Special Edition` to `%localappdata%\_Skyrim Special Edition`. The moment I click on `Play` in MS Store the folder
`C:\Users\Alpha\AppData\Local\Packages\BethesdaSoftworks.SkyrimSE-PC_3275kfvn8vcwc\..` will get created.

If there are no mods installed for the game, the `C:\Users\Alpha\AppData\Local\Packages\BethesdaSoftworks.SkyrimSE-PC_3275kfvn8vcwc\LocalCache\Local\Skyrim Special Edition MS` folder will be empty. Once mods will be installed, e.g. `Unofficial Skyrim Special Edition Patch`, `Plugins.txt` will be created here.
```
# This file is used by Skyrim to keep track of your downloaded content.
# Please do not modify this file.
*unofficial skyrim special edition patch.esp
```
Deleting the folder `BethesdaSoftworks.SkyrimSE-PC_3275kfvn8vcwc` and creating an empty OR using a non-empty `%localappdata%\Skyrim Special Edition` folder - doesn't seem to create a `Plugins.txt` if I start the game through MS Store once again. The `Plugins.txt` will continue to be created in `BethesdaSoftworks.SkyrimSE-PC_3275kfvn8vcwc`.

**Comment by Ortham** [comment]
Hmm, so using the usual game local app data folder isn't consistent... Looks like I'll have to add some more logic to conditionally override that path if using an MS Store game.

Unfortunately, now nothing's happening when I try to launch Oblivion for testing...

**Comment by pStyl3** [comment]
Changing LOOT's `Install Path` to `D:\Program Files\ModifiableWindowsApps\Skyrim Special Edition (PC)\` and restarting LOOT seems to have worked.

![grafik](https://user-images.githubusercontent.com/10406657/155610736-3059d402-aa6a-44a3-b674-0b14bdef2d15.png)

**Comment by Ortham** [comment]
> Changing LOOT's `Install Path` for SSE to `D:\Program Files\ModifiableWindowsApps\Skyrim Special Edition (PC)\` and restarting LOOT seems to have worked.

Was LOOT unable to detect the game before you set that?

**Comment by pStyl3** [comment]
With an empty `Install Path` LOOT finds my Steam SSE:
![grafik](https://user-images.githubusercontent.com/10406657/155612836-4745c531-f02e-4bd1-b027-ad2c97141b2e.png)

**Comment by Ortham** [comment]
Oh, right - you'll need to also remove the registry entries in LOOT's config for SSE for it to fall back to the Microsoft Store version, I forgot about that.

**Comment by pStyl3** [comment]
Completely clearing both `Install Path` and `Install Path Registry Keys` resulted in the MS Store SSE being found (plus `Install Path` listing `D:\Program Files\ModifiableWindowsApps\Skyrim Special Edition (PC)`) after restarting LOOT.

**Comment by sibir-ine** [comment]
I tested with Morrowind, so the `plugins.txt` issue wasn't relevant. As for the registry keys, it did find it at first when it was installed to the default location, `D:\Program Files\ModifiableWindowsApps\Morrowind GOTY (PC)\` in my case. I then reinstalled it out of curiosity, & it got installed to a new location instead, `D:\XboxGames\The Elder Scrolls III- Morrowind (PC)\Content\`, which couldn't be found by default. I checked the registry entry according to the instructions in the WB article, & `mutableLocation` was present but empty. I searched my registry for that path to see if it was stored elsewhere, but, unfortunately, I couldn't find anything. I can't figure out how to get it to install it as it was before (it errors when installing it to `Program Files\ModifiableWindowsApps\` on any drive, presumably due to lack of permissions), so 🤷 Interestingly, when installed to a custom location like this, LOOT doesn't need to be run as admin (nor does WB, it seems), so I guess that's nice.

As a side note, while I was testing if admin privileges were required with the original default installation location (they were), I noticed that after attempting to apply a sorted order & being denied access, discarding it didn't update the UI as if it were discarded.

**Comment by Ortham** [comment]
My copy of Oblivion stopped launching, so I rebooted and found that it had somehow managed to nuke itself, and trying to install again failed with some "the drive isn't mounted" error (I didn't note down the exact message). From searching around, it happens a lot when istalling anywhere other than the system drive, which is pretty terrible... I then saw that there were updates available for the XBox and Microsoft Store apps, so I installed them and rebooted again, and I was able to download and install Oblivion again. 

Like sibir, this time it wanted to install it to `D:\XboxGames` instead of `D:\Program Files\ModifiableWindowsApps`, and after installation I see:

* there's no Registry key that mentions the install path
* admin privileges aren't needed to write to the game install directory
* the game install directory isn't unreadable between turning on my computer and running the game
* the game creates and uses `%LOCALAPPDATA%\Oblivion` and while the path in `%LOCALAPPDATA%\Packages` still exists, it's empty (it might be leftover from my previous installation)
* there's no longer an "Enable Mods" option on the page for Oblivion in the Xbox app.

Given all that, I'm inclined to keep the Registry-based detection of `ModifiableWindowsApps` installs, but update the documentation to:

* reflect that games installed to `ModifiableWindowsApps` might not use `%LOCALAPPDATA%\<game>` and as such might need the game's local path to be configured in LOOT
* mention that games installed through the Xbox app to locations outside `ModifiableWindowsApps` are supported but can't be detected
* recommend that games installed to `ModifiableWindowsApps` are reinstalled outside of that directory to avoid problems.

What do people think of taking that approach?

**Comment by Ortham** [comment]
Also @pStyl3 if you can get Skyrim SE installed to `XboxGames`, what folder does it store `plugins.txt` in?

**Comment by Ortham** [comment]
@sibir-ine @pStyl3 I think it might be possible to for LOOT to detect where the Xbox app is installing games to (whether or not it's the default `XboxGames` folder), but I need to know the full path to the game's Data folder to hardcode some parts of that path. Can you tell me the paths you have for Morrowind and Skyrim SE? (For Morrowind any of the localisation folders will do.)

**Comment by pStyl3** [comment]
> @pStyl3 If you've still got Skyrim SE installed in ModifiableWindowsApps, can you try creating %LOCALAPPDATA%\Skyrim Special Edition MS to see if it uses that? I only realised today that the MS suffix is present for Skyrim SE from the Microsoft Store, which may be why you found the normal folder wasn't used before.

I've tried that, but `Plugins.txt` continues to be created in `Packages` and will not be created in `%LOCALAPPDATA%\Skyrim Special Edition MS`.

I'll try reinstalling the game now.

**Comment by pStyl3** [comment]
Uninstalled the game, also updated MS Store + Xbox App, installed SSE to `C:\XboxGames`. Initially Plugins.txt was still in `Packages`, but when I deleted the `Packages` folder and created an empty `%localappdata%\Skyrim Special Edition MS` folder to see if that one would get used .. Plugins.txt would no longer show up in either of them..

So i've closed & opened MS Store and the Xbox App, and clicked in the Xbox App on (I believe?) a `Manage` button for SSE, not entirely sure. That resulted in the SSE files being "moved" (whatever that meant). The game is definitely installed in `C:\XboxGames\The Elder Scrolls V- Skyrim Special Edition (PC)\Content` though.

That being said, Plugins.txt is now being created in `%localappdata%\Skyrim Special Edition MS`.

**Comment by Ortham** [comment]
Thanks for that, annoying that it's a different folder for plugins.txt, I'm going to have to override that for detected "XBoxGames" installs...

**Comment by pStyl3** [comment]
> Given all that, I'm inclined to keep the Registry-based detection of `ModifiableWindowsApps` installs, but update the documentation to:
> 
> * reflect that games installed to `ModifiableWindowsApps` might not use `%LOCALAPPDATA%\<game>` and as such might need the game's local path to be configured in LOOT
> * mention that games installed through the Xbox app to locations outside `ModifiableWindowsApps` are supported but can't be detected
> * recommend that games installed to `ModifiableWindowsApps` are reinstalled outside of that directory to avoid problems.
> 
> What do people think of taking that approach?

Seems good to me. They seem to prefer `C:\XboxGames` now instead of `ModifiableWindowsApps`, so reinstalling it to `C:\XboxGames` if possible, should be better in the long run, for the game itself as well as third party tools.

**Comment by pStyl3** [comment]
Getting this error with `loot_0.17.0-169-gf45e6a3_microsoft-store-win64.7z`:
![grafik](https://user-images.githubusercontent.com/10406657/155813044-7a295c84-5b5a-4455-b35c-cd381191a9fe.png)
Also see the `loot-discussions` channel in Discord.

> [23:42:33.961957] [error]: Failed to evaluate condition "product_version("../SkyrimSE.exe", "1.6.323.0", <) and version("Unofficial Skyrim Special Edition Patch.esp", "4.2.6a", >=)". Details: An error was encountered while accessing the path "C:\XboxGames\The Elder Scrolls V- Skyrim Special Edition (PC)\Content\Data\../SkyrimSE.exe": Zugriff verweigert (os error 5)
[23:42:33.962044] [error]: "unofficial skyrim special edition patch.esp"'s masterlist metadata contains a condition that could not be evaluated. Details: Failed to evaluate condition "product_version("../SkyrimSE.exe", "1.6.323.0", <) and version("Unofficial Skyrim Special Edition Patch.esp", "4.2.6a", >=)". Details: An error was encountered while accessing the path "C:\XboxGames\The Elder Scrolls V- Skyrim Special Edition (PC)\Content\Data\../SkyrimSE.exe": Zugriff verweigert (os error 5)
[23:42:33.970506] [error]: Failed to evaluate condition "product_version("../SkyrimSE.exe", "1.6.317.0", >=) and product_version("../SkyrimSE.exe", "1.6.353.0", <)". Details: An error was encountered while accessing the path "C:\XboxGames\The Elder Scrolls V- Skyrim Special Edition (PC)\Content\Data\../SkyrimSE.exe": Zugriff verweigert (os error 5)
[23:42:33.970591] [error]: Caught an exception: Failed to evaluate condition "product_version("../SkyrimSE.exe", "1.6.317.0", >=) and product_version("../SkyrimSE.exe", "1.6.353.0", <)". Details: An error was encountered while accessing the path "C:\XboxGames\The Elder Scrolls V- Skyrim Special Edition (PC)\Content\Data\../SkyrimSE.exe": Zugriff verweigert (os error 5)

**Comment by Ortham** [comment]
I'm going to try getting all the games installed through Game Pass, I hope this won't take more than a month to solve, and after that I never want to touch the Microsoft Store again...

**Comment by sibir-ine** [comment]
> I think it might be possible to for LOOT to detect where the Xbox app is installing games to (whether or not it's the default `XboxGames` folder), but I need to know the full path to the game's Data folder to hardcode some parts of that path. Can you tell me the paths you have for Morrowind and Skyrim SE? (For Morrowind any of the localisation folders will do.)

`D:\XboxGames\The Elder Scrolls III- Morrowind (PC)\Content\Morrowind GOTY English\Data Files\`

**Comment by Ortham** [comment]
I've now downloaded almost all the games (just waiting on Fallout 3 now) and after that I can start testing what local app data folders the games create and/or use.

In the meantime, I can replicate the access denied issue when trying to read the executable versions for all games, and from what LizardWizard has said in Discord running the game doesn't solve it like it does for the old-style MS installs, and any permissions changes just get reverted and/or cause more problems. 

Unless my testing sees different results to LizardWizard's, I think `version` and `product_version` are just broken for MS games' official executables. It might be possible to introduce an alternative function, but reading from `appxmanifest.xml` is useless because the version number it contains is pretty meaningless for LOOT's use, and there's nothing in the Registry for the new-style MS installs, so I don't know where the data would come from.

Fortunately, this only impacts ~ 25 conditions in each of the Skyrim SE and Fallout 4 masterlists (to find them you can search `version("..`).

**Comment by Ortham** [comment]
The latest build should now correctly detect all new installs of games from the Microsoft Store / Xbox app, including using the correct local appdata path for those games. Old installs should also be correctly detected, but LOOT might not use the correct local appdata path for them because the logic for picking the path varies by game and I'm not able to test them any more.

I've also updated the [docs](https://github.com/loot/loot/blob/microsoft-store/docs/app/usage/initialisation.rst#microsoft-store-compatibility) with information on compatibility.

As far as I'm aware, the only outstanding issues are:

* LOOT might pick the wrong local appdata path for old game installs
* the `version` and `product_version` condition functions fail if they're given an official game executable to read

If you remove those condition functions from your local masterlist, sorting and masterlist update should work. I'm going to take a look at the masterlists using those conditions to see if the functions can be removed or replaced.

**Comment by Ortham** [comment]
I've been looking into whether it would make sense to treat permissions errors while evaluating `version` and `product_version` in the same way as non-existent versions or files. If the file or version in the file can't be found, the condition evaluates to true if and only if the comparator is `!=`, `<` or `<=`, i.e. a non-existent version is always less than all other versions.

The trouble is, if that's the result it means that:

* Users will be told that their game is incompatible with the xxSE version they're using when it isn't
* Users will be told their game is outdated when it isn't
* In a couple of cases, users will be told that a mod requires a newer version of the game when it doesn't

I'd rather just remove those messages than have them give bad advice.

Another option would be to update the conditions to first do a "is this file readable" check separately to the version check, which would work because condition evaluation short-circuits on the first false result. That could either be done by introducing a new function, or by updating the `file` condition - I don't think the latter would cause any problems, but maybe there's a case where you'd want to know a file exists but don't care if it's readable by LOOT or not?

So I'm currently prototyping a `readable(path)` condition function to be used like `readable("../SkyrimSE.exe") and product_version("../SkyrimSE.exe", "1.6.317.0", >=)`.

**Comment by pStyl3** [comment]
> I'd rather just remove those messages than have them give bad advice.

In case that no other solution could be found, removing the messages instead of them giving bad advise would be better. But if we can update the given functions, or replace them with new ones, that route should be the preferable one.

> Another option would be to update the conditions to first do a "is this file readable" check separately to the version check, which would work because condition evaluation short-circuits on the first false result. That could either be done by introducing a new function, or by updating the `file` condition - I don't think the latter would cause any problems, but maybe there's a case where you'd want to know a file exists but don't care if it's readable by LOOT or not?

I don't know if there is such a use case, but introducing a new function instead of updating `file` would circumvent any potential problems down the road.

**Comment by Ortham** [comment]
The latest build of the `microsoft-store` branch now supports the `readable` condition function, and I've pushed `add-readable-checks` branches for the `fallout3`, `falloutnv`, `fallout4` and `skyrimse` repositories. If you configure LOOT to use them, you should see no more errors.

**Comment by sibir-ine** [comment]
> I'd rather just remove those messages than have them give bad advice.
> 
> Another option would be to update the conditions to first do a "is this file readable" check separately to the version check, which would work because condition evaluation short-circuits on the first false result.

I'd definitely prefer something like the `readable` function you've implemented to removing the messages; it's a similar workaround to what we had to implement for https://github.com/loot/libloot/issues/66, so there's already precedent.

> That could either be done by introducing a new function, or by updating the `file` condition - I don't think the latter would cause any problems, but maybe there's a case where you'd want to know a file exists but don't care if it's readable by LOOT or not?

I can't think of any such case either; however, another solution could be parsing versions from unreadable files as if it had no version info. This would match what you see when you look at the _File version_ & _Product version_ fields in the _Details_ tab of `Morrowind.exe`, & I'm assuming it's the same for other MS/GP games. Then, we could add a check to those messages that the executable's version isn't 0 where necessary. I imagine this solution would be better logistically as we could just direct MS/GP users to a download link for the latest LOOT snapshot without telling them to use a separate masterlist branch, & we wouldn't have to maintain that branch separately until the next release.

However, since you've already implemented `readable`, I understand if you'd prefer to proceed with it instead.

**Comment by Ortham** [comment]
> I can't think of any such case either; however, another solution could be parsing versions from unreadable files as if it had no version info.

That's what this was about:

> I've been looking into whether it would make sense to treat permissions errors while evaluating `version` and `product_version` in the same way as non-existent versions or files. If the file or version in the file can't be found, the condition evaluates to true if and only if the comparator is `!=`, `<` or `<=`, i.e. a non-existent version is always less than all other versions.
> 
> The trouble is, if that's the result it means that:
> 
>     * Users will be told that their game is incompatible with the xxSE version they're using when it isn't
> 
>     * Users will be told their game is outdated when it isn't
> 
>     * In a couple of cases, users will be told that a mod requires a newer version of the game when it doesn't
> 
> 
> I'd rather just remove those messages than have them give bad advice.

The current docs are wrong/outdated, the version isn't set to 0 if not found, the quote above gives the correct behaviour (and I'm updating the docs to match).

**Comment by pStyl3** [comment]
Snapshot: `loot_0.17.0-174-g6a05f47_microsoft-store-win64.7z`
Install Path: `C:\XboxGames\The Elder Scrolls V- Skyrim Special Edition (PC)\Content`
Masterlist Source: `https://raw.githubusercontent.com/loot/skyrimse/add-readable-checks/masterlist.yaml`

I no longer get the error message shown in https://github.com/loot/loot/issues/1436#issuecomment-1051332993, adding new mods and sorting the load order (applying as well as discarding) seems to work fine. 👍

**Comment by Ortham** [comment]
Done in e631685afa201bbcd2c4293428f67ea51f1d12fd.
