### ISSUE TITLE
Invalid plugins aren't hidden unless changes are made when sorting

### ISSUE THREAD

**Issue by sibir-ine** [loot/loot#1443]
Invalid plugins are supposed to be hidden from LOOT's UI, but they aren't if you press `Sort Plugins` & no changes are made. Some parts of LOOT's UI require you to press `Sort Plugins` to update, so I would expect pressing it to be enough to hide invalid plugins. 

This can be tested with [`Mystic.esp`](https://www.nexusmods.com/skyrim/mods/5600/) for TES5 or [`Aetheric Cuteblade.esp`](https://www.nexusmods.com/oblivion/mods/41246/) for TES4.

**Comment by pStyl3** [comment]
Related old issue: #971

**Comment by Ortham** [comment]
I can replicate this, but only if the invalid plugins are at the end of the pre-sorting load order (so removing them doesn't change the load order index of any valid plugin). @sibir-ine does that match what you see?

**Comment by sibir-ine** [comment]
@Ortham Yes, I think that's accurate. When I manually sort it before a mod that it doesn't conflict with such that LOOT's algorithm shouldn't try to change my load order, it correctly hides it as well as disabling it & placing it at the bottom of the load order. However, if it's at the bottom, it doesn't get hidden if no changes to my load order are made. If changes are made, then it does get hidden correctly even if it's at the end.

**Comment by Ortham** [comment]
This should be fixed in the `fix-invalid-plugin-hiding` branch. I changed the behaviour for when plugins are hidden: before, hiding a plugin would count as a change (unless it was at the end of the load order, that was the bug). Now hiding a plugin doesn't count as making a change to the load order, but I'm not sure if that's the most sensible behaviour or not. It makes more sense for games like Oblivion where not setting a plugin's load order would mean you could sort and re-sort and always be shown "changes" until you uninstalled the invalid plugin, but for games like Skyrim SE where not specifying a load order position means the plugin is removed from the load order, removing an invalid plugin from the load order could be a real change...

I'd appreciate your opinions on which is the right or expected behaviour.

**Comment by sibir-ine** [comment]
If it's expected behavior to place the invalid plugin(s) at the bottom of the load order, I think that might be worth counting as a change. This evokes #377, where we might be able to differentiate between the load order being changed & an invalid plugin being "removed" i.e. disabled, placed at the bottom, & effectively treated like it doesn't exist. In that case, we could easily not count it as a change but show users what happened & what to expect.

**Comment by Ortham** [comment]
Thinking about this some more, I agree, so I've changed it back to always treating an ignored plugin as a change. That means you'll always get a change the first time you sort after opening LOOT until you uninstall the plugin, but that's better than hiding changes that might have an in-game impact.

**Comment by Ortham** [comment]
Done in c9ef7a83dc47a2826a532024b45d47dbcd2aa5d4.
