### ISSUE TITLE
Check if translation template file is up to date in CI

### ISSUE THREAD

**Issue by Ortham** [loot/loot#1444]
If the pre-commit hook script runs and makes changes to the POT file, it's not up to date, and should probably fail the build. Otherwise it's too easy to accidentally let the template get outdated.

That said, most of the time the changes are only minor source line number differences, and is that being inaccurate enough to warrant a failed build? Given that the file is supposed to be automatically kept up to date, it's probably not worth distinguishing between types of changes.

**Comment by Ortham** [comment]
While working on the qt branch I've found it very useful to remove the pre-commit hook, because when the time comes to tidy up the branch history by rebasing, moving commits around and squashing them, the merge conflicts caused by the `template.pot` file changes are a pain to deal with and just get in the way (since for every commit the `template.pot` can be newly generated). Having the CI build fail due to the `template.pot` not being up to date would make this unworkable. 

Perhaps there could be another independent workflow that runs and does the check though, so it can fail without affecting the actual CI build?

**Comment by sibir-ine** [comment]
A separate workflow sounds like the best solution for this issue. I think all that really matters is that we are made aware that the template is outdated before or soon after changes reach the default branch so that translators have some time to translate before a release. If it's a separate branch that will be frequently developed on before being merged, it's reasonable to wait until everything is stable before worrying about updating it for the reasons you stated. However, I think there should always be at least some indication that an update is needed so that it isn't forgotten.

**Comment by Ortham** [comment]
I added a `check-pot` job to the CI workflow in the `ci-check-pot` branch and tested it failing and succeeding. That branch branches off from `qt` because there are fewer dependencies involved in checking the pot file when there's no JS.

**Comment by Ortham** [comment]
Closing this because the new job is now in `master` as of 64481e14c492ecfebed26219952f8020b6f2cc94.
