### ISSUE TITLE
Refine translations section of CONTRIBUTING.md

### ISSUE THREAD

**Issue by sibir-ine** [loot/loot#1448]
~~Just an idea, but I think it would be beneficial for us to split the _Translating LOOT_ section of `CONTRIBUTING.md` into a section for translators & a section for team members.~~

~~Basically, the translators section would have all the information & considerations translators need _just_ to properly generate or update a `.po` file for their language & translate the line in `[CustomMessages]` in `installer.iss`.~~

~~Meanwhile, the team members section would have all the details about finalizing a localization i.e. adding the file name to `build_installer.ps1` & `installer.iss`, the details with `loot_settings.cpp` & `loot_settings_test.h`, etc.~~

~~That way, translators can focus solely on translating instead of worrying about details we can easily take care of after. If they want to finalize the setup, they can, but I thinks it's best not to give them more steps than necessary that may overwhelm translators with less coding experience.~~

I'll write up a draft in a pull request ~~if this idea seems worth pursuing~~.

~~**Note 1**: I'm not sure if adding the translation in `installer.iss` without any of the other setup causes the build to fail, but, if it does, we can ask them to just comment it out in the translators section & uncomment it in the team members section.~~

**Note 2**: we should probably link to a site where people can look up the POSIX locale code for their language where we first mention it in step 3 of _Translating the Installer_.

**Comment by Ortham** [comment]
I don't know how useful doing this would be, though I did write the current text. The `Translating the LOOT application` section is pretty much all information for translators, and the `Adding A New Translation` is for finalising (and says that the translator can include its changes in their translation "if you wish" because they aren't expected to make changes they may not be comfortable making. Maybe the separation between audiences can be made more obvious.

The installer is a bit more complicated, because it's almost all in one file, and I think the change to the `build_installer.ps1` script is trivial. Personally, I'd prefer a PR to include all the installer changes together, and if it's not done quite right we can always fix it as part of the review process.

> **Note 1**: I'm not sure if adding the translation in installer.iss without any of the other setup causes the build to fail, but, if it does, we can ask them to just comment it out in the translators section & uncomment it in the team members section.

I think it would fail if just the `[CustomMessages]` line was added.

**Comment by sibir-ine** [comment]
Okay, then I think it would be good to make it clearer that translators don't need to worry about getting the installer 100% right since we can easily provide corrections. I think we should also make it a bit clearer that translators don't need to worry about the _Adding A New Translation_ section.

Also, until we add context for every string, should we update the link to request context to point to #1438 instead?

**Comment by Ortham** [comment]
> Also, until we add context for every string as needed, should we update the link to request context to point to #1438 instead?

That would probably be more useful, yes.
