### ISSUE TITLE
What is blocking LOOT??

### ISSUE THREAD

**Issue by tizl10** [loot/loot#1506]
Something is blocking my LOOT from connecting to git, whenever I try to sort I get this error in the debug file:

Exception while executing query: Git operation failed. Details: -1; failed to send request: A connection with the server could not be established
: libgit2 error

I have seen this error referenced a few times in connection to Vortex and MO2 (I'm currently using MO2, but gave up on Vortex because of this same issue, I had thought it was an issue with Vortex at the time).

I can connect to the loot github page just fine through my browser.  I've tried adding firewall rules to allow loot through, both incoming and outgoing, and even tried completely shutting down both my AV (Webroot) and Windows Firewall, and still get the connection error while those are shut down.  I am not currently connected to a vpn.

What else could potentially be blocking the connection?  Is there a way I can follow the connection and see where it is getting blocked, or is there a cmd function where I can attempt the same connection loot tries, and see what happens?

**Comment by tizl10** [comment]
A couple more things, I found in another thread to try and connect through the git console, it apparently uses the same connection.  I was able to successfully run "git clone https://github.com/loot/skyrimse.git" through there.

Also in that same thread it mentioned perhaps TLS version needed to be updated to 1.2, I checked mine and it's at 1.3.

**Comment by sibir-ine** [comment]
@tizl10 Can you please supply [debug logs](https://loot.github.io/docs/help/How-To-Report-Issues-Helpfully.html) for the issue?

**Comment by SewageFace** [comment]
Having the same issue.

[18:00:10.859476] [warning]: Blocking load of resource at https://fonts.googleapis.com/css?family=Roboto+Mono:400,700|Roboto:400,300,300italic,400italic,500,500italic,700,700italic
[18:00:11.484217] [warning]: No masterlist present at C:\Users\Monster\AppData\Local\LOOT\Skyrim Special Edition\masterlist.yaml
[18:00:11.521517] [warning]: Chromium console message from http://loot/ui/app.bundle.js at line 9: You have set a custom wheel sensitivity.  This will make your app zoom unnaturally when using mainstream mice.  You should change this value from the default only if you can guarantee that all your users will use the same hardware and OS configuration as your current machine.
[18:00:34.138865] [error]: Exception while executing query: Git operation failed. Details: -1; failed to send request: The operation timed out
: libgit2 error
[18:00:34.148314] [error]: Chromium console message from http://loot/ui/app.bundle.js at line 5723: Error: Oh no, something went wrong! You can check your LOOTDebugLog.txt (you can get to it through the main menu) for more information.
    at onFailure (http://loot/ui/app.bundle.js:5723:9239)

I'm running Windows 10. TLS 1.2 was enabled by default, so that's out. I ran it by itself, not through MO2, still giving me the same error.

Putting the masterlist.yaml in AppData/Local/LOOT/Skyrim Special Edition gives me this error:

[18:12:27.745669] [warning]: Blocking load of resource at https://fonts.googleapis.com/css?family=Roboto+Mono:400,700|Roboto:400,300,300italic,400italic,500,500italic,700,700italic
[18:12:28.387821] [error]: An error occurred while parsing the metadata list(s): yaml-cpp: error at line 59, column 48: illegal map value
[18:12:28.389406] [warning]: Not a Git repository: C:\Users\Monster\AppData\Local\LOOT\Skyrim Special Edition
[18:12:28.437946] [warning]: Chromium console message from http://loot/ui/app.bundle.js at line 9: You have set a custom wheel sensitivity.  This will make your app zoom unnaturally when using mainstream mice.  You should change this value from the default only if you can guarantee that all your users will use the same hardware and OS configuration as your current machine.
[18:13:17.658011] [error]: An error occurred while parsing the metadata list(s): yaml-cpp: error at line 59, column 48: illegal map value
[18:13:17.659713] [error]: Exception while executing query: Git operation failed. Details: -1; failed to send request: The operation timed out
: libgit2 error
[18:13:17.665852] [error]: Chromium console message from http://loot/ui/app.bundle.js at line 5723: Error: Oh no, something went wrong! You can check your LOOTDebugLog.txt (you can get to it through the main menu) for more information.
    at onFailure (http://loot/ui/app.bundle.js:5723:9239)

**Comment by sibir-ine** [comment]
@SewageFace Can you please enable debug logging in LOOT & attach that log? Also, please either attach the file to a comment or upload the contents to a service like Pastebin & link to it. Read the article I linked previously for more details.

**Comment by SewageFace** [comment]
Sorry about that.

[LOOTDebugLogMasterlist.txt](https://github.com/loot/loot/files/6489760/LOOTDebugLogMasterlist.txt)

I have Skyrim installed to the D drive, same with LOOT. I'm completely starting over since my laptop crashed a while back and I lost everything, so this is a fresh install. I've already launched Skyrim and went through the intro cutscene on a new file, cause I know sometimes you have to just launch it for it to work properly. I have no idea if any of that information is relevant, but I figured I'd throw it out there.

**Comment by sibir-ine** [comment]
@SewageFace Take a look at [this section](https://loot.github.io/docs/help/LOOT-FAQs.html#git-errors) of the FAQ, especially making sure nothing is preventing LOOT from reaching the online masterlist.

**Comment by tizl10** [comment]
I apologize that I never got back to this, work/life pulled me away.  In the end, I just manually downloaded and placed the latest masterlist.yaml file, and I was able to run Loot that way.  That didn't work for me when I was trying to use Vortex, but it worked with MO2, so I'm just going to stick with that for now.

**Comment by SewageFace** [comment]
> @SewageFace Take a look at [this section](https://loot.github.io/docs/help/LOOT-FAQs.html#git-errors) of the FAQ, especially making sure nothing is preventing LOOT from reaching the online masterlist.

There wasn't a .git file in there. I've added LOOT as an exception to the Windows firewall. Getting this debug log:
[LOOTDebugLogGit.txt](https://github.com/loot/loot/files/6496592/LOOTDebugLogGit.txt)

If I manually add the masterfile.yaml I get this log: 
[LOOTDebugLogManualMasterList.txt](https://github.com/loot/loot/files/6496598/LOOTDebugLogManualMasterList.txt)
I made sure to download the SE version and not the Skyrim version.

The FAQ says:
> Replace skyrim with morrowind, oblivion, fallout3, falloutnv, fallout4 or skyrimse as necessary in the URL and the folder path.

However my folder path is \AppData\Local\LOOT\Skyrim Special Edition, not \AppData\Local\LOOT\Skyrimse. Does that matter? I deleted the Skyrim Special Edition folder, but it created a new one after I ran it again.

**Comment by pStyl3** [comment]
@SewageFace 
Can you open this [link](https://github.com/loot/skyrimse)?

The `.git` subfolders within `%localappdata%\LOOT\<Game>\` are usually hidden. In Windows file explorer, select the index tab `View` and set the hook in front of `Hidden Elements`. You now should be able to see the `.git` folder.

`Skyrim Special Edition` is the correct foldername. I think we need to update the FAQ on that aspect, the folder names also start with an uppercase letter, and not with a lowercase one as the FAQ suggests.

**Comment by SewageFace** [comment]
> @SewageFace
> Can you open this [link](https://github.com/loot/skyrimse)?

I can. No issues there.
> The `.git` subfolders within `%localappdata%\LOOT\<Game>\` are usually hidden. In Windows file explorer, select the index tab `View` and set the hook in front of `Hidden Elements`. You now should be able to see the `.git` folder.

I don't. :( 
![Hiddenfiles](https://user-images.githubusercontent.com/84208111/118555858-2f503c00-b731-11eb-967c-55fa318bbb7e.png)

**Comment by pStyl3** [comment]
Out of curiosity, when was the last time you restarted your PC? If it has been more than a few days, could you restart it and see if something changes?

**Comment by SewageFace** [comment]
Nope. I appreciate the help though :)

**Comment by pStyl3** [comment]
In LOOT's settings, what are your entries for `Masterlist Repository URL`, `Masterlist Repository Branch`, `Install Path` and `Install Path Registry Key`?

Also, if you completely uninstall LOOT and also make sure that the LOOT folder in `%localappdata%` is removed, then install [this snapshot](https://loot.jfrog.io/ui/repos/tree/General/loot%2Fmaster%2Floot_0.16.0-204-g74cf1d4_master-win32.7z), (simply extract the archive and copy & paste it's content to some LOOT folder in D), does that fix it for you?

**Comment by SewageFace** [comment]
Masterlist Repository URL: https://github.com/loot/skyrimse.git
Masterlist Repository Branch: v0.15
Install Path: D:\Steam\steamapps\common\Skyrim Special Edition\
Install Path Registry Key: Software\Bethesda Softworks\Skyrim Special Edition\Installed Path

No dice with the snapshot, still not able to connect to get the master list.

**Comment by pStyl3** [comment]
Can you enable full debug logging in LOOT's settings with the snapshot you just installed, and provide us once more a debug log?
Is your Windows up to date or are there patches for it you could install?
Do you use an anti-virus tool, and if so could you add LOOT to it's exception list as well?

**Comment by pStyl3** [comment]
@SewageFace In case you still experience the issue described above, please check out the new official version, [LOOT 0.16.1](https://github.com/loot/loot/releases/tag/0.16.1).

**Comment by sibir-ine** [comment]
@tizl10 @SewageFace Since these seem to be connectivity issues, I don't think there's much more we can do to help. As discussed previously, you can at least download the masterlists manually as you've both done. If you're also unable to update your masterlists due to connectivity issues, you'll probably have to turn off **Update masterlist before sorting** (& maybe **Check for LOOT updates on startup** if that's causing issues as well) in the settings menu & update it manually. You can follow the masterlists' repositories to get notified when they're updated. I don't know if there's an option to receive notifications per commit, but there is one to receive notifications by pull request, which we use for virtually every masterlist update. Unless you two have any further questions, we'll close this issue.

**Comment by sibir-ine** [comment]
No response, so I'll close this.
