### ISSUE TITLE
Strings Missing Translation Support

### ISSUE THREAD

**Issue by RacerBG** [loot/loot#1527]
When you open "Edit Metadata" -> "Load After" -> "ADD NEW ROW", the red text "A value is required." is not translated. I searched for it in "template.pot" but I could not find it. It would be nice to have a translation support for this string too. :smiley: 

EDIT 1: The name of the dark theme "dark" should be made translatable too.

EDIT 2: The title "Groups Editor", the link "View Documentation" and the buttons "CANCEL" and "APPLY" on the same page.

EDIT 3: The "About" page could further be translated (the text "Copyright © 2012 WrinklyNinja" and everything below it).

EDIT 4: This error, after entering invalid metadata: "File object has an invalid condition: Failed to parse condition "". Details: The parser did not consume the following input: """

Regards,
Georgi

**Comment by Ortham** [comment]
* `A value is required` - I think this comes from the `paper-input` component, I'll need to check if it can be replaced with a translatable value (I assume so).
* `dark` - this is taken from the theme's filename, so isn't translatable without renaming the file. That could maybe be done by the LOOT installer, but that would be unlike other text (because changing the language in LOOT wouldn't change the filename).
* Groups editor buttons - this is just an oversight, easily fixed.
* About dialog: the copyright notice is legal text, and translations are [not officially valid](https://www.gnu.org/licenses/translations.html). We could swap the text for an unofficial translation, but I don't think that's worth doing considering the importance of the text being correct.
* That error is generated by the backend and cannot be translated. We could hide it away in the debug log, but I think it's more useful to display it, even if it's not easily understood by them.

**Comment by RacerBG** [comment]
> 
> 
>     * `A value is required` - I think this comes from the `paper-input` component, I'll need to check if it can be replaced with a translatable value (I assume so).
> 
>     * `dark` - this is taken from the theme's filename, so isn't translatable without renaming the file. That could maybe be done by the LOOT installer, but that would be unlike other text (because changing the language in LOOT wouldn't change the filename).
> 
>     * Groups editor buttons - this is just an oversight, easily fixed.
> 
>     * About dialog: the copyright notice is legal text, and translations are [not officially valid](https://www.gnu.org/licenses/translations.html). We could swap the text for an unofficial translation, but I don't think that's worth doing considering the importance of the text being correct.
> 
>     * That error is generated by the backend and cannot be translated. We could hide it away in the debug log, but I think it's more useful to display it, even if it's not easily understood by them.

Understood. I'm fine with fixing the red text and the text in the Groups Editor. The others can be left as they are. :smiley:

**Comment by RacerBG** [comment]
![Untitled](https://user-images.githubusercontent.com/68707872/120927530-c9305680-c6e9-11eb-9164-77e36890cd13.png)

**Comment by Ortham** [comment]
Done as of f97da190b74fe9ffe33dd6807d0558430f8e2048.
