### ISSUE TITLE
Feature Request: Proper Masterlist Editing UI

### ISSUE THREAD

**Issue by BellCubeDev** [loot/loot#1651]
# Why?
Because I'm not sure anyone particularly enjoys writing YAML. The current edit UI, while sufficient for user-defined rules, does not follow the formatting that the Masterlists use. Furthermore, conditions are a bit of a pain. Here's some of what I hope to see:

## Important
* Formatting consistent with Masterlists
* Popout Window Message Editor with support for predefined messages and subs AND a preview of the message
* Popout Window Conditions Editor with "blocks" of conditions and fields. I'll come up with a visualization soon™.
* Suggest names of existing files & plugins

## Minor
* Ability to create a fork and submit a pull directly from LOOT's interface, given GitHub credentials (see [GitHub Desktop](https://github.com/desktop/desktop) for examples)
* Built-in YAML editor with semi-realtime linting and LOOT-specific functions such as allowing easy reorder of plugins via drag-and-drop

As always, the minor, less important ones require the most work 😆.

**Comment by Ortham** [comment]
I think this *could* be done, but I don't think it should be part of the LOOT application:

* What you've requested does not fit anywhere in the current UI
* The only crossover with existing functionality is suggesting names of existing files and plugins
* You wouldn't be able to build on top of libloot, because it doesn't round-trip the YAML (e.g. it doesn't preserve things like comments)
* LOOT is fairly tightly focussed towards helping mod users sort their load orders, and introducing this functionality would be going in a quite different direction with a different target audience.

Given that, I'm going to close this as wontfix. That's not to say this shouldn't be done - if anyone wants to build a masterlist editor like this I'd be interested to see it, and am as always open to questions and discussions. It's just that I don't think such an editor would benefit from being part of this codebase, or that this codebase would benefit from having such an editor, and I'm not interested in building such an editor myself.
