### ISSUE TITLE
Exception while executing query: Git operation failed. Details: -1; failed to send request: The operation timed out : libgit2 error

### ISSUE THREAD

**Issue by Masteidel** [loot/loot#1690]
I've been having issues with LOOT being unable to connect to Github. I've already tried disabling my firewall and following the instructions on the FAQ for this kind of issue. This is a problem with both LOOT on its own and LOOT built into Mod Organizer. I've included my log files for both.
[LOOTDebugLog.txt](https://github.com/loot/loot/files/8019788/LOOTDebugLog.txt)
[mo_interface.log](https://github.com/loot/loot/files/8019789/mo_interface.log)

**Comment by sibir-ine** [comment]
Just FYI, we can't really do anything with MO2 logs. However, going off your LOOT debug log, it seems to be a connectivity issue. If deleting your `.git` folders & making an exception for LOOT in your firewall don't work, you'll have to manually update your masterlists for now as described in the FAQ. You'll want to disable `Update masterlist before sorting` in the settings menu as well.

The next version will drop masterlist updates via Git, so that'll hopefully resolve some connectivity issues like these. You can try it with the [snapshot builds](https://loot.jfrog.io/ui/repos/tree/General/loot).

**Comment by sibir-ine** [comment]
Closing this as a connectivity issue & therefore not an issue with LOOT. If you need further help troubleshooting, feel free to ask in our Discord server, forum thread, or this issue.
