### ISSUE TITLE
garbage

### ISSUE THREAD

**Issue by sebastianbhahn** [loot/loot#1692]
Whoever designed this software has apparently never used any operating system with a file system before, and has no idea how to organize their directories properly; and apparently also doesn't know how to access the file explorer to enable users to select and set up said directories, since users are expected to input directories manually; and even then, this software wants several vaguely defined directories input into it, while it doesn't indicate what these multiple directories are for or where they should be within the file system in relation to one another or to this software's directory. This software also wants access to registry keys, which shouldn't at all be necessary, and likewise with the repository URLs it wants. This software is completely unusable.

**Comment by Ortham** [comment]
This isn't the place to post ignorant rants, pick literally almost anywhere else on the Internet if you want to do that. I've blocked you because I don't see any attempt in what you've written to engage in good faith and don't want the hassle of having to deal with you beyond this. 

That may be a bit harsh, as your writing could be interpreted as hyperbolic rather than being rude or attacking outright (which is what I've banned others for in the past), but there are pleasant, constructive ways to communicate your concerns, and you chose not to take any of them.
