### ISSUE TITLE
Add Hide Creation Club plugins filter

### ISSUE THREAD

**Issue by pStyl3** [loot/loot#1697]
Besides Bethesdas official game plugins (e.g. `Skyrim.esm`, `Dawnguard.esm` etc), there are many "Creation Club" plugins for Skyrim Special Edition and Fallout 4 (e.g. `ccasvsse001-almsivi.esm` or `ccBGSFO4016-Prey.esl`).

These through Bethesda curated plugins are listed in `Skyrim.ccc` (SSE) and `Fallout4.ccc` and it would be great to be able to `Hide Creation Club plugins` in LOOT, as the amount of CC mods is significantly higher than the amount of normal game plugins.

**Comment by Ortham** [comment]
libloadorder already reads the CCC file as part of identifying implicitly-active plugins, and exposes an API for getting a list of implicitly-active plugins, but since reading the CCC file is simple and the implicitly-active plugins list also includes official plugins I think it would be better for LOOT to do its own reading of the CCC file when loading a game. The filter can then check if a plugin name is included in the set of plugin names that were read from that file.

**Comment by Ortham** [comment]
I've implemented this in the `creation-club-filter` branch.

**Comment by Ortham** [comment]
Done in 4c88b66d1cfeab04ba75e0390cfeeee4e2e376ae.

**Comment by pStyl3** [comment]
Works great, thanks.
