### ISSUE TITLE
MOD ORGANIZER WILL NOT OPEN LOOT! LOOT WON'T OPEN AT ALL TOO!

### ISSUE THREAD

**Issue by RevaTheConqueror** [loot/loot#1705]
Just redownloaded LOOT 5 times,k in 5 different locations, disabled antivirus software, I've literally remade the paths in Mo2 so much times now. When I pless RUN, it opens up the usual stuff, preparing -vfs. When it finishes preparing, it doesn't open LOOT, just stops the process, going back to how mo2 normally looks. It was working perfectly yesterday, whats the issue now???

**Comment by Ortham** [comment]
I don't know why it's not working, but you can try using [this snapshot build](https://loot.jfrog.io/artifactory/loot/master/loot_0.17.0-183-gf121f6b_master-win64.7z).

**Comment by sibir-ine** [comment]
@RevaTheConqueror, there's a new version of LOOT, so please try it to see if it runs now. If not, make sure it runs outside of MO2 first. If it still doesn't please enable debug logging & upload a debug log. Otherwise, if the issue only occurs with MO2, you'll have to troubleshoot with them as the issue would be with MO2 & not LOOT itself.

**Comment by sibir-ine** [comment]
I'll close this due to lack of response. @RevaTheConqueror, if you're still having issues, feel free to ask for more help in this issue or at [our Discord server](https://loot.github.io/discord/).
