### ISSUE TITLE
User Interface

### ISSUE THREAD

**Issue by Cristi80** [loot/loot#1706]
1. Sort Plugins and Update Masterlist buttons are now on the left side which in my opinion is kinda clunky also the direct Search function is now bundled in Game branch which makes it less practical. 
2. The User Interface is a bit uneasy on eyes a darker background and slighlty bigger font/simbols would be perfect (i am aware of the Dark Theme).
3. And maybe a Jump Back button to reset left/right sliders to the upper page? Sorting doesnt do that anymore :|

**Comment by StudMuffin420** [comment]
Why did you turn it so ugly?

**Comment by sibir-ine** [comment]
> Why did you turn it so ugly?

Please refrain from providing feedback that isn't civil & constructive. Simply calling it ugly doesn't tell us how we can improve the UI, it's just rude & uncalled-for.

**Comment by Ortham** [comment]
> 1. Sort Plugins and Update Masterlist buttons are now on the left side which in my opinion is kinda clunky also the direct Search function is now bundled in Game branch which makes it less practical.

The reasoning for the position of those buttons is that toolbars are generally left-aligned, so this brings LOOT into line with other desktop applications. I removed the search button from the toolbar because I thought it was relatively unused and the menu entry also tells you about the Ctrl-F shortcut, but maybe I'm wrong about that.

> 2. The User Interface is a bit uneasy on eyes a darker background and slighlty bigger font/simbols would be perfect (i am aware of the Dark Theme).

The font size for most text should be the default desktop font size, as in File Explorer and other desktop applications. Which icons do you find too small? I can increase the size of the icons on plugin cards, but I think the menu icon size is fixed.

> 3. And maybe a Jump Back button to reset left/right sliders to the upper page? Sorting doesnt do that anymore :|

Do you specifically want the lists to scroll to the top after sorting? Would a scroll-to-top button really be useful in general?

> Why did you turn it so ugly?

I appreciate that the UI doesn't look as stylish (if that's the right word) as it did, but I think the benefits outweigh the drawbacks. I may be able to make improvements given specific constructive feedback, but just saying it's ugly isn't that.

**Comment by Cristi80** [comment]
> > 1. Sort Plugins and Update Masterlist buttons are now on the left side which in my opinion is kinda clunky also the direct Search function is now bundled in Game branch which makes it less practical.
> 
> The reasoning for the position of those buttons is that toolbars are generally left-aligned, so this brings LOOT into line with other desktop applications. I removed the search button from the toolbar because I thought it was relatively unused and the menu entry also tells you about the Ctrl-F shortcut, but maybe I'm wrong about that.
> 
> > 2. The User Interface is a bit uneasy on eyes a darker background and slighlty bigger font/simbols would be perfect (i am aware of the Dark Theme).
> 
> The font size for most text should be the default desktop font size, as in File Explorer and other desktop applications. Which icons do you find too small? I can increase the size of the icons on plugin cards, but I think the menu icon size is fixed.
> 
> > 3. And maybe a Jump Back button to reset left/right sliders to the upper page? Sorting doesnt do that anymore :|
> 
> Do you specifically want the lists to scroll to the top after sorting? Would a scroll-to-top button really be useful in general?
> 
> > Why did you turn it so ugly?
> 
> I appreciate that the UI doesn't look as stylish (if that's the right word) as it did, but I think the benefits outweigh the drawbacks. I may be able to make improvements given specific constructive feedback, but just saying it's ugly isn't that.
