### ISSUE TITLE
Update Chinese translation

### ISSUE THREAD

**Issue by zhuabaobao123** [loot/loot#1707]
Great God, look forward to your update on Chinese characters

**Comment by sibir-ine** [comment]
Unfortunately, none of us are actually fluent in any variant or dialect of Chinese, written or otherwise, so we depend on contributors for translations. If you're interested in updating our Simplified Chinese translation or providing a translation for a different variant (e.g., Traditional or any other variant covered by a [POSIX locale code](https://www.gnu.org/software/gettext/manual/html_node/Locale-Names.html)), we'd be happy to accept your contributions. You can learn more about translating LOOT & the masterlists at https://github.com/loot/loot.github.io/issues/77.

**Comment by zhuabaobao123** [comment]
I don't know what software to use to translate qt_zh_CN files, xTranslator and EET4 can't translate

**Comment by zhuabaobao123** [comment]
How can I help you Chineseize,

**Comment by sibir-ine** [comment]
For LOOT itself, you can take a look [here](https://github.com/loot/loot/blob/master/CONTRIBUTING.md). For translating the masterlists, you can read the _Masterlist Localization_ section of https://github.com/loot/loot.github.io/issues/77.

**Comment by pStyl3** [comment]
I'll close this issue, because we already track localization progress for the LOOT application in issue 77 that @sibir-ine has mentioned above.

@zhuabaobao123 in case you find the time to help out with the Chinese localization you will be very welcome indeed. If you need any help, please see the links sibir provided and don't hesitate to ask. We also have a `translations` channel on our Discord server, where we can discuss things.
