### ISSUE TITLE
When changing styles, you have to reload to take effect

### ISSUE THREAD

**Issue by Prepubescent-Blastoise** [loot/loot#1714]
The button says Save, but there is no notification you have to close the program and reload. But if I don't like it, then I have to change, close, reload again. This could be fixed to change when you press save.

**Comment by Ortham** [comment]
There are tooltips on the labels for the language and theme dropdowns saying they apply on restart, but getting those tooltips to display is not obvious...

As a semi-temporary measure I'll add explanatory text at the bottom of the content area (below the prelude source input) so that it's more obvious. I say semi-temporary because I don't intend to make changing the language apply immediately (I did briefly experiment with this but it was a pain), and I'm not sure how easy it'll be to apply themes immediately (a lot of stuff might need to be explicitly re-drawn), but I can see that being able to view themes without a restart would be useful.

**Comment by Ortham** [comment]
Supporting this is made difficult by the fact that LOOT uses a combination of QPalette and style sheets for its theming, and while a the UI can be easily updated to reflect a style sheet change, I haven't figured out how to reliably do the same for a QPalette change.

I've been able to replicate the palette colours using style sheets for most UI elements, but the following still depend on palette colours, so I need to figure out an alternative approach:

- [ ] Icons colour
- [ ] Groups editor node, edge and label colours
- [ ] Hyperlink text colour

I've got an idea for the first two, but hyperlinks are styled using Qt itself and I think they're the main reason I ended up mixing QPalette with style sheets in the first place.

**Comment by Ortham** [comment]
I've made more progress, but hit an issue where going from the dark theme to the light theme doesn't update some styling. I think this is happening because there are selectors in the dark theme that aren't in the light theme, and the styling they set isn't replaced so it's not removed - copying some rules into the light theme and changing their values does apply those values. However, that's not ideal because there's some styling that I want to leave implicit because I can't replace the default styling in the style sheet.

There's also an issue related to the fact that there's no way to set the colour of placeholder text in a text input separately to the colour of actual value text, so I need to add code for each input with a placeholder to make sure it switches styling appropriately...

**Comment by Ortham** [comment]
This is now done in the `hot-load-theme` branch, but I've seen a lot of inconsistency in getting styling applied, so I think it'll need more manual testing before it gets merged.

**Comment by Ortham** [comment]
I've merged this into master as of bfabf036623b8f2f4134280b6027fb1e470165ac, if there are still issues they'll get fixed as they're spotted.
