### ISSUE TITLE
Editor is Open icon is wrong color for unfocused selected row

### ISSUE THREAD

**Issue by pStyl3** [loot/loot#1717]
This issue occurs, when the editor is opened through the right-click menu in LOOT's right pane, and the sidebar has not yet been clicked on.

![grafik](https://user-images.githubusercontent.com/10406657/158040096-a6fed535-e9ef-402f-8483-8e5331c00374.png)

After clicking on for example the sidebar's scrollbar:
![grafik](https://user-images.githubusercontent.com/10406657/158040112-f7926bd0-0941-49aa-8641-a9f6bba57518.png)

**Comment by Ortham** [comment]
Isn't this just a contrast issue? I can see the pen icon in your first screenshot, it's just white on a light grey background.

**Comment by pStyl3** [comment]
How on earth did you see that? 😄 I zoomed in 800% with PhotoFiltre and still couldn't see a difference. However, creating the negativ of the image revealed this:

![grafik](https://user-images.githubusercontent.com/10406657/158040777-2e0b061e-1439-4b66-84e9-c5db0605852d.png)

So yeah, it's there, just .. very white.

**Comment by Ortham** [comment]
Unfortunately I don't think this is something we can change, I remember trying to use the dark icon when the row is selected but the list does not have focus and couldn't find a way to specify the icon for that state.

**Comment by Ortham** [comment]
Closing this as it turned out to be a monitor contrast issue.

**Comment by Ortham** [comment]
Reopened as it is would be good to have the correct icon used for unfocused selected rows, and maybe I'll be able to solve it at some point...

**Comment by Ortham** [comment]
It looks like the behaviour has changed (possibly when updating to Qt 6.5.1?). Here's the highlighted colouring with the list focussed:

![image](https://github.com/loot/loot/assets/2430738/5213c5b2-6f86-434d-a3b3-d892e3292db8)

and here's the list unfocused:

![image](https://github.com/loot/loot/assets/2430738/f90a22ed-71e1-4048-8420-6d6734b7d885)

I've changed the behaviour so that the text colour won't switch when the list loses focus, since the background colour no longer changes.
