### ISSUE TITLE
load after rules section with blank entry causes loot to ignore load after rules

### ISSUE THREAD

**Issue by walkswithwolf** [loot/loot#1743]
When adding load after rules to a plugin, if you add a blank entry and leave it blank (which is hard to see in dark mode), loot will ignore all load after rules.

Edit: Forgot to mention loot version 0.18.2 build af8cf16e

**Comment by sibir-ine** [comment]
I can't reproduce this. Can you please make sure your masterlist is up-to-date? If you still experience the issue, can you please elaborate on the circumstances in which you experienced this, i.e., with what game & what plugins, & [provide a full debug log](https://loot.github.io/docs/help/How-To-Report-Issues-Helpfully.html#supplying-log)?

**Comment by walkswithwolf** [comment]
Please close this ticket.  Figured out the issue.

Tried to duplicate it again, and worked as expected.  Then I tried the loot button in mo2, issue returned. I use the mo2 button for quick sorts, and launch the full loot app for major sorts.  The mo2 button (mo2 internal loot implementation) is not  up to date with the new loot changes (including new groups, which was the reason it was not sorting properly).

Sorry for the false report.

**Comment by sibir-ine** [comment]
Yeah, MO2 hasn't been updated for v0.18.x yet, so it's still stuck on the outdated v0.17.x masterlist. I believe they're already aware of it & will update when they get the chance. However, I don't recall any new groups being added since v0.18.0 released. The locations of LOOT's game profiles were moved & are automatically migrated on launch, so, since MO2 is still using the old location, it's LOOT implementation won't pick them up unless you manually copy them back. If you have any user groups or rules, that might've been what you were seeing.
