### ISSUE TITLE
Convert separate search dialog window to in-window dialog

### ISSUE THREAD

**Issue by sibir-ine** [loot/loot#1769]
[Requested](https://forums.nexusmods.com/index.php?showtopic=5002060/#entry112386833) in the Nexus forum

The request is to convert the search dialog window into a search box that's built into the toolbar to prevent opening a second window. There's plenty of room laterally to add the various components of the search dialog, but it might look a bit awkward. Dynamically expanding the toolbar downward or adding some kind of sub-toolbar would probably look better & make it more obvious that the components are all connected.

Of course, it's not like a separate window is all that abnormal to begin with. Applications like Notepad++ make use of it, though NP++'s is much more populated with different options & modes.

**Comment by Ortham** [comment]
I think I put it in a separate dialog because I looked at how other applications and it was a split between "put it in a separate non-modal dialog" and "put it somewhere inline", and there was very little agreement about *where* inline for those that took that option, so the modal dialog seemed like the more "standard" approach.

I don't have a particularly strong opinion about this, but I also don't feel like moving it into the toolbar (or a separate toolbar) so I'm going to close this. If anyone can come up with a persuasive argument for why it should change then I'd be willing to reopen this.
