### ISSUE TITLE
General information card sized incorrectly after switching games

### ISSUE THREAD

**Issue by pStyl3** [loot/loot#1781]
Under certain conditions, the heigth of plugin cards is sometimes unstable as well as unintuitive. One key factor here seems to be that LOOTs entire window is getting displayed rather slim rather than it getting displayed in full screen.

Here's a first example:
![LOOT_AqL4K6ytUW](https://user-images.githubusercontent.com/10406657/184808933-10bad59e-3dc2-44e5-8d06-e96662b8bf32.gif)

Now I've deleted the `LOOT` folder in `localappdata` and managed to get to the point the issue occurs by updating the masterlist of one installed game and *then* switching to another game that is installed.
![LOOT_AxbL5bAOp0](https://user-images.githubusercontent.com/10406657/184809477-14ec4e07-4a0f-4cbb-b02e-3a91b6af0295.gif)

In addition to the above, sometimes there is too much empty space above a plugin name:
![grafik](https://user-images.githubusercontent.com/10406657/184809704-bebd9814-4ba1-4c32-a576-0f8d7164121e.png)

**Comment by sibir-ine** [comment]
I've noticed this when updating via the installer since that purges masterlists, but fetching them again seems to fix it. Though, if this can be fixed, I imagine that'd avoid some confusion for users.

**Comment by Ortham** [comment]
I can replicate this with pStyl3's instructions, but I can also replicate it when one game already has a masterlist and the other does not, it just takes a couple more switches to show up, so no update is needed. I can't get it to show up if both games already have a masterlist (though presumably it would manifest if an update added or removed a message), or if neither game has a masterlist and no masterlist is downloaded.

It's something to do with the size hint cache, as disabling it stops the bug from happening. The cache isn't cleared when switching games, but that's intentional. It could be because the cached data for the general info card doesn't include any of the table content, which doesn't directly affect the height but does affect the width of the content?

I've pushed a commit that ignores cached size hints for only the general info card, which seems to avoid the issue. @sibir-ine @pStyl3 can you test the `fix-card-sizing` branch to see if you can still replicate the issue? If not, then constantly recalculating the size of a single card isn't hugely expensive, but I'd still like to investigate a bit more to try and actually identify and fix the underlying issue.

**Comment by sibir-ine** [comment]
Yup, that seems to have fixed it 👍

**Comment by pStyl3** [comment]
The general information card works as intended now. There's still this though:

![grafik](https://user-images.githubusercontent.com/10406657/185050998-a5720dd0-5da7-4852-abbd-3b57a04b5ae2.png)

I'm not seeing a pattern yet, but when making the LOOT window smaller, some of the plugin cards will have additional empty space added to them above the plugin name, while others stay normal in that regard.

**Comment by Ortham** [comment]
@pStyl3 Could you open a separate issue for that? Even if they've got the same underlying cause, you're seeing two separate behaviours and I can only investigate them one at a time, having them both in the same thread is just confusing.

**Comment by pStyl3** [comment]
Done: https://github.com/loot/loot/issues/1783

**Comment by Ortham** [comment]
My latest push to `fix-card-sizing` avoids a lot of size hint calculations using invalid data (given by Qt) and it seems to improve the situation, but not fix it: I can no longer observe the issue when switching between Morrowind and Oblivion, but when I then switch to Skyrim it then recalculates an existing cached size hint and switching games then causes the issue to start appearing.

I don't yet know why the third game has this recalculation while the second didn't, so I've got to do more investigation.

---

My notes doing some breakpoint debugging:

On initial load of Oblivion without masterlist, hits are:

1. set content (0 messages), size 524x125
3. cache hit (0 messages), size 524x125, new size 650x125
5. set content (1 message), size 667x165

UI then displays. No further hits mousing around. Update masterlist gives a new hit:

1. set content (2 messages), size 667x199

UI then updates. No further hits mousing around. Switching to Morrowind gives no new hits. Switching back and forth between Oblivion and Morrowind several times gives no new hits and the general info card is sized correctly for both games.

Switching to Skyrim gives a new hit:

1. cache hit (1 message), size 667x165, new size 650x165

UI then updates. General info card is sized correctly. Switching to Oblivion gives no new hits and card is sized correctly. Switching to Morrowind gives a new hit:

1. cache hit (1 message), size 650x165, new size 667x199

UI then updates. General info card is sized incorrectly, and changes visible size on hover.

**Comment by Ortham** [comment]
I think this is now fixed properly in my latest push to `fix-card-sizing`, can someone confirm?

It turned out to be fairly silly: for plugin cards, each cache key (which is the data that can affect card size) has a corresponding cached widget to calculate sizes using, but for general info cards there's one widget shared across all cache keys. The widget content is only set when the cache entry is created, so if you end up using an older cache entry then you'll end up calculating size using the wrong content. The fix is to either set content for the general info card every time size needs to be calculated, or use a different widget for each general info card - I've gone for the latter as the increased memory usage is probably less important than avoiding more CPU usage during resizes.

**Comment by pStyl3** [comment]
Looks good. 👍

**Comment by Ortham** [comment]
OK, done as of 2c7fb74e13665241228492954a7f238634d52cb0.
