### ISSUE TITLE
Stuck load order???? something???? idk what to call it

### ISSUE THREAD

**Issue by PrinceJaxonHellsing** [loot/loot#1792]
As the title says I don't know what to call this bug but the issue is when I sort a load order it says that "sorting made no changes to the load order." when I exit and re open loot it still says "you have not sorted your load order" even though I tried to sort it and it gave me the "sorting made no changes to the load order" so I can't fix my load order at all and I'm unable to play fallout 4 cause it crashes since the load order hasn't been sorted

**Comment by sibir-ine** [comment]
The full message I believe you're referring to is "You have not sorted your load order this session." It's not saying that there are changes to be made that you haven't yet made by sorting (LOOT can't actually tell until you press the sort button & start the process). It's just reminding you that since opening LOOT, you haven't yet attempted to sort your load order. If you then attempt to & LOOT presents you with the "Sorting made no changes to the load order" message, it means that no changes were actually detected & so none were made, not that changes could be made but it failed to sort (there are separate messages for that).

As for your game crashing, if it really is something to do with how your load order is sorted, you'll have to narrow it down to what LOOT is sorting incorrectly & report that to the appropriate repository ([Fallout 4](https://github.com/loot/fallout4)'s in your case). This issue is not really a good place for troubleshooting your game, but your free to ask for help in the `#general-chat` channel in our [Discord](https://loot.github.io/discord/). Someone could potentially help you there.

**Comment by PrinceJaxonHellsing** [comment]
> The full message I believe you're referring to is "You have not sorted your load order this session." It's not saying that there are changes to be made that you haven't yet made by sorting (LOOT can't actually tell until you press the sort button & start the process). It's just reminding you that since opening LOOT, you haven't yet attempted to sort your load order. If you then attempt to & LOOT presents you with the "Sorting made no changes to the load order" message, it means that no changes were actually detected & so none were made, not that changes could be made but it failed to sort (there are separate messages for that).
> 
> As for your game crashing, if it really is something to do with how your load order is sorted, you'll have to narrow it down to what LOOT is sorting incorrectly & report that to the appropriate repository ([Fallout 4](https://github.com/loot/fallout4)'s in your case). This issue is not really a good place for troubleshooting your game, but your free to ask for help in the `#general-chat` channel in our [Discord](https://loot.github.io/discord/). Someone could potentially help you there.

that's not what I mean. I can make a video and send it to show you if you'd like

**Comment by sibir-ine** [comment]
Sure, if you can't do so with screenshots alone.

**Comment by PrinceJaxonHellsing** [comment]
ok well I have no clue why but this time I sorted the load order and it actually gave me an apply option this time. but I will send the video as a gif for what "was" happening.

**Comment by PrinceJaxonHellsing** [comment]
I just have to wait a bit though

**Comment by PrinceJaxonHellsing** [comment]
ugh forget it. it works now anyway. I've spent how long trying to compress it and it just cuts off? Thanks for trying to help though
