### ISSUE TITLE
Settings window is larger than the screen size

### ISSUE THREAD

**Issue by Sylennus** [loot/loot#1794]
**Bug report** : 

- Details: The settings window of LOOT (v0.18.4) is larger than my screen. When trying to resize it from the left side, it instantly shrinks out of my screen, even with the smallest mouse movement, and resizing from the right side doesn't work. Resizing using corners achieves the same results. 

- Steps to reproduce : 
  - Open LOOT
  - In the top left menu, click on "File" then in the dropdown, click on "Settings..."
  - Settings Window appears, and is larger than my screen (around 15% larger I would say)
  - 100% reproducibility rate on my side

- My configuration :
  - 1920x1080 24" Monitor
  - Windows 10 Family Edition
  - RTX 2070 Super
  - AMD Ryzen 5 3600 3.60 GHz
  - 16GB RAM
  - LOOT v0.18.4 (64bit) installed through the executable downloaded on this repository. 
  
I do not remember having this issue on previous versions but I cannot guarantee it either.

**Comment by pStyl3** [comment]
Under `File`, click on `Open LOOT Data Folder`, then close LOOT. Within the folder you just opened, go one folder back in the folder structure, so that you see the `LOOT` folder. Rename that to `_LOOT`, this will generate a new LOOT folder here, the next time you start LOOT.exe (renaming the old folder instead of deleting it keeps any `userlist.yaml` files, in case you use them).

Now start LOOT once more, and see if the issue with the settings has been fixed.

If not, then please see [this](https://github.com/loot/loot/issues/1773#issuecomment-1207132857) comment and tell us what your windows text scaling setting is.

**Comment by Sylennus** [comment]
This resolved the issue, thank you.
