### ISSUE TITLE
Identify manual group overrides in cyclic interactions

### ISSUE THREAD

**Issue by sibir-ine** [loot/loot#1796]
This would make it easier for maintainers & hopefully users as well to identify when manual group overrides are causing a cyclic interaction. Currently, there is no distinction in LOOT's cyclic interaction messages between group-enforced plugin load rules added by a masterlist & those added by the user.

**Comment by Ortham** [comment]
We don't currently track the origin of group edges as it's not directly obvious, e.g. if D loads after A because A -> B -> C ->D and B -> C is added in user metadata, when you've only got a plugin in A and a plugin in D, you need to walk the chain of groups between them to check if any user metadata was involved. It's also complicated by the fact that there may be multiple paths between two groups, so you need to check if any of them have any edges that came from user metadata. It can be done, but it'll need a bit of work in libloot and may break API/ABI compatibility there.

**Comment by Ortham** [comment]
I've done this in the differentiate-group-edge-types branches of the libloot and loot repositories: the changes break API compatibility for libloot so I'll hold them back for the future v0.19.0 release.

**Comment by sibir-ine** [comment]
Seems to work from some brief testing 👍

**Comment by sibir-ine** [comment]
Ah, sorry, it looks like what's being identified is if group rules are derived from groups defined in either the masterlist or the userlist. The issue is actually about identifying whether group rules are derived from a group _assigned to a plugin_ in the masterlist or the userlist. That would help in identifying whether a cyclic interaction due to group rules is due to an error on our end (e.g., a user has two mods that can be used together & have dependencies that we haven't given an explicit order) or user error (e.g., a user has assigned a group to a plugin with dependencies without setting an explicit order between it & other mods in the group they have installed).

**Comment by Ortham** [comment]
It's both: a group edge is identified as a user group edge if:

* it involves a group "load after" relationship that's defined in the userlist (this includes involving groups defined in the userlist)
* one of the plugins was added to its group in the userlist.

I don't think it makes sense to say "A loads after B due to masterlist group metadata" if A and B are assigned to groups in the masterlist but those groups are related due to user metadata.

**Comment by sibir-ine** [comment]
I see, then it doesn't appear to be correctly identifying the latter case. For SSE, I created four plugins, `Plugin A.esp`, `Plugin B.esp`, `Plugin AA.esp`, & `Plugin BB.esp` where `Plugin AA.esp` has `Plugin A.esp` as a master & `Plugin BB.esp` has `Plugin B.esp` as a master. I then added `Plugin A.esp` & `Plugin B.esp` to **Low Priority Overrides** & sorted, producing a cyclic interaction as expected. However, this was the cycle produced:
> [error]: Failed to sort plugins. Details: Cyclic interaction detected: Plugin A.esp --[Master]-> Plugin AA.esp --[Masterlist Group]-> Plugin B.esp --[Master]-> Plugin BB.esp --[Masterlist Group]-> Plugin A.esp

**Comment by Ortham** [comment]
Can you try again with the latest `differentiate-group-edge-types` build and share your debug log and userlist?

**Comment by sibir-ine** [comment]
Here you go: [Log & Userlist.zip](https://github.com/loot/loot/files/10063158/Log.Userlist.zip)

**Comment by Ortham** [comment]
It's not obvious what's going on, so here it is written out:

* A is a master of AA, so AA loads after A
* B is a master of BB, so BB loads after B
* A and B are in the default group
* AA and BB are in the Low Priority Overrides group
* Low Priority Overrides loads after default
* Although the groups say A should load after AA, that's ignored because AA must load after A due to the master relationship
* Although the groups say B should load after BB, that's ignored because BB must load after B due to the master relationship
* The groups say A should load after BB, and B -> BB -> A is not a cycle.
* The groups also say that B should load after AA, and A -> AA -> B is not a cycle.
* However, with both put together, B -> BB -> A -> AA -> B is a cycle.

However, while LOOT correctly identifies that Low Priority Overrides loads after default due to masterlist metadata, it fails to recognise that A and B are in the former group due to user metadata, not masterlist metadata...

**Comment by Ortham** [comment]
Figured it out, I wasn't taking into account where the current plugin's group came from, only the groups of its predecessor plugins. The latest build should work as expected.

**Comment by sibir-ine** [comment]
From some brief testing, it seems to work well now 👍

**Comment by Ortham** [comment]
Done in fd2c5d5bd8ede58363858d85d89c064c5797ee57.
