### ISSUE TITLE
Plugins are not active for some reason.

### ISSUE THREAD

**Issue by Darkabox** [loot/loot#1838]
[LOOTDebugLog.txt](https://github.com/loot/loot/files/10543165/LOOTDebugLog.txt)

**Comment by sibir-ine** [comment]
I'm assuming you're neyvermaynd from the Discord? You don't appear to have more than 255 plugins active, so that's not the issue. I'm not familiar with Vortex, but, according to its [online docs](https://wiki.nexusmods.com/index.php/User_Interface_Overview) there are separate **Mods** & **Plugins** sections that you might be confusing. LOOT only interacts with the **Plugins** section, so can you please post a screenshot of it to compare?

**Comment by sibir-ine** [comment]
Closing due to no response in over a week nor on Discord. Feel free to continue the discussion if you're still experiencing the issue.
