### ISSUE TITLE
Add support for Nehrim & Enderal SE from GOG

### ISSUE THREAD

**Issue by sibir-ine** [loot/loot#1848]
Nehrim & Enderal SE (not LE) have recently been [released](https://www.gog.com/news/release_enderal_forgotten_stories_and_nehrim_at_fates_edge_alongside_their_soundtracks_and_mad_restaurant_people_from_sureai) on GOG, & they may require a few changes. According to WB's recent support for the two (see wrye-bash/wrye-bash@d6a7df416418dc8327540f13b7d2f44840d24e14), each game uses the same main registry key Steam uses, so game detection doesn't require any changes. However, they do have separate GOG-specific registry keys that could be used as backups, `Software\GOG.com\Games\1497007810\path` for Nehrim & `Software\GOG.com\Games\1708684988\path` for Enderal. @Infernio also changed the file WB uses to detect a GOG install from `Galaxy64.dll` to `gog.ico`. I'm not sure if it's because one of them was missing the former, I haven't had the chance to check.

The main required change is that Enderal uses a different local AppData folder, `Enderal Special Edition GOG`.

**Comment by Infernio** [comment]
I changed to `gog.ico` because Nehrim does not have `Galaxy64.dll`, but all the games in question do seem to have the `gog.ico` file.

**Comment by sibir-ine** [comment]
Thanks for the clarification! Since we only need to differentiate between Steam & GOG installs for Enderal SE, we should be able to continue to use `Galaxy64.dll`.

**Comment by Ortham** [comment]
I'm going to have to rework some stuff to automatically support Enderal SE on GOG due to that different local AppData folder - the Enderal SE config in LOOT [hardcodes](https://github.com/loot/loot/blob/master/src/gui/state/loot_settings.h#L151-L161) the folder name and there's no way to say "if Galaxy64.dll is present, ignore that folder name and use this one instead".

**Comment by Ortham** [comment]
I've added support for these GOG distributions in the `gog-support` branch, with Enderal being handled using a separate settings entry, but it's not ideal as Enderal writes the same registry key for Steam and GOG installs so you could end up with a GOG install being handled with the wrong local app data folder.

As mentioned in Discord, I want to try decoupling the game settings from game detection, so that there doesn't need to be a 1:1 mapping between detectable games and settings objects. Instead, the settings objects should be for games that have been detected or manually configured as installed, and game detection should try to look for all copies of a game, not just stopping at the first install it finds. They'll need to be deduplicated (e.g. as multiple Registry keys may point to the same install), and there'll need to be some detection and labelling to differentiate multiple installs: I'm thinking "(Steam)" and "(GOG)" suffixes, numbered if there are multiple.

**Comment by Ortham** [comment]
Done as of e5833c64548c642b4a37417810208765f421e8fb - I'll investigate decoupling detection from settings separately.
