### ISSUE TITLE
LOOT version 0.21.0 has problems

### ISSUE THREAD

**Issue by SuperDat01** [loot/loot#1918]
I made a video recording the error process, I encountered a strange error, had to downgrade to the old version and then reinstall the new version successfully. 
---------------------------------------------------------------------------------------------------------------------------------------------

**Comment by Ortham** [comment]
Please describe what your problem is, and [supply a debug log](https://loot.github.io/docs/help/How-To-Report-Issues-Helpfully.html#supplying-log). The video is ambiguous because I don't know what you intend to demonstrate with it.

From the video I see LOOT v0.19.1 showed warnings that all the Fallout 4 plugins it could see were invalid. It only shows plugins that it can parse the headers of, so the start of each file looked enough like a valid plugin to satisfy LOOT's initial scan, but when it tried to fully parse them for sorting it couldn't. 

I didn't see any issues when you ran v0.21.0.

**Comment by SuperDat01** [comment]
> Vui lòng mô tả vấn đề của bạn là gì và [cung cấp nhật ký gỡ lỗi](https://loot.github.io/docs/help/How-To-Report-Issues-Helpfully.html#supplying-log). Video mơ hồ vì tôi không biết bạn định chứng minh điều gì với nó.
> 
> Từ video tôi thấy LOOT v0.19.1 hiển thị cảnh báo rằng tất cả các plugin Fallout 4 mà nó có thể thấy là không hợp lệ. Nó chỉ hiển thị các plugin mà nó có thể phân tích cú pháp các tiêu đề, vì vậy phần đầu của mỗi tệp trông đủ giống như một plugin hợp lệ để đáp ứng quá trình quét ban đầu của LOOT, nhưng khi nó cố gắng phân tích hoàn toàn chúng để sắp xếp thì không thể.
> 
> Tôi không thấy bất kỳ vấn đề nào khi bạn chạy v0.21.0.

after I installed NMM (Nexus Mod Manager) the error appeared

**Comment by SuperDat01** [comment]
http://pastie.org/p/5LBNct01GsmQoN5jNia98N

**Comment by SuperDat01** [comment]
The error has been fixed
