### ISSUE TITLE
Failing to build on Arch Linux due to ICU having EXACT keyword

### ISSUE THREAD

**Issue by C0rn3j** [loot/loot#1920]
Following commit added the `EXACT` keyword to the ICU version requirement (present both in loot and libloot) https://github.com/loot/loot/commit/efc59898d597d162869fba2b669254ef87723a7d and bumped the ICU version to 71.1

Arch Linux is already on 73.2, so trying to build (lib)loot fails due to exact versions not matching.

Pre 0.21.0, the build would just happily eat the newer ICU despite 66 being the default.

Is it necessary to have the `EXACT` keyword in there? 

As a workaround one can simply remove the EXACT keyword from CMakeLists.txt

```bash
	sed -i 's/ICU 71.1 EXACT/ICU 71.1/' "${srcdir}/${pkgname}-${pkgver}/CMakeLists.txt"
	sed -i 's/ICU 71.1 EXACT/ICU 71.1/' "${srcdir}/lib${pkgname}-${pkgver}/CMakeLists.txt"
```

**Comment by Ortham** [comment]
The EXACT keyword is there because the Flatpak runtime environment supplies ICU 71.1 and it ensures that libloot is built against the same version. Otherwise if the build environment happened to have a more recent ICU installed (e.g. supplied by the system after a build runner update) then CMake would choose that version and libloot would link against it, so LOOT would fail to start when run as a Flatpak.

If you want to build libloot yourself for a different runtime environment, feel free to remove you EXACT keyword for your own usage.

**Comment by C0rn3j** [comment]
So it's there to ensure that loot and libloot use identical ICU versions?

That makes sense.

Would it be possible to make it configurable via a variable so having to hack the CMake files with sed isn't necessary?

Something similar to this:

```cmake
    if (ALLOW_NEWER_ICU) {
        find_package(ICU 71.1 REQUIRED COMPONENTS data uc i18n)
    } else {
        find_package(ICU 71.1 EXACT REQUIRED COMPONENTS data uc i18n)
    }
```
(I am not too familiar with cmake so this is more of a pseudocode)

**Comment by Ortham** [comment]
OK, I'll just get rid of the `EXACT` keyword then.

**Comment by Ortham** [comment]
Done in https://github.com/loot/libloot/commit/f4627963ca834f66aad8a5e4379f52eed49905e1 and 9f2e8ef7f0b463242beac5c3ef5a79dd48d82757.
