### ISSUE TITLE
LOOT Icon

### ISSUE THREAD

**Issue by mcbarker69** [loot/loot#1955]
Just a minor issue... I accidentally changed the **LOOT** icon in **Vortex** and would like to have the original back, but the **_Vortex/edit/change icon_** button still shows the default Windows icon. I noticed that there's no individual **LOOT.ico** file in any of the LOOT directories, and using the icon embedded in the **LOOT.exe** file doesn't work. Thank you.

**Comment by Ortham** [comment]
Strange that Vortex won't use the embedded icon, it should work fine (I just tried adding LOOT to Steam as a "game" and that picked up the icon fine). If Vortex accepts SVG files as icons, then you can use [this one](https://github.com/loot/loot/blob/master/resources/icons/loot.svg), otherwise you'd need to use a tool to convert the SVG to an ICO file (of which there are many).

**Comment by mcbarker69** [comment]
Found a LOOT.jpg icon file online and added it to the LOOT directory and
was able to change the icon without any problems. Thanks for the help, and
for replying so quickly.
