### ISSUE TITLE
This plugin requires "FalloutNV.esm" to be active, but it is inactive.

### ISSUE THREAD

**Issue by xAphex** [loot/loot#1971]
![LOOT](https://github.com/loot/loot/assets/5391237/62774ca9-53b5-418a-934b-486fa4e145cd)

How can i fix this issue?

How can the master game files show as "inactive", this makes no sense.

Thank you.

**Comment by Ortham** [comment]
IIRC Fallout NV does not hardcode its official plugins to always load, try making sure they're in `plugins.txt`.

**Comment by pStyl3** [comment]
![grafik](https://github.com/loot/loot/assets/10406657/03ed6830-6c1f-4439-a2ba-f1a4ddf4692e)

![grafik](https://github.com/loot/loot/assets/10406657/82f51dbc-950a-4b96-9821-b0d6e43ebd57)

That's from a recent conversation we had on Discord in our `app=help` channel.

The user found that NVMP has some alternative `plugins.txt` in `FalloutNV_Epic` instead of `FalloutNV`.

**Comment by xAphex** [comment]
Fixed the problem, `FalloutNV.esm` wasn't found in `AppData\Local\FalloutNV_Epic\plugins.txt`

Thank you to everyone ❤️
