### ISSUE TITLE
Settings Window Super Wide, Can't Be Resized - Langauge Dropdown Appears Corrupted

### ISSUE THREAD

**Issue by EternityEngine** [loot/loot#2022]
Using 64-bit LOOT on Windows.

When I open the Settings window in LOOT, it's super wide (wider than my monitor!) and I cannot horizontally resize it (though it can be resized vertically). Also, half the Language options in the dropdown appear corrupted - I would assume it's due to the requisite fonts not being installed on my system, but it's doing it for Spanish and Portuguese and those both use the Latin alphabet.

Screenshot of both issues:
![settings](https://github.com/user-attachments/assets/97dff584-83aa-48f4-9dd5-46c5e568bf48)

**Comment by Ortham** [comment]
If you can't horizontally resize it, I think that means that the layout algorithm thinks that it's already at the minimum width needed to fit everything - I guess because of those mangled strings.

I suspect the strings are mangled in LOOT's settings file, try this: go to its data folder (there's an option to do so in the File menu) and open up `settings.toml` there, then remove all the `[[Language]]` sections and save the file. If you relaunch LOOT, they should then be un-mangled.

**Comment by pStyl3** [comment]
It would also be good to know, which version of LOOT @EternityEngine is using.

**Comment by EternityEngine** [comment]
Oof, knew I was forgetting something. Just updated to version 0.23.1. However, deleting the `[[languages]]` sections in `settings.toml` did in fact fix the issue! It was also corrupted there. Thank you for the help.

**Comment by pStyl3** [comment]
@EternityEngine Before updating, was the LOOT version you were using LOOT v0.18.3, or even older? Because in LOOT v0.18.4 - published around 2 years ago - we fixed the following:
> LOOT’s installer no longer double-encodes the settings file when it sets LOOT’s language, so non-ASCII text like language names is no longer mangled.

If you have been using such an old version of LOOT, this might explain why you have encountered this issue.

Reference:
[Changelog](https://loot.readthedocs.io/en/latest/app/changelog.html)

**Comment by EternityEngine** [comment]
@pStyl3 Nope! I update pretty regularly, so I'm reasonably sure it was at v23.0 before updating. That said, I hadn't gone into the settings in quite a while, so I don't actually know how long the issue was present.

**Comment by pStyl3** [comment]
Thanks for the additional information. Since your issue has been fixed and for the moment no further investigation seems to be needed, I'll close this issue.
