### ISSUE TITLE
Support Starfield's Shattered Space DLC

### ISSUE THREAD

**Issue by pStyl3** [loot/loot#2032]
Shattered Space is now available and it's files are:

![image](https://github.com/user-attachments/assets/344ae536-cf7a-4a18-87ed-52346b249554)

While Shattered Space does have it's own [Creations Page](https://creations.bethesda.net/en/starfield/details/b6b52ca2-3f1f-4316-bef8-dcb0bb2dcc32/Starfield__Shattered_Space/), it's plugin `ShatteredSpace.esm` does not get listed in `Plugins.txt`, in contrary to other Creations. It seems like it's treated as DLC and as such, in the same way as the other base game files.

Note:
[Instructions to start the quest](https://bethesda.net/en/article/7fHSb8gfxJEE9UZLBkfKWg/prepare-for-the-launch-of-shattered-space)

**Comment by Ortham** [comment]
According to [Meridiano on Discord](https://discord.com/channels/535508975626747927/1144803661034299443/1290347689296400456) the way load order works has changed again, to hardcode the official plugins to load first, and to ignore `Starfield.ccc`, so I'm going to have to redo a whole load of testing to verify that and check if anything else has changed...

**Comment by Silarn** [comment]
I'm not seeing this in the save file, anyway. Starfield is at the top but other core plugins are not. I haven't inspected the records in game however.

**Comment by Silarn** [comment]
It does appear that it's been changed back to something roughly like SSE and FO4.

I believe the standard load order is:
```
Starfield.esm
ShatteredSpace.esm
Constellation.esm
OldMars.esm
SFBGS003.esm
SFBGS004.esm
SFBGS003.esm
SFBGS003.esm
SFBGS003.esm
```

As it's still a blueprint flagged file, BlueprintShips-Starfield.esm still loads last.

Some basic testing seems to indicate that plugins written to a Starfield.ccc file will still be loaded before plugins.txt. This may well be legacy functionality but it's still worth checking this file.

**Comment by Ortham** [comment]
Testing notes:

- The game still reads `Starfield.ccc` (seen in Process Monitor)
- Swapping the order of `OldMars.esm` and `Constellation.esm` does not change the FormID of the Old Mars Cutter
- I created a new light master plugin that added a single record and put it in `Starfield.ccc` above `Constellation.esm`, removed `OldMars.esm` from `Starfield.ccc` and added it to the bottom of `Plugins.txt`. In-game, the Old Mars Cutter FormID didn't change, and the test record was found at light index 5. In `Plugins.txt`, `*test1.esm` was added as the first listed plugin, and `OldMars.esm` was removed.
- Looking at the FormIDs of records in-game, I can see that the official plugins load at the following mod indexes:
  - `ShatteredSpace.esm` -> `01`
  - `Constellation.esm` -> `FE000`
  - `OldMars.esm` -> `FE001`
  - `SFBGS003.esm` -> `FD00`
  - `SFBGS004.esm` -> `FE002`
  - `SFBGS006.esm` -> `FD01`
  - `SFBGS007.esm` -> `FE003`
  - `SFBGS008.esm` -> `FE004`

It looks like `BlueprintShips-Starfield.esm` is not hardcoded but is still implicitly active: if I have no `Starfield.ccc` and create another blueprint plugin (`testb.esm`) and add it to `Plugins.txt`, that plugin will load at index 02, but if I also add `BlueprintShips-Starfield.esm` to `Plugins.txt` before `testb.esm`, then `testb.esm` loads at index 03.

So I'll update LOOT to treat the other official plugins as hardcoded instead of implicitly active, update their order to match the indexes that I've found - I'm not sure how plugins of different types load relative to one another, but I don't think it matters for the official plugins, and the order Silarn gave above looks sensible.

I think I'll also stop LOOT writing `Starfield.ccc`, since although `BlueprintShips-Starfield.esm` still doesn't have a fixed load order, it loads after just about everything anyway, and I don't think that'll cause any issues.

**Comment by Ortham** [comment]
Done as of 70d8939ff2ebcc74e5c88a5434d56ed20b002119.
