### ISSUE TITLE
BlueprintShips-Starfield.esm loads after plugins that require it

### ISSUE THREAD

**Issue by extreme117** [loot/loot#2035]
![New Issue · loot_loot and 7 more pages - Personal - Microsoft​ Edge 10_6_2024 9_52_07 AM](https://github.com/user-attachments/assets/b5e41007-1a4a-4d05-9523-afd2aa1ef4a3)
the blueprint esm isn't loading in the correct position which causes it to load under the mods that require it in the new update 0.24.0
![LOOT 10_6_2024 9_49_00 AM](https://github.com/user-attachments/assets/599b6a1e-0de2-4806-9b97-1329f4472169)

**Comment by Ortham** [comment]
It looks like everything is working as intended to me.

The game changed how it loads `BlueprintShips-Starfield.esm` between its initial release and the update that introduced official mod support, it's now loaded after all non-blueprint-master plugins, which is what those messages are saying. LOOT previously didn't reflect that change correctly, now it does.

The sorting failure is unrelated but due to changes in Starfield vs. previous games.

**Comment by extreme117** [comment]
is there a way to make that a non-warning pop up since vortex still puts the blueprintship-starfield.esm at the top regardless of the loot load order because that is 69 warning messages for nothing?

**Comment by pStyl3** [comment]
As can be seen [here](https://github.com/Nexus-Mods/node-loot) and [here](https://github.com/Nexus-Mods/Vortex/releases), Vortex currently uses `libloot v0.23.1`. That version of `libloot` doesn't feature support for blueprint plugins yet .. support for them was added in `libloot v0.24.0`, and the current version is `libloot v0.24.3` (which `LOOT v0.24.0` uses).

This means that Vortex currently does not display the position of `BlueprintShips-Starfield.esm` correctly, as that plugin is **always** loaded after all plugins, that are not _blueprint master plugins_. In short, you could say that it loads at the end of the load order, where LOOT now also displays it.

There are are a couple of important things to understand here.

- Once Vortex updates to `libloot v0.24.3`, it should also place `BlueprintShips-Starfield.esm` at the bottom of your load order, and it should also display the new warning message you see in LOOT on many Starfield plugins.
- Non-Blueprint-master plugins, which require `BlueprintShips-Starfield.esm` as a master, will NOT get loaded after `BlueprintShips-Starfield.esm` - the game ignores this master dependency in this case.
- As such, there's almost always no point in having `BlueprintShips-Starfield.esm` as a master. On the contrary, having `BlueprintShips-Starfield.esm` as a master indicates, that the plugin in question wasn't created with the Creation Kit, or that the author of the plugin isn't aware of the implications this might have.

Having said all of this. The new warning message is rightfully getting displayed now in LOOT. The underlying issue is, that plugins that do have `BlueprintShips-Starfield.esm` as a master - shouldn't have it as a master. That is why LOOT displays a warning for them, so that the user is made aware of this. The new warning message should therefore continue to be displayed, if the aforementioned criteria has been met.

**Comment by extreme117** [comment]
oh, gotcha thanks
