### ISSUE TITLE
Autocompletion for filenames in metadata editor

### ISSUE THREAD

**Issue by Freso** [loot/loot#253]
It would be neat if the metadata editor would be able to autocomplete filenames from the available plugins. E.g., in this screenshot, there would be some way to select "EVE.esm" instead of having to type it all out (and thus possibly mistype etc.):
![Screenshot](https://i.imgur.com/Zmqg4Ba.png)

I'm intentionally not setting the 0.7.0 milestone on this, since this shouldn't hold back a 0.7.0 release, but can easily wait for future iterations, as I have no idea how complicated it would be within the current framework. (IIRC, it's fairly simple to do in jQuery... but jQuery is like a whole separate language to JavaScript. :p)

**Comment by WrinklyNinja** [comment]
This is mostly done (using a paper-autocomplete custom element instead of <datalist>, which still hasn't landed). However, the new input API is different and that's broken loading and saving data, and drag 'n' drop.

On the UI side, I've noticed that there's no way to dismiss the suggestion dropdown, which can result in it obscuring lower inputs, and pStyl3 has also mentioned that it would be nice to be able to keyboard-navigate the list.

**Comment by WrinklyNinja** [comment]
Done in 5c5670d52f9de103bc576ef9c7210e28fa0245db
