### ISSUE TITLE
Add proxy support

### ISSUE THREAD

**Issue by l00ter** [loot/loot#423]
Without HTTP proxy support, I can't connect to your "repository" from LOOT app.

or provide "Offline mode".

**Comment by WrinklyNinja** [comment]
Offline mode would be just you not getting masterlist updates, so you can replicate that by unchecking the option to look for updates before sorting.

It seems that libgit2 does have proxy support, but not support for authenticated proxies that require a username and password (though that is an active area of work). Try adding the following to your `%LOCALAPPDATA%\LOOT\Skyrim\.git\config` file:

```
[http]
    proxy = http://proxy.com:8080
```

Replacing the proxy URL and port with the correct details for your proxy. You'll need to do the same for each game's `.git\config` file that you want to use LOOT with.

**Comment by l00ter** [comment]
No, above solution doesn't work.

cmd
mkdir %LOCALAPPDATA%\LOOT\Skyrim\.git\
notepad %LOCALAPPDATA%\LOOT\Skyrim\.git\config
(copy&paste, edit, save)

C:\Users\*\AppData\Local\LOOT\Skyrim\.git\config <- good!

Run LOOT.
Loot doesn't use proxy.
Loot moved /skyrim to /skyrim.temp, ignoring config file.
/skyrim/.git folder was moved to /skyrim.temp/.git.

**Comment by l00ter** [comment]
BTW I'm using 0.6.1 Archive edition.

**Comment by WrinklyNinja** [comment]
Hmm, could you try it out on the latest [snapshot build](https://www.dropbox.com/sh/scuvwwc6ovzagmd/AAD1TodBAwGQTuV1-4Z2d0sCa?dl=0)? Support may only have been added more recently than v0.6.1's release.

**Comment by l00ter** [comment]
The Box link you provide was censored by my ISP, so I tried "LOOT.v0.7.0-beta.4-0-g5aca14b.7z" from github instead.

No success. Loot simply ignore proxy config file.
Is there a way to do it manually? Grab loot/skyrim/masterfile.yaml file and save to XXXXX folder?

IMO, this v7's sort result is terrible. I'll stick with v6(current latest/stable).

**Comment by WrinklyNinja** [comment]
> Is there a way to do it manually? Grab loot/skyrim/masterfile.yaml file and save to XXXXX folder?

Yes, you can get the file [here](https://raw.githubusercontent.com/loot/skyrim/master/masterlist.yaml), and put it in your `%LOCALAPPDATA%\LOOT\Skyrim\` folder.

I just noticed that you have `mkdir %LOCALAPPDATA%\LOOT\Skyrim.git\` above: it's supposed to be `mkdir %LOCALAPPDATA%\LOOT\Skyrim\.git\`. Was that just a typo, or were you creating the wrong folder? Also, I had assumed that you had a `.git` folder in `%LOCALAPPDATA%\LOOT\Skyrim\` already, otherwise the instructions won't work. Was that the case?

> IMO, this v7's sort result is terrible. I'll stick with v6(current latest/stable).

The only difference is that v0.7 puts non-interacting and equally-conflicting plugins in alphabetical order, which is unlikely to produce any meaningful changes. In any case, I'm currently trialling a change that has v0.7 making no changes compared to v0.6.

**Comment by l00ter** [comment]
Absolutely not.
Skyrim/.git of course.
Github automatically edit my post, that's why.

> Yes, you can get the file here
Thanks, it worked!
(I DLed this; https://github.com/loot/skyrim/archive/master.zip )

**Comment by WrinklyNinja** [comment]
I finally got around to looking into this by setting up a local proxy on my machine and stopping outbound traffic with my firewall. It turns out that unauthenticated proxies are supported so long as the proxy is given in one of the following:

1. Local Git config (unlikely given you're trying to get a Git repository in the first place)
2. Global Git config (unlikely as you're probably not a Git users, so you probably don't have such a config)
3. The `https_proxy` environmental variable.

If your proxy configuration doesn't already set the `https_proxy` environmental variable, you can set it in Windows by:

1. Opening the System item in the Control Panel
2. Open the System Properties dialog by clicking the "Advanced system settings" item in the sidebar
3. Open the Environmental Variables dialog by clicking the "Environmental Variables..." button in the "Advanced" tab.
4. In the User variables section, click the "New..." button.
5. Put `https_proxy` as the variable name, and the proxy URL as the variable value in the New User Variable dialog.
6. Click "OK", then "OK" in the Environmental Variables dialog.
7. Relaunch LOOT.

Authenticated proxies are not supported: the relevant upstream bug report is libgit2/libgit2#2106.

As unauthenticated proxies are already supported and there's nothing I can do for authenticated proxies, I'll add this information to the FAQs page and close this issue.
