### ISSUE TITLE
v0.7.1 won't load in ModOrganizer.

### ISSUE THREAD

**Issue by ROODAY** [loot/loot#463]
I was using 0.6.1 without any issues before I noticed the upgrade message, which I then followed and installed 0.7.1. I'm able to run LOOT.exe on its own without a problem, but running it in ModOrganizer opens a blank LOOT window, and nothing from the LOOT interface loads. Here's a screenshot of it looks like for me. 
![Broken LOOT in MO](http://i.imgur.com/mCjQjCB.png)
Is this a known issue?

**Comment by pStyl3** [comment]
Try to add the "--single-process" argument (without quotes) to LOOT within MO's "Modify Executable" window. This should bypass the problem!

Aside from the mentioned "fix" above, does this happen every single time you start MO? Or did you 'start MO via downloading a mod from Nexus priorly', so that MO wasn't running when you clicked on 'Download with Manager' .. and thus, got started that way?

Also, where do you have Steam/MO/LOOT installed to? Please provide file paths.

**Comment by ROODAY** [comment]
Thanks, the `--single-process` argument fixed it!

The problem occurred no matter how MO was started, whether normally, through my steam shortcut, or  from starting a mod download.

Here are my file paths
Steam: `C:\Program Files (x86)\Steam`
Skyrim: `R:\SteamLibrary\SteamApps\common\Skyrim`
MO: `R:\Fun Stuff\Mods\Mod Organizer`
LOOT: `R:\LOOT`

**Comment by WrinklyNinja** [comment]
Closing this since a workaround has been found.

**Comment by justicelordneshsuperman** [comment]
ok i have problem with LOOT i can post you %LOCALAPPDATA%\LOOT and screen shot with problem so loot 091 worked fine and just stoped with white screen with loot name in tab after deleting %LOCALAPPDATA%\LOOT and starting again loot create files again in %LOCALAPPDATA%\LOOT and same white screen, so i tried (LOOT v0.8.1-146-gb199982 (32 bit) and also same problem do you want me to upload to you %LOCALAPPDATA%\LOOT ok im uploading here it is [0703/050331:ERROR:child_process_launcher.cc(505)] Failed to launch child process

CEFDebugLog.txt

**Comment by WrinklyNinja** [comment]
@justicelordneshsuperman Spamming multiple issues and unrelated pull request conversations is incredibly rude. Do so again and you'll find yourself reported to the site moderators and earning yourself a place on my ignore list.
