### ISSUE TITLE
Allow the user to cancel long operations

### ISSUE THREAD

**Issue by Ortham** [loot/loot#468]
Suggested by pStyl3, and I certainly wished I had one when testing masterlist parsing failures yesterday. To support this:
- [x] Create a framework for cancelling JS<->C++ queries, using `cefQueryCancel()`
- Ensure each cancellable operation is transactional, probably the easiest way to do this is by not modifying the LOOT state object until the end of the operation.
- Add cancellation points at logical points in each cancellable operation.

The following operations would be affected:
- [ ] Changing game
- [ ] Masterlist update
- [ ] Plugin sorting
- [ ] Content refresh
- [ ] Conflicting plugins filtering

These processes would have to be adapted to ensure that early exit doesn't result in partial changes being made, unless such changes wouldn't have an adverse effect (for example, only fully-loading some plugins would be OK).

**Comment by WrinklyNinja** [comment]
I've finally started working on this. 

Unfortunately, cancelling a query is a little messy because although notifying the C++ side is easy enough, a callback can't be called for a cancelled query, so the query's promise never settles. To make matters worse, ES2015 promises can't have their state changed externally, so the JS query cancel function can't just reject the query's promise. 

To get around this, I check a `cancelled` boolean once a second while the promise is pending, and reject the promise with nothing passed if the boolean is true. The boolean is initialised to false and set to true by the query cancel function.

Of course, this means updating all rejection handlers to do nothing when a promise is rejected with an undefined argument.

**Comment by Ortham** [comment]
Closing this as performance improvements over the years have reduced the benefit this would bring to the point that it's not worth the effort, and the little work that I did towards it is so old it's no longer relevant to the current codebase.
