### ISSUE TITLE
LOOT v0.8 doesn't support manual update.

### ISSUE THREAD

**Issue by espress0** [loot/loot#490]
v0.8.1

Masterlist Revision	Unknown: Git repository missing
Masterlist Date	Unknown: Git repository missing

Warnings	0
Errors	0
Total Messages	4 
Active Plugins	41
Dirty Plugins	0
Total Plugins	41

1. I've placed "masterlist.yaml" file to C:/Users/FGithub/AppData/Local/LOOT/Skyrim/
2. I run v0.6 LOOT. LOOT loads it and sort my plugins.
3. I updated to v0.8.1.
4. Now, this LOOT doesn't sort my plugins anymore, as shown above.
In 0.6, LOOT shows "Dirty plugins 2" but now it's gone.

Please support http proxy, or provide manual update for this.
I'm considering downgrade to 0.6.

**Comment by espress0** [comment]
related https://github.com/loot/loot/issues/423

**Comment by WrinklyNinja** [comment]
How does "the above" show that v0.8.1 doesn't sort your plugins? v0.6 and v0.8.1 use different masterlist versions, it could be that the dirty info has been removed or fixed so that it doesn't show for you.

LOOT loads my masterlist.yaml and sorts correctly when only it is in LOOT's Skyrim folder.

**Comment by espress0** [comment]
> v0.8.1 doesn't sort your plugins

1. If LOOT loads "masterlist.yaml" correctly, why Revision and Date fields are "Unknown"?

> Masterlist Revision Unknown: Git repository missing
> Masterlist Date Unknown: Git repository missing

2. I've changed a load order from Skyrim launcher, and save it.
ABCDEF -> ABC'F'DE
But when I start LOOT, it shows "ABCDE'F'". Why LOOT ignore current load order?
And I run "filter", the result is "ABCDEF".
I'm not sure LOOT is really sorting my plugins...

> ...when only it is in LOOT's Skyrim folder.

" C:/Users/FGithub/AppData/Local/LOOT/Skyrim/ ", right?

**Comment by WrinklyNinja** [comment]
> If LOOT loads "masterlist.yaml" correctly, why Revision and Date fields are "Unknown"?

Because that information isn't stored in the masterlist, it's in the masterlist's Git repository that the updater downloads and keeps in sync.

> I've changed load order from "Skyrim launcher", and save it. ABCDEF -> ABC'F'DE But when I start LOOT, it shows "ABCDE'F'". Why LOOT ignore current load order? And I run "filter", the result is "ABCDEF". I'm not sure LOOT is really sorting my plugins...

Skyrim's launcher only shows/sets the load order of your active plugins, whereas LOOT operates on a load order for all installed plugins, and syncs it with the active plugin load order whenever it sets a new load order.

> I'm not sure LOOT is really sorting my plugins...

Well, if you're just opening LOOT and looking at the plugins, then no, it hasn't sorted them. You need to click the sort button (then the apply button once it's calculated an order) for it to actually sort them.

> " C:/Users/FGithub/AppData/Local/LOOT/Skyrim/ ", right?

Yes
