### ISSUE TITLE
Fix to restore Windows XP compatibility for loot32.dll

### ISSUE THREAD

**Issue by megamurmulis** [loot/loot#500]
To restore Windows XP compatibility for loot32.dll:
```
FILE:      loot\src\backend\helpers\helpers.cpp
LINE:      123
FUNCTION:  RegKeyStringValue
```
<b>Replace this Vista+ API call (`advapi32.RegGetValueW`):</b>
```
LONG ret = RegGetValue(hKey,
                       ToWinWide(subkey).c_str(),
                       ToWinWide(value).c_str(),
                       RRF_RT_REG_SZ | KEY_WOW64_32KEY,
                       NULL,
                       &wstr[0],
                       &len);
```
<b>With Windows 2000+ compatible API calls (RegOpenKeyExW, RegQueryValueEx):</b>
```
LONG ret = RegOpenKeyExW(hKey,
                         ToWinWide(subkey).c_str(),
                         NULL,
                         KEY_QUERY_VALUE,
                         &hKey);
if (ret == ERROR_SUCCESS) {
    DWORD lpType = 0;
    ret = RegQueryValueEx(hKey,
                          ToWinWide(value).c_str(),
                          0,
                          &lpType,
                          (LPBYTE)&wstr[0],
                          &len);
    if ((lpType != REG_SZ) && (lpType != REG_EXPAND_SZ)) {
        ret = ERROR_FILE_NOT_FOUND;
    }
}
```

<b>Building:</b> (make sure to use `v1*0_xp` toolset, for example Visual Studio 2013)
```
>  mkdir build && cd build
>  cmake.exe .. -G "Visual Studio 12" -T "v120_xp"
Open solution in VS, set Build type to Release, then build project "loot32"..
```
<br>
<br>
<hr>
<b>Note:</b> getting `libgit2` to properly work on Windows XP is another (separate) matter.
Recent v0.23+ versions added some fixes for Windows Vista, which broke lots of functionality in Windows XP, so either:
<b>a)</b> Use older version / apply libgit2 patches to resolve those:
```
>  patch -u -p 1 -i  patches_libgit_1_GetFinalPathNameByHandle.diff
>  patch -u -p 1 -i  patches_libgit_2_new_fixes.diff
>  mkdir build && cd build
>  cmake.exe .. -G "Visual Studio 12" -T "v120_xp" -DMSVC_SHARED_RT=OFF
Open solution in VS, set Build type to Release, then build project.
Finallly run `libgit2_clar.exe` to verify that it works on Win 7+ and Win XP.
```

<b>b)</b> Or if you don't need automatic masterlist update feature - compile without libgit2:
1. remove git.lib from Include Libraries
2. replace `loot\src\backend\masterlist.cpp` with stubs.
<hr>

**Comment by WrinklyNinja** [comment]
I'm not interested in crippling the masterlist update to provide compatibility to an end of life OS.

**Comment by megamurmulis** [comment]
How does fixing Loot API call cripple master list update?
Those are 2 separate things.

My note about libgit2 = only for people who might not realize that <b>libgit2 v0.21+ does not work on Windows XP</b>, unless compatibility patches are applied before building it..

And (b) option is just edge case, since masterlist update really does not need full blown git support..

**Comment by WrinklyNinja** [comment]
> And (b) option is just edge case, since masterlist update really does not need full blown git support..

Yes it does.

There are a couple of non-trivial technical issues that XP support brings:

* To support XP, all of LOOT's many dependencies also need to be built with the XP toolset. This is something that's easy to lose track of and forget when I update a dependency, meaning many points of failure and so more care required to double-check everything. On top of that, I don't build my own CEF binaries (I don't think I can), and I'm not sure what their XP support status is: I know that Chromium is going to drop XP support possibly as soon as the end of this year.
* Libgit2 does not support XP, which means relying on third-party patches which may be of dubious quality (ie. they might break stuff to force XP support) and which would need to be maintained as Libgit2 develops. 

On top of that:

* I can't test XP support.
* The Steam Hardware Survey for October put XP users at 2.24%, a drop of 0.32% from the previous month. I can't find historical data, but if that rate persists (it'll probably tail off when only the die-hards are left), that means effectively no XP users on Steam by June next year. Sure, you don't need Steam to play Oblivion, but I'd bet that there's a pretty strong correlation between Steam users and Oblivion players. There may always be *some* people that stick with XP, but even now it's just not worth the effort to cater to the 2% that use it.
* Microsoft don't support XP, why should I? It's an ancient, superseded, insecure OS that I don't want people using if they can at all help it, and by providing XP support I'd be complicit in letting them stick with it. Sure, nobody is likely to update just because LOOT doesn't support it, but it can be a contributing factor as more software drops support.

**Comment by megamurmulis** [comment]
Ok, so the title was bit pretentious + i really should not have put that note about libgit2,
as now whole discussion turned out about it / supporting / providing binaries working on XP - not what i asked..
So - please ignore that part about libgit2 (people who need it, will compile it manually; while for the rest of the world this does not matter)

What this really was about:
- changing `RegGetValue` call to [`RegOpenKeyEx`, `RegQueryValueEx`]..

**Comment by WrinklyNinja** [comment]
That's a more reasonable request, though I also recently swapped `SHGetFolderPath` for `SHGetKnownFolderPath`, so that would need to be reverted too. That's a pretty trivial change to make, but `RegGetValue` has niceties like ensuring strings are null-terminated, not to mention being one function call rather than two, so I'm reluctant to revert that improvement.

**Comment by Freso** [comment]
Off-topic: 500 issues! :tada:
