### ISSUE TITLE
Fallout 4 - Cannot save to plugins.txt when read-only flag is set

### ISSUE THREAD

**Issue by micdah** [loot/loot#517]
I am trying out v0.8.1-53 (snapshot) which unfortunately cannot save when the ````plugins.txt```` file has the read-only flag set, giving the following exception:
````
Error

Error code: 1; libloadorder failed to set the load order. Details: "C:\Users\micdah\AppData\Local\Fallout4\plugins.txt" could not be written. Details: ios_base::badbit set: iostream stream error
````

Because Fallout 4 launcher has the unfortunate "_feature_" of resetting ````plugins.txt```` if it is not flagged as read-only, it is pretty much a must-have for Fallout 4.

It seems Nexus Mod Manager has also incorporated this into their program, as it sets the read-only flag whenever it changes ````plugins.txt```` (_probably by either ignoring the flag on the write call, or by removing/setting the flag_).

It would be a great fix if LOOT could also handle Fallout 4's odd ````plugins.txt```` resetting "_feature_"

**Comment by WrinklyNinja** [comment]
I expect that when official mod support is released, Fallout 4's launcher
will stop setting the read-only flag. All signs suggest that it is a
measure intended to dissuade people from using mods created before official
mod support is released, since they can be dangerous.

As I don't intend to release Fallout 4 support for LOOT before official
support has landed and I've had a chance to verify that support has not
changed anything, I don't see the need to hack around the launcher's
behaviour.
