### ISSUE TITLE
Installer selects a drive that doesn't exist without option to change the target

### ISSUE THREAD

**Issue by Matakor** [loot/loot#591]
![Ran in admin mode](http://i.imgur.com/X4dv0G1.png)

Unsure what's going on with it. Can't install at all, admin active or not. I don't get any scree that lets me 'choose' a location to install even.

Any fix?

**Comment by Matakor** [comment]
Manual install with the .zip does work, however.

**Comment by WrinklyNinja** [comment]
LOOT skips the install location screen:

![screenshot 46](https://cloud.githubusercontent.com/assets/2430738/16348178/eaa728c6-3a48-11e6-8935-d8df5c8b376b.png)

if you've previously installed LOOT, because it re-uses the existing install location, silently uninstalling the existing version of LOOT (but keeping your user files). In this case, the first screen after selecting the installer language would be:

![screenshot 47](https://cloud.githubusercontent.com/assets/2430738/16348190/fdb920f4-3a48-11e6-98e5-4bbc6345d955.png)

and the next screen does the actual install. I guess you're getting the error because the location of the previous install no longer exists? Are you able to uninstall LOOT through the Control Panel? If so, try doing that then running the installer again.
