### ISSUE TITLE
loot_get_plugin_tags should accept a set of mods

### ISSUE THREAD

**Issue by Utumno** [loot/loot#597]
As it is we pass it one mod at a time. Not sure if you reread and/or reparse the masterlist each time (I would appreciate some insight on the caching policies) - but anyway all these calls cost performance - on each and every tab out/in or internal refresh operation. It would be neater (and faster) to be able to supply a list of mods and get the tags back in one big go - calling the dll exactly once.

**Comment by WrinklyNinja** [comment]
> Not sure if you reread and/or reparse the masterlist each time (I would appreciate some insight on the caching policies)

The masterlist gets parsed in `loot_load_lists()`, and conditions are evaluated in `loot_eval_lists()`. Evaluation can discard some masterlist data, but otherwise it's cached until the next `loot_load_lists()` call (or until the handle is destroyed).

There's no additional performance hit to calling `loot_get_plugin_tags()` multiple times vs. calling a function that would take multiple plugins at once (such a function would just call `loot_get_plugin_tags()`, there's no real optimisation to be made).

**Comment by Utumno** [comment]
Ok thanks - so you mean that `loot_load_lists` and `loot_eval_lists` are not called in between the calls to `loot_get_plugin_tags` - it would make sense however to have one call to the dlll as context switches are costly. Loading the Bash tags is one of the most costly operations on booting:

```
   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
        1    0.000    0.000    9.028    9.028 __init__.py:4178(_Init)
      3/2    0.000    0.000    4.488    2.244 balt.py:1560(_conversation_wrapper)
        1    0.000    0.000    4.399    4.399 __init__.py:3926(RefreshData)
        1    0.000    0.000    3.438    3.438 __init__.py:4229(InitData)
        1    0.000    0.000    3.428    3.428 __init__.py:4002(warn_corrupted)
        1    0.000    0.000    3.427    3.427 balt.py:986(Display)
        1    0.000    0.000    3.421    3.421 _windows.py:709(ShowModal)
        1    3.137    3.137    3.421    3.421 {wx._windows_.Dialog_ShowModal}
        1    0.000    0.000    2.763    2.763 __init__.py:3374(refresh)
        1    0.001    0.001    1.904    1.904 __init__.py:3536(reloadBashTags)
      286    0.002    0.000    1.902    0.007 __init__.py:2675(reloadBashTags)
      572    0.002    0.000    1.895    0.003 mods_metadata.py:290(_getTagCache)
      286    0.000    0.000    1.894    0.007 mods_metadata.py:282(getBashTags)
      286    1.890    0.007    1.892    0.007 loot.py:362(GetModBashTags)
        5    0.005    0.001    1.310    0.262 __init__.py:3022(refresh)
        1    0.000    0.000    1.024    1.024 __init__.py:3812(__init__)
        1    0.000    0.000    0.997    0.997 __init__.py:3478(__init__)
        8    0.001    0.000    0.902    0.113 balt.py:1602(__init__)
        8    0.002    0.000    0.806    0.101 balt.py:1756(PopulateItems)
      458    0.001    0.000    0.772    0.002 __init__.py:2326(getHeaderError)
        1    0.000    0.000    0.556    0.556 mods_metadata.py:246(refreshBashTags)
        1    0.000    0.000    0.556    0.556 loot.py:340(Load)
      383    0.016    0.000    0.553    0.001 balt.py:1695(PopulateItem)
        1    0.000    0.000    0.550    0.550 __init__.py:1499(__init__)
       96    0.015    0.000    0.480    0.005 __init__.py:2778(getStatus)
     8179    0.480    0.000    0.480    0.000 {nt.stat}
      288    0.004    0.000    0.452    0.002 __init__.py:2693(readHeader)
        1    0.382    0.382    0.382    0.382 loot.py:345(PlainLoad)
...
```

If I take out the wx stuff it is actually _the_ most costly operation on boot (with other loot calls it accounts for half the booting time).

One call per mod to the dll results in overhead I believe - but more accurate profiling is needed. Anyway, bottom line the less and more optimized calls the better (as always)

**Comment by WrinklyNinja** [comment]
I'll try some profiling for calling from C++, to see if the Python <-> C overhead is significant.

**Comment by WrinklyNinja** [comment]
Which game are those timings you posted for, so that I can test against the same masterlist?

**Comment by Utumno** [comment]
This is oblivion with 286 mods - now that I turned the eye on this I will refactor a bit though, I just kept seeing it in my dreams tonight hahaha. Here is the profiling commit:

https://github.com/wrye-bash/wrye-bash/commit/e0e79bd6bb7283a25dd201701ac510d891f48def

286 mods

**Comment by WrinklyNinja** [comment]
I ran the following Google Test parameterised case 5 times (one for each supported game, though the timed code has no game-specific logic) against the latest LOOT `dev` branch code (35e6ca62104f499680de6ec990b815d08fc76b9e) on a pretty high-spec system (Intel Core i7 6700K). 

The masterlist used is the latest Oblivion masterlist (e9fecf6), and I chose to test getting tags for `Unofficial Oblivion Patch.esp` because it's got 21 tags in the masterlist and so would cause more processing than a plugin with no or few tags.

```
TEST_P(loot_get_plugin_tags_test, performanceTest) {
  ASSERT_EQ(loot_ok, loot_load_lists(db_, "C:\\Users\\Oliver\\Documents\\GitHub\\LOOT\\oblivion\\masterlist.yaml", NULL));
  ASSERT_EQ(loot_ok, loot_get_tag_map(db_, &tagMap_, &numTags_));

  auto start = std::chrono::system_clock::now();

  for (size_t i = 0; i < 200000; ++i) {
    EXPECT_EQ(loot_ok, loot_get_plugin_tags(db_, "Unofficial Oblivion Patch.esp", &added_, &numAdded_, &removed_, &numRemoved_, &modified_));
  }

  auto end = std::chrono::system_clock::now();

  std::cout << std::chrono::duration_cast<std::chrono::microseconds>(end - start).count() << '\n';
}
```

Results:

```
26865388
26628872
26555440
26969793
26568154
```

Average: 26717529 us => 134 us per call to `loot_get_plugin_tags()`, or 38 ms for 286 calls

For completeness' sake, I then changed the test to get tags for a plugin with no tags, and ran the test again:

```
21588638
21763348
22008627
21723222
21804266
```

Average: 21777620 us (22 seconds) => 109 us per call to `loot_get_plugin_tags()`, or 31 ms for 286 calls

So I'm seeing performance 50x faster than what you see calling from Python. Some of this may due to system specs (what processor are you running on?), and some will be the Python -> C layer, but it's still a massive difference.

I'll try running the tests on my laptop (which has an Intel i5 4200U, and I can put it in energy saver mode to really dial things down) later to see what timings it gets.

**Comment by WrinklyNinja** [comment]
OK, results from my laptop:

```
141326823
146171284
145053341
114464521
127285155
```

Average: 134860225 us => 674 us per call to `loot_get_plugin_tags()`, or 193 ms for 286 calls. A lot slower than my desktop, but still almost 10x faster than what is seen in Bash. 

I should also note that at the level of throttling I was running the tests on (power saving was restricting my CPU to ~770 MHz) Skyrim (and probably Oblivion) is unplayable and everyday desktop tasks are laggy, so I suspect that real Bash users would be running with more processing power.

**Comment by WrinklyNinja** [comment]
Given that the issue seems to be an overhead issue, it might be worth investigating an alternative to `ctypes` with less overhead: it would be easier to add a function that you can call once, but that's avoiding the problem when I'd rather solve it if possible.

I did a bit of googling, and SWIG and Boost.Python were recommended most often, though I also found [pybind11](https://github.com/pybind/pybind11) which seems to be worth a look. I'll give them a go if I can make the time.

**Comment by Utumno** [comment]
Thanks for looking at this! I will have to do more accurate profiling from my part and keep you posted. But maybe it makes a difference I am getting the tags for 286 _different_ mods ?

**Comment by WrinklyNinja** [comment]
> But maybe it makes a difference I am getting the tags for 286 different mods ?

I doubt it. Certainly the API doesn't cache previous calls (beyond the memory allocated for outputs), and everything lives in memory, so there's no disk cache.

**Comment by WrinklyNinja** [comment]
I got a chance to play around with pybind11 and managed to wrap the LOOT API's `loot_is_compatible()` function:

```
#include <loot/api.h>
#include <pybind11/pybind11.h>

namespace py = pybind11;

PYBIND11_PLUGIN(loot_api_python) {
  py::module m("loot_api_python", "LOOT API pybind11 wrapper");

  m.def("loot_is_compatible", &loot_is_compatible, "Checks for API compatibility.");

  return m.ptr();
}
```

![screenshot 3](https://cloud.githubusercontent.com/assets/2430738/17464522/dfb2d00c-5cd8-11e6-819d-b58011d1302f.png)

That was with manually dragging the API's `.lib` and `.dll` files to the right place, and I've got to modify the API archiver to include the .lib file (otherwise the wrapper needs to build the API itself, which is overkill).

Early impressions are good though. I'll create a repository for the wrapper and hopefully get something that can be performance-tested for comparison relatively quickly.

**Comment by WrinklyNinja** [comment]
OK, repository created: [loot-api-python](https://github.com/loot/loot-api-python).

**Comment by WrinklyNinja** [comment]
Well, I hit a pretty big snag - Python doesn't support output parameters (ie. pass a pointer so the function can modify the value it points to), which is a very C way of doing things, and so most wrapped API functions won't output anything.

I could break the LOOT API to return objects that include return codes alongside all the fields that are currently output parameters, but given that I'm experimenting with a C++11 -> Python binding library, I might as well rip out all the API's C++ -> C bits and simplify the whole lot. I can then maintain the C API as "just another wrapper".

Making the API a C++ API would involve:

- [ ] Exposing the `loot_db` class.
- [ ] Making all the functions that accept a `loot_db *` into member functions of `loot_db`. There is probably overlap with the GUI's needs here, so I could see how much state management can be in common code.
- [ ] Exceptions instead of return codes.
- [ ] Create POD structs for return types where necessary, so there are no non-const pointers or references.
- [ ] Namespace instead of using `loot_` prefixes.
- [ ] Use error, game type, message type and language enum types directly.
- [ ] Probably a lot more.

**Comment by Utumno** [comment]
Thanks for looking at this.

Ctypes is part of the python std. Unless the performance difference is enormous I would not add yet a new dependency in Bash.

I can't look into this now but I am interested - my suggestion would be to test existing ctypes wrapper on your own and figure out if there is a way to speed this up. It does really seem strange that ctypes (a library that's been around since so long) should introduce such a performance lag - I feel something else is going on.

-----

Meanwhile I need to update loot for Bash - which snapshot should I use ?

**Comment by Freso** [comment]
> Meanwhile I need to update loot for Bash - which snapshot should I use ?

Is there a reason not to use the [latest release](https://github.com/loot/loot/releases)?

**Comment by WrinklyNinja** [comment]
> Ctypes is part of the python std. Unless the performance difference is enormous I would not add yet a new dependency in Bash.

There's no new dependency to the pybind11-generated wrapper - instead of having a loot.py file in your source tree, pybind11 generates a loot-api.pyd file.

> It does really seem strange that ctypes (a library that's been around since so long) should introduce such a performance lag - I feel something else is going on.

The overhead is well-known, that's why I'm investigating an alternative that promises less-to-no overhead.



> Meanwhile I need to update loot for Bash - which snapshot should I use ?

Use the [0.9.2 release](https://github.com/loot/loot/releases/download/0.9.2/loot-api_0.9.2-0-g6b58f92_dev.7z).

**Comment by Utumno** [comment]
Thanks - I take it that the bugs I reported are fixed in 9.2, but I would use a newer snapshot if some important issue is fixed there. Meanwhile I get this with 9.2:

```
Traceback (most recent call last):
  File "Wrye Bash Launcher.pyw", line 88, in <module>
    bash.main()
  File "bash\bash.py", line 362, in main
    bosh.initBosh(opts.personalPath, opts.localAppDataPath, bashIni)
  File "bash\bosh\__init__.py", line 7696, in initBosh
    initDirs(bashIni, personal, localAppData)
  File "bash\bosh\__init__.py", line 7496, in initDirs
    configHelpers = ConfigHelpers()
  File "bash\bosh\mods_metadata.py", line 215, in __init__
    loot.Init(bass.dirs['compiled'].s)
  File "bash\loot.py", line 187, in Init
    LOOT_LANG_ANY = _uint('loot_lang_any')
  File "bash\loot.py", line 109, in _uint
    def _uint(const): return c_uint.in_dll(LootApi, const).value
ValueError: symbol 'loot_lang_any' not found
```

LOOT_LANG_ANY is used in EvalConditionals which is used in Load: https://github.com/wrye-bash/wrye-bash/blob/fc996774f52f443b143b8ef2fe67be6d105ead05/Mopy/bash/loot.py#L343

> The overhead is well-known, that's why I'm investigating an alternative that promises less-to-no overhead.

Can you point me to info on this overhead ? If the overhead is per call then this issue (calling the api once) would help.

-------

**Comment by WrinklyNinja** [comment]
> LOOT_LANG_ANY is used in EvalConditionals which is used in Load: https://github.com/wrye-bash/wrye-bash/blob/fc996774f52f443b143b8ef2fe67be6d105ead05/Mopy/bash/loot.py#L343

`loot_lang_any` was removed in 0.9.0: use `loot_lang_english` instead, it's functionally equivalent.

> Can you point me to info on this overhead ? If the overhead is per call then this issue (calling the api once) would help.

Well, there's the profiling we did, plus stack overflow posts like those [here](https://stackoverflow.com/questions/8067171/ctypes-vs-c-extension) and [here](https://stackoverflow.com/questions/1942298/wrapping-a-c-library-in-python-c-cython-or-ctypes).

I'd like to do my own profiling of Wrye Bash for direct comparison against my earlier results and in the future against the pybind11-generated module, if I download the source archive for [this commit](https://github.com/wrye-bash/wrye-bash/commit/e0e79bd6bb7283a25dd201701ac510d891f48def) do I just need the usual Python dependencies (wx, pywin32, comtypes)?

**Comment by WrinklyNinja** [comment]
Right, I spiked a very rough C++ API that works when I wrap it for Python, and I wrote and ran an analogous profiling test to my earlier C++ test. 

The results are impressive: the average is 123 us per call to loot_get_plugin_tags(), or 35 ms for 286 calls. That's **faster** than calling the C API in C++! Though there's such a small margin that it may be down to background CPU load differences, and realistically performance is equivalent.

@Utumno: I guess this result means you'd like to see this new C++ API and its Python wrapper module fleshed out? If so, I'd value your input on the wrapper's API, so you get something that's useful and pleasant to use (since I'm not a Python dev, I might miss some things).

Here's the profile outputs for the 5 runs I performed:

```
         200005 function calls in 25.122 seconds

   Ordered by: cumulative time

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
        1    0.006    0.006   25.122   25.122 <string>:1(<module>)
        1    0.282    0.282   25.116   25.116 test.py:67(test_get_plugin_tags_performance)
   200000   24.515    0.000   24.515    0.000 {built-in method get_plugin_tags}
        1    0.319    0.319    0.319    0.319 {built-in method load_lists}
        1    0.000    0.000    0.000    0.000 {built-in method create_db}
        1    0.000    0.000    0.000    0.000 {method 'disable' of '_lsprof.Profiler' objects}

         200005 function calls in 24.802 seconds

   Ordered by: cumulative time

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
        1    0.006    0.006   24.802   24.802 <string>:1(<module>)
        1    0.276    0.276   24.796   24.796 test.py:67(test_get_plugin_tags_performance)
   200000   24.202    0.000   24.202    0.000 {built-in method get_plugin_tags}
        1    0.319    0.319    0.319    0.319 {built-in method load_lists}
        1    0.000    0.000    0.000    0.000 {built-in method create_db}
        1    0.000    0.000    0.000    0.000 {method 'disable' of '_lsprof.Profiler' objects}

        200005 function calls in 25.597 seconds

  Ordered by: cumulative time

  ncalls  tottime  percall  cumtime  percall filename:lineno(function)
       1    0.007    0.007   25.597   25.597 <string>:1(<module>)
       1    0.282    0.282   25.591   25.591 test.py:67(test_get_plugin_tags_performance)
  200000   24.990    0.000   24.990    0.000 {built-in method get_plugin_tags}
       1    0.318    0.318    0.318    0.318 {built-in method load_lists}
       1    0.000    0.000    0.000    0.000 {built-in method create_db}
       1    0.000    0.000    0.000    0.000 {method 'disable' of '_lsprof.Profiler' objects}

       200005 function calls in 24.895 seconds

 Ordered by: cumulative time

 ncalls  tottime  percall  cumtime  percall filename:lineno(function)
      1    0.006    0.006   24.895   24.895 <string>:1(<module>)
      1    0.275    0.275   24.890   24.890 test.py:67(test_get_plugin_tags_performance)
 200000   24.298    0.000   24.298    0.000 {built-in method get_plugin_tags}
      1    0.316    0.316    0.316    0.316 {built-in method load_lists}
      1    0.000    0.000    0.000    0.000 {built-in method create_db}
      1    0.000    0.000    0.000    0.000 {method 'disable' of '_lsprof.Profiler' objects}

      200005 function calls in 25.337 seconds

Ordered by: cumulative time

ncalls  tottime  percall  cumtime  percall filename:lineno(function)
     1    0.006    0.006   25.337   25.337 <string>:1(<module>)
     1    0.279    0.279   25.331   25.331 test.py:67(test_get_plugin_tags_performance)
200000   24.733    0.000   24.733    0.000 {built-in method get_plugin_tags}
     1    0.318    0.318    0.318    0.318 {built-in method load_lists}
     1    0.000    0.000    0.000    0.000 {built-in method create_db}
     1    0.000    0.000    0.000    0.000 {method 'disable' of '_lsprof.Profiler' objects}
```

Unfortunately the profiler doesn't give microsecond-precision, but averaged over so many calls it doesn't make much of a difference.

**Comment by Utumno** [comment]
> loot_lang_any was removed in 0.9.0: use loot_lang_english instead, it's functionally equivalent.

Thanks will try and post back if I encounter further issues

> Well, there's the profiling we did, plus stack overflow posts like those here and here.

Very interesting - I did feel there is something laggy with the dlls (see the OP here) - of course it is a complex subject and we may be missing stuff

> I'd like to do my own profiling of Wrye Bash for direct comparison against my earlier results and in the future against the pybind11-generated module, if I download the source archive for this commit do I just need the usual Python dependencies (wx, pywin32, comtypes)?

Yep - cProfile is part of python std

----

> @Utumno: I guess this result means you'd like to see this new C++ API and its Python wrapper module fleshed out? If so, I'd value your input on the wrapper's API, so you get something that's useful and pleasant to use (since I'm not a Python dev, I might miss some things).

Well yes ! Unfortunately I have no time at the moment (moreover I am currently away from my main machine). However it may be an opportunity to refactor the C++ API too (apparently as recent bugs show few people were using the latest iterations) so we can get some performance right in C++ (also memory performance). If you find some time could you document a bit the internals of the API calls and db loading (caching policies etc) ? This would help to make more informed decisions on the wrapper.

**Comment by WrinklyNinja** [comment]
> However it may be an opportunity to refactor the C++ API

It doesn't exist yet - I've included an example of what I'm aiming for in the description for #632.

> so we can get some performance right in C++

As this issue shows, if you find a case where performance is a real issue, I'll go a long way to fix it, but I'm not interested in optimising before there's any evidence that the current performance isn't acceptable.

> If you find some time could you document a bit the internals of the API calls and db loading (caching policies etc) ? This would help to make more informed decisions on the wrapper.

I can try to flesh out the detail a bit.

**Comment by WrinklyNinja** [comment]
Closing this, as it's been superseded by #632 and loot/loot-api-python#3.

Python wrapper snapshot builds, including the DLL they're built against, are [now available](https://bintray.com/wrinklyninja/loot/loot-api-python#files). It (and LOOT builds on the `c++-api` branch) requires the [MSVC 2015 x86 redistributable](https://download.microsoft.com/download/9/3/F/93FCF1E7-E6A4-478B-96E7-D4B285925B00/vc_redist.x86.exe), but this is the lesser of two evils (more info [here](https://github.com/loot/loot/issues/632#issuecomment-239608579)).

There's no documentation for the new API and wrapper yet, I still need to write some and figure out the best way to provide it that's CI-friendly.
