### ISSUE TITLE
Include xEdit version in `dirty` entries

### ISSUE THREAD

**Issue by Freso** [loot/loot#608]
Since LOOT v0.10.0 is going to support `clean` entries with xEdit version information (#414), perhaps we can also start including version information in `dirty` entries? I have until now included xEdit version information in code comments (seems like I didn't do any for a long time, but @Sharlikran ported over some from the old BOSS lists in e.g., https://github.com/loot/skyrim/commit/2671f4d0dcad4518b9e12ad79dcd99b28b72a036), but we might as well just have them encoded properly so LOOT (or something else parsing the masterlists - e.g., you could generate a report with plugin files needed to be rechecked if they're >x versions behind) can use the information.

**Comment by Sharlikran** [comment]
I think it's a great idea but no idea how to implement it.  

The commit you linked was me trying to port over comments from the BOSS masterlist to the yaml file.  Later on it was deemed unreadable and I was asked not to do that anymore.  I can't find the commit or the forum post to reference, sorry.

**Comment by Freso** [comment]
Well, right now *all* `dirty` entries have `util: *dirtyUtil`. Maybe we don't even need a schema change, but just agree that from v0.10.0 onwards, the `util` should mirror how it's used for `clean` entries:
```
name: Example.esp
clean:
   - crc: 0x01234567
     util: 'TES5Edit v3.1.0'
```
(From https://github.com/loot/loot/issues/414#issuecomment-112163379)

**Comment by WrinklyNinja** [comment]
The trouble with doing that is that `util` has slightly different meanings between `clean` and `dirty` entries. In the former, it's what utility was used to check the plugin, but in the latter it's what utility should be used to clean the plugin. Specifying a version in the latter case is a bit odd. (Also you'd want to keep it a link so that users can get to the cleaning instructions.)

**Comment by Freso** [comment]
Hm. I'm not sure it's a good idea to use `util` for both if they are to be interpreted different actually. But then, I'm not sure about the usefulness of the `util` bit for the `dirty` flags since *every single* `dirty` bit has `util: *dirtyUtil`. `&dirtyUtil` is (slightly) different between masterlists, but for all of them, *every* instance of `dirty` has `util: *dirtyUtil`. Perhaps make a "magic message" (`commons: dirtyUtilMessage`?) or something that LOOT can utilise for displaying for `dirty` plugins?

Or `util_version`? ("Verified clean as per $util_version.", "Dirty data found using $util_version.")

**Comment by WrinklyNinja** [comment]
Well, a new top-level `constants` or whatever map could be added for the masterlist to insert into every cleaning data object, but it would complicate parsing as every object is independent (merge keys are handled at a lower level, and that wouldn't be suitable for such shared constants), and so interdependence would have to be introduced, which could be tricky to get right.

The other reason for keeping `util` per-object is that some plugins require additional manual cleaning, and it's a good place to put a message string including or linking to the relevant information.

As for not being sure about differing interpretation based on which field they're used in, why isn't that a problem for file data, which can be requirements, incompatibilities or load after metadata? Just as the meaning of `name` varies there, the varying meaning of `util` makes sense in the context you use it.

However, what about `utility` being the utility + version used to check, and `info` being the string appended to the dirty message. The message could be changed slightly so that instead of `Contains X ITMs, Y deleted records and Z deleted navmeshes. Clean with UTILITY.`, it would read `X ITMs, Y deleted records and Z deleted navmeshes found by UTILITY. INFO`. How does that sound?

**Comment by Freso** [comment]
> However, what about `utility` being the utility + version used to check, and `info` being the string appended to the dirty message. The message could be changed slightly so that instead of `Contains X ITMs, Y deleted records and Z deleted navmeshes. Clean with UTILITY.`, it would read `X ITMs, Y deleted records and Z deleted navmeshes found by UTILITY. INFO`. How does that sound?

I like the sound of that. 👍

**Comment by WrinklyNinja** [comment]
I'll make that change then, and make `info` like the message `content` field, so it can take localised strings too.
