### ISSUE TITLE
FIX: Windows 10 - Running LOOT through Mod Organizer 2 - Only lists DLC and no plugins

### ISSUE THREAD

**Issue by fortunequacker** [loot/loot#615]
Once I figured this out, it is actually a  very simple and quick fix.
I recently uninstalled my previous antivirus and am now using Windows Defender.
Didn't make the connection at first due to time between changes to setup.
When I would run Mod Organizer 2 and then LOOT all I would see is the DLC listed and no plugins.
Went through all the normal reinstalls, getting latest drivers, downloads, etc.  Nothing worked.
Then for giggles, I tried excluding the usvfs_proxy.exe file in the ModOrganizer folder.
Everything works perfectly now.
I actually now have Oblivion, Fallout NV, Skyrim and Fallout 4 all working with Mod Organizer 2 and LOOT!

**Comment by Freso** [comment]
Happy to see you managed to make it work. :)

You may want to post this in one/some of the Mod Organizer threads to alert/inform other MO2 users. (We don't actively support running LOOT through MO, since anything that causes LOOT to not work under MO is really on MO (assuming LOOT runs fine outside of MO), so there's nothing we can do about it on our end.)

**Comment by fortunequacker** [comment]
I posted there when I posted here.

**Comment by fortunequacker** [comment]
Unfortunately, this "fix", that I thought I discovered, has stopped working.  So, back to the drawing board on this one.

**Comment by sachaw** [comment]
Same issue, loads all manually added esm and esp's but none that are loaded via vfs, any ideas?

**Comment by ViralGamer** [comment]
Actually, I finally gave up on using MO2.  There are some that claim it works with Win10.  But that has not been my experience.  Sorry I cannot help you.
