### ISSUE TITLE
Improve handling of plural forms in messages

### ISSUE THREAD

**Issue by WrinklyNinja** [loot/loot#631]
Mentioned by pStyl3 [here](http://forums.bethsoft.com/topic/1603366-rel-loot-thread-24/?p=25200182) in the context of the dirty info message not having singular forms for its count, but more generally there's no distinction given between singular and plural forms for any translatable messages.

**Comment by WrinklyNinja** [comment]
@pStyl3 @Freso Do the new dirty plugin message strings suit your needs for plural forms? I'm not sure about the combined strings (`%1% found %2%, %3% and %4%.` and similar), but hopefully they'll do.

**Comment by Freso** [comment]
It will work fine for Danish at least, but I can imagine that for some languages something like `format(translate("%1% found %2%, %3% and %4%.")) % utility_ % itmRecords % deletedReferences % deletedNavmeshes;` would be hard to do because conjugation of `%4%` might depend on number of `%3%`, though I can't think of any languages like this off the top of my head—so an improvement for now, and let's deal with edge cases once they're reported.

Would be good to get some of the translators of the less indo-european languages to give feedback though.

**Comment by WrinklyNinja** [comment]
@loot/translators Any feedback on these changes?

**Comment by WrinklyNinja** [comment]
Done as of c88bf590dbc465316b224c51e5494934387b3d4c, can be re-opened if further improvements are necessary.
