### ISSUE TITLE
LOOT API doesn't accept symlinks to directories as CreateDatabase arguments

### ISSUE THREAD

**Issue by WrinklyNinja** [loot/loot#645]
Mentioned in wrye-bash/wrye-bash#325. `CreateDatabase()` checks that the given paths are directories, which means that if a given path is to a symlink that points to a directory, the function errors. It should instead resolve the symlink before checking if it's a directory.

I had a quick search for other cases where I use `boost::filesystem::is_*` functions and I don't think any other cases would cause problems (unless people are symlinking plugins, which is unlikely).

**Comment by neoh4x0r** [comment]
@WrinklyNinja 
My setup is:
```Wine 1.8.4 / Debian Jessie 8```

This is how I created the symlink:

1) move folder
~/Games/Steam/steamapps/common/Skyrim
to
~/Games/Bethesda Softworks/Skyrim

2) delete folder 
~/Games/Steam/steamapps/common/Skyrim

3) create symlink
ln -s "~/Games/Bethesda Softworks/Skyrim" ~/Games/Steam/steamapps/common/Skyrim

**Comment by Utumno** [comment]
Thanks for looking at this - if this is fixed shortly I would like to bundle the snapshot that fixes it instead of 9.2 with Bash 307 beta

**Comment by WrinklyNinja** [comment]
@Utumno: I don't think I can reasonably provide support for running the LOOT API through Wine. I already have CI set up for native Windows and Linux builds, I'm not sure how I could feasibly extend that to cover Windows builds that then publish the test binaries and trigger a second Linux CI build that runs the binaries through Wine...

That said, the issue existed when running natively, so I'm guessing my fix will also work through Wine.

> Thanks for looking at this - if this is fixed shortly I would like to bundle the snapshot that fixes it instead of 9.2 with Bash 307 beta

The fix is made against the `dev` code, which has the C++ API, so you won't be able to just replace the DLL (unless you've already made the switch?). Once the fix is merged, I'll update the python wrapper and notify you once a snapshot build for it has been published. I also want to bump the version number to 0.10.0 to avoid confusion, and add independent versioning for the Python wrapper, to avoid confusion.

**Comment by Utumno** [comment]
I had not time to look at the C++ API - one issue that bothers me though is that it requires the C++ MSVC redistributable - which means another dependency (we had removed that) and rewriting the NSIS scripts for downloading it etc - not my cup of tea. In short - I would need some help plugging that in, could you throw a hand ?

**Comment by WrinklyNinja** [comment]
> rewriting the NSIS scripts for downloading it etc - not my cup of tea. In short - I would need some help plugging that in, could you throw a hand ?

I think I've done that before, I can have a look once done on my end.

**Comment by neoh4x0r** [comment]
With the C++ MSVC redistributable what version of it are you using?
There are issues with VC2014 not running natively under  XP or Server 2003 -- so wine would be out of the question.

@WrinklyNinja 
Where can the native linux builds be downloaded from?
I ask because the release page (for 9.2) says the tar.xz contain a linux binary (but the filname is 'metadata-validator_0.9.2-0-g6b58f92_dev.tar.xz') -- I assumed that this was not loot binary.

**Comment by WrinklyNinja** [comment]
> What version of the C++ MSVC redistributable are you using to build loot?

2015, and targeting anything older is not going to happen because I require C++11 support (and make use of some C++14 improvements too).

> Are there native linux binaries available for linux?

Snapshot builds are hosted on [Bintray](https://bintray.com/wrinklyninja/loot). The Linux builds are made using GCC 5.x on Ubuntu 12.04.

**Comment by Utumno** [comment]
> I think I've done that before, I can have a look once done on my end.

Thanks, here is a relevant commit: https://github.com/wrye-bash/wrye-bash/commit/874a59a80a3b5af4bf8cc0b09d2c384983c874d9 - commits around this are also relevant. I would need some holding hands with plugging in the api too - as in a pull req. Had a look at the docs: http://loot.readthedocs.io/en/latest/miscellaneous.html good job :+1: I still have no time for delving deeper - will come back for more.

>  Can Wrye bash be compiled to run natively on linux?

@neoh4x0r: compiling ? Should run natively - it's a python app. However since this was not even dreamt about by my predecessors there is a lot to investigate - relevant goal issue: https://github.com/wrye-bash/wrye-bash/issues/243 - follow the commit links there to get a notion, let's not hijack loot's tracker.

**Comment by neoh4x0r** [comment]
@WrinklyNinja 
I tried the latest linux build from bintray: loot_0.9.2-74-g6809c39_dev.tar.xz

but I get this error:
```
./LOOT: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by ./LOOT)
./LOOT: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `CXXABI_1.3.9' not found (required by ./LOOT)
```

The higest that I have is from libstdc++6:amd64 / 4.9.2-10:
GLIBCXX_3.4.20
CXXABI_1.3.8

I would have to upgrade my system from debian/jessie to stretch to potentially fix this

---------
right now the highest loot version I have been able to run is 0.9.0 (under wine -- no native linux build available)
https://github.com/loot/loot/releases/tag/0.9.0

Do you forsee any problem with sticking with 0.9.0 (run under wine)
or will this eventually, and silently, break?

-- my only option beyond this is try to update to stretch (which I have had problems with in the past)
** going back to Windows would not be an option for me (as I hate it -- with a passion)

**Comment by WrinklyNinja** [comment]
You could also try adding a PPA with a newer version of libstdc++, or you could try building LOOT yourself (4.9.2 *might* work).

I don't foresee any existing build of LOOT breaking, but I do know that existing releases have bugs, and I do know that once v0.10.0 is released, the masterlists for older versions will most likely become unmaintained (unless someone backports commits to them).

**Comment by neoh4x0r** [comment]
@WrinklyNinja 
I could try to install a newer version of libstdc++ -- but from my experience that means a lot of applications will be broken (since they depend on an older version).

It would be easier for me to try to backup my current system and upgrade from stable (jessie) to testing (stretch).
Jessie currently has: libstdc++6/4.9.2-10
Stretch has: libstdc++6/6.1.1-11
and sid: libstdc++6/6.2.0-4

I am in the process of backing up my system with the intention of trying to upgrade to stretch....
I'll have to wait and see if that works out..

**Comment by neoh4x0r** [comment]
@WrinklyNinja 
I was unable to update to stretch (it had too many issues and resulted in only a partially working system.

Also I am on Debian/Jessie I cannot use Ubuntu PPAs (it is not recommended as it will likely break the system)
https://wiki.debian.org/DontBreakDebian#Don.27t_make_a_FrankenDebian

I guess I will have to wait for the Debian/Stretch freeze and subsequent stable release sometime in February/2017.
