### ISSUE TITLE
v0.9.2 Blank Screen in Mod Organizer

### ISSUE THREAD

**Issue by coralcity** [loot/loot#660]
I've tried to open LOOT from Mod Organizer, and I always get a blank screen. I've already tried "--single-process", with no change. LOOT worked perfectly before I moved the LOOT folder into the Mod Organizer folder.

**Comment by pStyl3** [comment]
Did you adjust your Binary path to the LOOT executable in MO's "Modify Executables" menu?

If the answer is yes and the problem is still occuring, try reinstalling MO, which can be done by simply deleting everything in your MO folder BUT the "downloads", "mods" and "profiles" folders, and installing a fresh MO installation over it. Creating a backup beforehand would be advisable.

**Comment by coralcity** [comment]
I uninstalled Mod Organizer, but LOOT was still on a blank screen. So I uninstalled that too, reinstalled Mod Organizer, then installed LOOT into a folder in the Mod Organizer folder. That seemed to work, LOOT immediately went into MO executable list and it works now.
