### ISSUE TITLE
Skyrim Special Edition support

### ISSUE THREAD

**Issue by draeath** [loot/loot#669]
Skyrim Special Edition has released this evening and there are already a large amount of mods ported over. There doesn't seem to be an existing issue to track this, and the current release doesn't support it (out of the box at least) either.

So, without further ado, here be an issue formally requesting support!

**Comment by WrinklyNinja** [comment]
This is already being worked on in the `skyrim-se-support` branch.

**Comment by WrinklyNinja** [comment]
@Sharlikran I'm confused, is Skyrim SE's local app data folder `Skyrim Special Edition` or `SkyrimSE`? I've got a user with both folders, and I can't launch the game on the laptop I've got to check myself.

**Comment by DeathProxie** [comment]
@WrinklyNinja I just installed a few mods via NMM and the plugins.txt inside the Skyrim Special Edition was modified and the SkyrimSE folder was not. I went in-game to confirm the mods were working and they did. So that should be the correct one. Folder path below to make sure we're talking about the same thing.

C:\Users\UserName\AppData\Local\Skyrim Special Edition

**Comment by WrinklyNinja** [comment]
Thanks!

**Comment by WrinklyNinja** [comment]
Closing this as it's now done in 9013cb2c815d6d0d29696df867b3cdc2739b64d8.
