### ISSUE TITLE
Mod list covering LOOT window.

### ISSUE THREAD

**Issue by ShadeC4** [loot/loot#702]
Hello. My issue with LOOT is that windows that pop up within LOOT are appearing behind the mod list, making it difficult to use the program. This has been happening in both 0.10.0 and 0.10.1. I have attached an image displaying my issue.
![loot_modlist_bug](https://cloud.githubusercontent.com/assets/23424425/20242351/b7fd3fd4-a8f0-11e6-979b-87c3399a1249.png)
For the time being I am continuing to use 0.9.2 as I know of no other way to fix this issue currently.

In case it is important, I am using Windows 7 Pro 64 bit, 8 gb RAM, 15-2500K processor. Thank you in advance. :)

**Comment by WrinklyNinja** [comment]
Please see [How To Report Issues Helpfully](http://loot.github.io/docs/help/How-To-Report-Issues-Helpfully.html). The CEFDebugLog.txt in particular may include useful information for this issue.

**Comment by ShadeC4** [comment]
My bad. Here's the files:
[LOOTDebugLog.txt](https://github.com/loot/loot/files/587592/LOOTDebugLog.txt)
[CEFDebugLog.txt](https://github.com/loot/loot/files/587593/CEFDebugLog.txt)

**Comment by WrinklyNinja** [comment]
Hmm, they didn't give any clues. I'm not sure why this is happening only for you, but I guess it's related to updating Chromium. I'll update the CEF build used and post a link to a snapshot build for you to test once it becomes available.

**Comment by WrinklyNinja** [comment]
OK, please try [this snapshot build](https://bintray.com/wrinklyninja/loot/LOOT/0.10.1-2-gb62295e_update-cef).

**Comment by WrinklyNinja** [comment]
There's an issue preventing CI builds from passing, so snapshot builds are currently unavailable until chocolatey/chocolatey-coreteampackages#394 is fixed.

**Comment by ShadeC4** [comment]
Thank you. :) I shall patiently wait.

**Comment by WrinklyNinja** [comment]
OK, the [snapshot build](https://bintray.com/wrinklyninja/loot/LOOT/0.10.1-2-gb62295e_update-cef) is now available, download the 7z archive and try running the LOOT.exe in there.

**Comment by ShadeC4** [comment]
The issue is still occurring. :/

**Comment by pStyl3** [comment]
Can you provide your debug logs with the new snapshot build?

**Comment by ShadeC4** [comment]
Here ya go:
[LOOTDebugLog.txt](https://github.com/loot/loot/files/588164/LOOTDebugLog.txt)
[CEFDebugLog.txt](https://github.com/loot/loot/files/588165/CEFDebugLog.txt)

**Comment by WrinklyNinja** [comment]
Still no use... I suspect it's a z-index-related rendering bug in Chromium, what graphics card / integrated graphics chip do you use, and what drivers (if you know) for it?

**Comment by ShadeC4** [comment]
AMD Radeon HD 6800 Series

**Comment by ShadeC4** [comment]
My driver version is apparently: 15.200.1062.1004
I also got this info in case it's needed:
![displaydriverinfo](https://cloud.githubusercontent.com/assets/23424425/20283148/75338fee-aa7d-11e6-92aa-033deffc95fa.png)

**Comment by Steve-E-M** [comment]
Just wanted to add my name in the ring here. I'm seeing similar issues and possibly even worse on the settings page: 
![image](https://cloud.githubusercontent.com/assets/23468638/20292882/452d0392-aabf-11e6-8592-0b848fb90397.png)
I'm running a GeForce GTX 970M
[NVIDIA System Information 11-14-2016 23-11-42.txt](https://github.com/loot/loot/files/591077/NVIDIA.System.Information.11-14-2016.23-11-42.txt)

**Comment by WrinklyNinja** [comment]
If you change the sidebar to the Filters tab, does the overlap still occur?

**Comment by ShadeC4** [comment]
The overlap is not there when the filters tab is selected.

**Comment by WrinklyNinja** [comment]
@ShadeC4: How many plugins do you have installed?

**Comment by WrinklyNinja** [comment]
Well, I think I have it.

When the CSS `@media only screen and (-webkit-max-device-pixel-ratio: 1)` query fails, the `will-change: transform;` styling is not applied to the sidebar's plugin list. One of the side-effects of that styling is that it forces a new stacking context, basically meaning that when comparing z-positions, everything in the list element seems to have the same z-position as the list element itself, but things in the list can have different z-positions relative to one another. When this stacking context is not forced, the z-positions of the list elements are effectively exposed to comparison with elements outside the list. 

Now, list elements are given z-positions so that the first element has a z-position equal to the number of elements in the list, and the z-positions decrease as you go down the list (this is so that tooltips and other overlays overlap instead of underlapping).

The overlay and dialog boxes appear on top of other elements by setting z-positions of ~ 100. If you've got more than that number of plugins, the z-position of your first list element is > than the z-position of your dialog box, and this issue occurs.

So, can anyone experiencing the issue try scrolling down their sidebar plugin list and see if at one point it drops below the dialog overlay? Also, are you using a high-pixel-density screen?

**Comment by WrinklyNinja** [comment]
OK, [here's](https://bintray.com/wrinklyninja/loot/LOOT/0.10.1-7-g903dd4d_fix-sidebar-stacking#files) a snapshot build that fixes the issue I identified, let me know if it works.

**Comment by Steve-E-M** [comment]
Hey @WrinklyNinja , worked for me. Thanks!

**Comment by ShadeC4** [comment]
I tried scrolling to the bottom of my plugin list and it went back behind the menu I had opened. It did so at around the 93rd to 9E plugins I have installed. Now going to try the snapshot.

I am pleased to report the snapshot no longer has the z index issue. :) However, it restarted itself shortly after having been opened. Other than that it functions fine.

**Comment by WrinklyNinja** [comment]
Fixed in 903dd4dc8f285a0d01c892c834cdb4c94882b146.
