### ISSUE TITLE
Split LOOT API into its own repository

### ISSUE THREAD

**Issue by WrinklyNinja** [loot/loot#759]
Following from #753, it would be good to split the LOOT API into its own repository, and leave this repository for the GUI application only. The GUI build would then handle the API like how `loot-api-python` handles it. Like the Python wrapper, it would probably be useful to give the GUI its own versioning.

**Comment by WrinklyNinja** [comment]
@Freso: For the API repository, do you think I should try to rewrite all the GUI bits out of history, or just have a commit deleting those files? I'm leaning towards the latter as there's not a clean split throughout history, so there'll be stuff left over anyway, and the repo isn't very big anyway (~10 MB).

**Comment by Freso** [comment]
I think the most in-the-future-understandable approach is to make a commit cleaning out the GUI stuff. That will explain to anyone looking at the code in 5–10 years what happened—and if we ever decide to revert it, the two code bases will have common ancestor commits which makes for much easier merging. :)

The only downside that I can think of is 1) it makes the repository larger (if size is a big issue, you can clone a shallow copy for compiling etc.), 2) it makes it harder to tell exactly where/when the split happened when looking at the grand scheme of things (but OTOH, it also gives a more correct history, since the API was technically part of the other codebase before the "split").

**Comment by WrinklyNinja** [comment]
Done as of 089cb4fa0a42f848ec672795a5ec3879c3858046. I've also created the issues relevant to the API over to the new repository.
