### ISSUE TITLE
Unable to start Loot via MO2

### ISSUE THREAD

**Issue by FullBoat** [loot/loot#773]
I'm not able to start Loot via MOv2.0.7, I keep getting the settings screen, then it says I have an error. But, I am able to start it from outside of the program. Any ideas? This is the new Loot 11.0.0, but I also had the same thing in 0.10.3
[CEFDebugLog.txt](https://github.com/loot/loot/files/998727/CEFDebugLog.txt)
[LOOTDebugLog.txt](https://github.com/loot/loot/files/998728/LOOTDebugLog.txt)

**Comment by pStyl3** [comment]
Backup your MO installation. Then reinstall MO by deleting everything within your MO folder BUT the "downloads", "mods" and "profiles" folder and install a fresh MO installation over it. Also don't forget to delete the "LOOT" folder within C:\%localappdata%

That probably fixes your issue, otherwise theres likely nothing LOOT can do about it, as it's an issue only occuring in conjunction with MO.

**Comment by skeevy420** [comment]
I was having a similar issue after moving the contents of Skyrim SE to a ramdisk and setting a junction under my Steam directory that links to the ramdisk (I have 48GB of ram).  First LOOT wouldn't start, and when it finally did, didn't work correctly (files wouldn't write).  I first tried deleting %localappdata%\loot, reinstalling, and giving it admin privileges.

What I ended up doing was installing LOOT to a different hard drive (I suspect anything that isn't under Program Files or isn't a system directory will work) and giving LOOT admin privileges.   Hopefully you'll figure it out, good luck.

**Comment by FullBoat** [comment]
Well, I finally got it worked out. MO was creating a MO2 folder in my
Skyrim directory. I moved that folder to the main install location, and
re-pointed the config to it. LOOT starts like a champ now. Don't know why
it was giving me problems before. But, it works.

Thanks for the tips.

**Comment by WrinklyNinja** [comment]
Glad you got it working, closing this.
