### ISSUE TITLE
Blank screen when running Loot v0.11

### ISSUE THREAD

**Issue by MrMcClusky** [loot/loot#778]
Hi,
I installed v0.11 a few days ago and it was working fine but it now shows a blank screen when it starts - either when running via Mod Organiser or standalone.  I've tried passing the --single-process argument that I found mentioned on an old thread for an earlier version but this has made no difference.  The only changes I've made to my set up are to install a new nVIDIA driver (version 382.05).

Any help gratefully received!

Thanks.

**Comment by WrinklyNinja** [comment]
I'm running the same driver and haven't experienced any issues. 
Please see [How To Report Issues Helpfully](http://loot.github.io/docs/help/How-To-Report-Issues-Helpfully.html) and provide your debug logs as described.

**Comment by toddzilla57** [comment]
Having a similar issue here. I recently reinstalled Windows 10 on my laptop and needed to reinstall LOOT as well. I can't get it to work through MO, NMM, or Standalone. It always comes up looking like this 
![screenshot 1](https://user-images.githubusercontent.com/29789154/27719141-7ba4b2e6-5d1e-11e7-9084-d8785293ff73.png)

I'm really at a loss as to what would cause this. I've tried reinstalling LOOT, running in compatibility mode, and all the same result. Please help?

[LOOTDebugLog.txt](https://github.com/loot/loot/files/1114000/LOOTDebugLog.txt)
[CEFDebugLog.txt](https://github.com/loot/loot/files/1113999/CEFDebugLog.txt)

**Comment by Freso** [comment]
@toddzilla57 If you're not sure it's exactly the same issue, it's generally better to open a new one.

What game are you trying to use LOOT with? Did you run that game's launcher to make it make a registry entry? There doesn't seem to be anything abnormal about the screenshot you're showing. @MrMcClusky talked about showing a blank screen when opening LOOT, which is not what you're seeing. Since @MrMcClusky didn't reply back in over a month, I'll close this issue. Please open a new issue @toddzilla57 with more details.
