### ISSUE TITLE
New to LOOT, no idea what the issue is

### ISSUE THREAD

**Issue by AshbornK9** [loot/loot#797]
Been trying to use Mod Organizer with Skyrim, ran LOOT with it successfully a few times, now it throws an error saying 

Oh no, something went wrong! You can check your LOOTDebugLog.txt (you can get to it through the main menu) for more information.

The debug log then reads

LOOTDebugLog.txt: https://pastebin.com/SCR49cUx
LOOTAPIDebugLog.txt: https://pastebin.com/nQYb9QcT
CEFDebugLog.txt: https://pastebin.com/VUgjtiVP

(There's an extra pathing in there as Skrim, that I tried adding to see if it was an issue with the directory, it wasn't as far as I can tell)

**Comment by Freso** [comment]
Can you reproduce the issue without Mod Organizer?

**Comment by AshbornK9** [comment]
I did run into some error without Mod Organizer after this error started, but a fresh install fixed that. Now it runs normally without it

**Comment by AshbornK9** [comment]
I should also add that without Mod Organizer, no mods are installed, just the DLC esp files and the High Res texture esm files

**Comment by Freso** [comment]
> without Mod Organizer, no mods are installed

That is expected, considering [how MO works](http://wiki.step-project.com/Guide:Mod_Organizer_Advanced#Internal_Mechanics).

Unfortunately, we can't really give support for problems that only happens when run LOOT is run through Mod Organizer, since MO does a lot of interfering with the system (which is not necessarily a bad thing, it's what makes MO superior (IMHO :)) to e.g., the NMM). If you can replicate the issue outside of MO, we'd be happy to look at it, but if not, you should report it with MO instead.
