### ISSUE TITLE
Bintray builds insists on being outdated

### ISSUE THREAD

**Issue by Freso** [loot/loot#804]
If I run the "nightly" builds from Bintray they always give me the message that there's a newer version of LOOT available, which is wrong. Either they should give a message that it's not a stable/final build, or it should wait until 0.11.1 or 0.12.0 is released until complaining that there's a newer build available.

**Comment by WrinklyNinja** [comment]
This is because the update checker is very dumb, it just checks the version number and build SHA and assumes anything that doesn't match the latest game is out of date.

One fix would be if performing a release automatically then bumped the version number, but a better solution would probably be to compare the dates of those build commits, which would either involve storing a date in the binary, or making another GitHub API request for the build commit to get its date.

The first method involves more code, but the second means it's more likely that a user hits the API rate limit (though that would mean launching LOOT more than 30 times in an hour, I'm not sure anyone not developing it does that..).

**Comment by Freso** [comment]
How is the GitHub API rate limited? Is it per IP, per API key? Per IP-per-API-key?

Anyway,
> checks the version number and build SHA

What if it just only checked version number and ignored the commit hash?

**Comment by WrinklyNinja** [comment]
It's per IP for unauthenticated requests, which LOOT's are. It checks the hash so that people on snapshot builds that have the "next" version number get an update notice when it's released.

**Comment by Freso** [comment]
Could we do something like version 0.11.0.r18 or 0.11.0.18 for the 18th commit since 0.11.0 was tagged? (Similar to using `git describe --tags`.)

Or maybe just add a new message "Your version is the same as the most recent version of LOOT but your build hash is different. If you were using a pre-release build, please update. If you're using a nightly/Bintray build, feel free to disregard."?

Or just add the additional GitHub API call. For far most users it shouldn't be an issue. Even I don't open LOOT that frequently (≥30 times/hour) in my peak periods, and I'm guessing that I'm one of the ones that open LOOT most frequently (besides you probably :) ).

**Comment by WrinklyNinja** [comment]
Counting commits doesn't work when you have branches. :wink:

**Comment by WrinklyNinja** [comment]
I think I'll go with the API call at least as a first shot, as it's simpler to implement and probably won't cause any problems.

**Comment by WrinklyNinja** [comment]
This is currently blocked on philschatz/octokat.js#190 getting merged.

**Comment by WrinklyNinja** [comment]
Done in 075e78a0399d4e1bf0df940773043dec0d85df40: I replaced octokat with another GitHub API library.
