### ISSUE TITLE
Support for .esl files

### ISSUE THREAD

**Issue by Freso** [loot/loot#816]
See https://bethesda.net/community/topic/85064/fallout-4-creation-kit-update-support-for-new-file-format and https://www.creationkit.com/fallout4/index.php?title=Data_File

**Comment by WrinklyNinja** [comment]
> Light Plugin: .esl
> 
> Light plugin (.esl) file are a new optimized file format, introduced in the 1.10 Update. They behave like a normal plugin, except for the following:
> .esl files are read-only. Active development should be done in an normal (.esp) plugin.
> .esl files bypass the 8-bit plugin ID limit (255).
> .esl files have a budget of no more than 4,000 forms.
> .esl files are treated as unique files from the .esp it was converted from, so saved games will not be compatible between them.
> To convert a normal plugin (.esp) to a light (.esl) plugin, load your .esp file, and under File, select Convert Active File to Light Master.
> It is good practice to run Compact Active File Form IDs to optimize your formids within the 4,000 form budget.
> NOTE: Compacting form ids does change formids in the plugin, so only do this before converting to .esl, and not on a .esp (plugin) you plan on releasing.

The above suggests you can have an unlimited number of `.esl` plugins active in a load order... I wonder what the limit actually is. I guess I could work that out from the file format.

I'll need to update libespm to support reading the new file format, libloadorder to recognise them and not include them in active plugins counts, and LOOT to recognise them. If you know of or come across any `.esl` files in the wild, or any docs detailing their structure, that would be useful, as I don't own Fallout 4.

Also, that wiki page mentions `.fos` plugins, any idea what they are?

**Comment by Freso** [comment]
FallOut... Shelter? No, I have no clue. I just saw the post on the Beth.net forum and thought LOOT should get ahead of the curve, and it didn't look like there was an issue already.

**Comment by Freso** [comment]
And yeah, I guess the "unlimited number of plugins" is in response to being able to download and enable mods directly via their interface + the upcoming Creator's Club, which means that mods are suddenly a lot more accessible to more people - and console users and PC users only using the in-game interface won't be using xEdit, Merge Plugins, etc. to be able to reduce the number of plugins.

**Comment by Freso** [comment]
.fos is the Fallout Savegame format, apparently: http://falloutmods.wikia.com/wiki/FOS_File_Format

**Comment by Freso** [comment]
According to [this Reddit comment](https://www.reddit.com/r/FalloutMods/comments/6u2qrg/fo4_fallout_4_creation_kit_update_support_for_new/dlq7wu9/), .esl files are essentially .esp files with a flipped bit (well, `00` to `02`, so a couple of flipped bits). I guess we yet have to see whether `Fallout4.exe` will treat the specially with regards to load order though.

**Comment by pStyl3** [comment]
In which ways, if any, is LOOT in it's current form limited by "max. 255 active plugins are allowed" ? Basically, what would happen if I tried right now to sort let's say 10.000 (normal) plugins?

Also, this whole situation raises the question, whether or not LOOT should differentiate between load orders containing
- only .esm / .esp's
- both .esm / .esp's and .esl's
- "only" .esm's / .esl's

Regarding option 3, at least one .esm is always given, the game master file. like for example `Skyrim.esm`.

**Comment by WrinklyNinja** [comment]
> In which ways, if any, is LOOT in it's current form limited by "max. 255 active plugins are allowed" ? Basically, what would happen if I tried right now to sort let's say 10.000 (normal) plugins?

AFAIR, the only thing is that when it gets the list of active plugins, only the first 255 will be returned, which may affect some conditions, and when the load order is written, only those 255 plugins will be active.

**Comment by Freso** [comment]
Fallout 4 1.10 is out now, with ESL support.

**Comment by WrinklyNinja** [comment]
Thanks for the heads-up, I'll keep an eye out for any info on ESL files.

**Comment by WrinklyNinja** [comment]
I've now got a copy of Fallout 4 thanks to Nebulous112's generosity, so I'll start working on this this weekend. @pStyl3 quoted some info from hlp on the LOOT thread, reposting it here:

> As far as I can see, ESL use 2 bytes for load order and 6 for formID, so they don't need to be renumbered. The runtime load order index was increased from 1 byte to two which changed the internal format of TESFile (ModInfo). Also CC content has been added to the list of file automatically loaded when the game start so probably they will load before any mod.
>
> What I wonder is if all ESL share the same most significant byte for load order (which would limit to 256 ESL at once) of if they can use more than one. Anybody tried to load 300 ESL yet ?

Things I want to look into are:

1. The file format of ESL files vs ESM/ESP files, so I know how to parse their headers and record FormIDs.
2. The format of FormIDs in ESL "on disk" and the format they take once loaded in the game (i.e.. their merging behaviour), so that LOOT can determine FormID overlap between ESL files and other plugins.
3. How are ESL files placed in the load order?
    - Are they treated like normal plugins, able to be active anywhere that's suitable for their master flag value, or are they treated like DLC and implicitly loaded before all other non-official plugins?
    - Is the master flag even present/checked, or do they always get treated as non-master plugins?
    - As hlp asks, do all ESL files have the same load order index, do consecutive ESLs share an index, or do they merge down to the index of the preceding plugin? (or something else?)
    - Do ESL files get recorded in plugins.txt like other plugins, with an asterisk prefix if they're active?
4. How do ESL files bypass the 255 active plugin limit?
    - What's the max number of ESL files you can have active, is the limit a combined limit with other plugins?
    - What happens to ESL files that are active beyond that limit?

That's all the questions I can think of for now.

**Comment by pStyl3** [comment]
I've purchased five cc-mods, the ingame ui tells me they are "owned" and "installed". Starting with a vanilla savegame, and playing with those cc-mods, then saving, leaves no `[M]` in front of the savegame's titel like it's the case if normal mods are detected, so e.g. it's not `[M] Commonwealth` but `Commonwealth`.

Apparently they also will not be written to plugins.txt. My game was vanilla prior to installing those cc-mods, so I had no plugins.txt in \localappdata\Fallout 4\  (official DLCs aren't written to plugins.txt). Installing those cc-mods did not create a plugins.txt in said folder.

**Comment by TanninOne** [comment]
The names of the esls are listed in the Fallout4.exe, near the names of the DLCs so I guess they get loaded automatically and in a fixed order.

**Comment by WrinklyNinja** [comment]
OK, what I've learned/verified so far:

- The only difference between and ESL and the ESP it was created from is that the ESL has a value of `0x200` in its `TES4` header's flags field.
- The game and creation kit treat ESL files as masters, as they are deactivated by default, are activated with an asterisk prefixing their `plugins.txt` line, and cannot load after non-master plugins.
- The game and creation kit check the file extension, not the `0x200` header flag, so a `.esp` file with that flag is still a normal plugin.
- Creation Club ESL plugins are treated like DLC: they are hardcoded in `Fallout4.exe` alongside the DLC plugins, do not appear in `plugins.txt`, and are implicitly loaded before other masters. The block in my `Fallout4.exe` is 

    ```
    DLCRobot.esm....
    DLCworkshop01.esm.......
    DLCCoast.esm....
    DLCUltraHighResolution.esm......
    Automatron......
    Wasteland Workshop......
    Far Harbor......
    Contraptions Workshop...
    Vault-Tec Workshop......
    Nuka-World......
    High Resolution Textures.......
    .ccBGSFO4001-PipBoy(Black).esl...
    ccBGSFO4002-PipBoy(Blue).esl....
    ccBGSFO4003-PipBoy(Camo01).esl..
    ccBGSFO4004-PipBoy(Camo02).esl..
    ccBGSFO4006-PipBoy(Chrome).esl..
    ccBGSFO4012-PipBoy(Red).esl.....
    ccBGSFO4014-PipBoy(White).esl...
    ccBGSFO4016-Prey.esl...
    .ccBGSFO4017-Mauler.esl..
    ccBGSFO4018-GaussRiflePrototype.esl.....
    ccBGSFO4019-ChineseStealthArmor.esl.....
    ccBGSFO4020-PowerArmorSkin(Black).esl...
    ccBGSFO4038-HorseArmor.esl......
    ccBGSFO4039-TunnelSnakes.esl....
    ccBGSFO4041-DoomMarineArmor.esl.
    ccBGSFO4042-BFG.esl.....
    ccBGSFO4043-DoomChainsaw.esl....
    ccBGSFO4044-HellfirePowerArmor.esl......
    ccFSVFO4001-ModularMilitaryBackpack.esl.
    ccFSVFO4002-MidCenturyModern.esl........
    ccFRSFO4001-HandmadeShotgun.esl.
    ccEEJFO4001-DecorationPack.esl..
    ```

    I have inserted line breaks for legibility, and the trailing periods are null byte padding. I'm not sure why not all the DLC master names are present, maybe it's because I don't own any DLC and if I did the Fallout4.exe might get patched to include them too...

- In game, ESL plugin FormIDs begin at `0xFE000xxx` and go up to `0xFFFFFxxx`, 'overflowing' into the savegame FormID space (`FF`). They do not overflow further into `0x00000xxx`. This means 4096 ESL plugins can be loaded in the `FE` index, and another 4096 ESL plugins can be loaded into the `FF` index.

With Creation Club content essentially being DLC outsourced to freelancers spun as some sort of backfiring PR stunt, their plugins being loaded like the DLC plugins makes sense, but hardcoding them in Fallout4.exe seems pretty daft to me - it means whenever a new CC DLC is released, Bethesda need to push an update to every player, and all the tools will need to be updated to handle it correctly. Why isn't that text block just in a text file so it's more easily extensible and more easily supported?

ESL FormIDs overflowing into the savegame index space also seems like a bad idea. It's pretty unlikely it'll happen, but without knowing how saving handles that FormID space, it also seems like saves could end up corrupted if it did.

Open questions that I'll get round to answering in the morning:

- How do (non-Creation-Club) ESL files load relative to normal masters?
- Is the FE load order slot now reserved for ESL files, i.e. what happens if there are 255 non-ESL plugins active, and what happens if an ESL plugin is then added?
- What order are Creation Club ESL plugins implicitly loaded in, is it the order they're hardcoded in?
- How do FormID overrides work between ESL and non-ESL plugins, and between ESL plugins?

**Comment by pStyl3** [comment]
> I'm not sure why not all the DLC master names are present, maybe it's because I don't own any DLC and if I did the Fallout4.exe might get patched to include them too...

They are listed a bit "higher" than the rest of the official DLCs / CC content, I doubt that your executable is different.

**Comment by TanninOne** [comment]
What do you mean by 
> I'm not sure why not all the DLC master names are present
? As far as I can tell, the exe lists all esls currently released plus a few that haven't been released (yet).
It's possible Bethesda is already including CC content that is currently in the works to avoid too many exe updates. On the other hand if this is their strategy to kill off the script extender it's not a bad one...

**Comment by WrinklyNinja** [comment]
Ah, ignore that bit, I later realised that the filenames are present, just not in the same block.

**Comment by pStyl3** [comment]
[Link](https://bethesda.net/community/topic/88724/why-is-fo4-auto-downloading-creation-club-ba2s/150?page=8)

Quote by Cartogriffi:
> Hi everyone, we’re working on solutions that would not require Creation Club archives  be part of the game’s patch. We are certainly listening to everything people are saying, and appreciate the constructive feedback, both positive and negative.
This note has also been added to the pinned FAQ.

**Comment by WrinklyNinja** [comment]
More questions answered:

- The FE load order slot is not reserved for ESL FormIDs, if there are 255 plugins present, the 255th will use the FE slot for its FormIDs. If an ESL plugin is also present, it uses the FE slot for its FormIDs too. If a normal plugin and an ESL have a record with the same Object ID, the ESL record is used. The other record is replaced, it doesn't get remapped to a different FormID.
- Creation Club ESLs appear to load in the order that they're listed above. I didn't test this exhaustively, because I'm getting errors downloading from the Nexus, so I've only got a couple of plugins to test with, and swapping them in and out of every combination would take ages.
- ESLs overriding records from other plugins and vice versa works as normal, the edits are squashed to the FormID of the original record.

---

So, in summary

- Utilities need to treat files with a `.esl` extension as light masters.
- Light masters behave like masters unless otherwise noted.
- Light masters don't count to the 255 active plugin limit: they take up one space (the FE load order index) in total, but can share it with a non-light-master plugin.
- If a non-light-master plugin shares a load order index with light master plugins, any FormID conflicts are won by the light master FormID replacing the non-light-master FormID.
- Up to 8192 light masters can be active at the same time, and they're loaded in the order they're listed in `plugins.txt`.
- If over 4096 light masters are active, they start to use FormIDs in the FF index.
- There are some new implicitly-active plugins that are light masters.

UI for light master load order positions will be a bit weird, because their load order positions relative to non-light-master plugins are decoupled from the in-game load order index used by their FormIDs.

**Comment by pStyl3** [comment]
So it would be correct to say that .esl plugins are like .esm plugins, with the difference that the .esl plugins won't load _before_ .esp plugins, but _after_ them (as they use the FE/FF slots and as such, win all conflicts against .esm's and .esp's) .. right?

If so, it should technically be irrelevant, where .esl's are placed within plugins.txt _in relation to .esm's and .esp's_. So technically ..

> pluginA.esp
pluginB.esl
pluginC.esl
pluginD.esp

.. within plugins.txt would load the .esl's after the .esp's just like

> pluginA.esp
pluginD.esp
pluginB.esl
pluginC.esl

But if we have the freedom to place .esl plugins whereever we want within plugins.txt - in relation to .esm's and .esp's - we could also say that we _want_ them to be placed at the bottom of plugins.txt, reflecting their behaviour to load after .esm's and .esp's. Not to mention that it would be neater that way.

The UI needs to be updated in some way or another for this, as mentioned by wrinklyninja. I would propose the following:

If no .esl plugins are detected within the \data\ folder, nothing changes.

IF there are .esl plugins detected, display for the .esl plugins 1-4096 the load order index FE and for the .esl plugins 4097-8192 the load order index FF - even if the very first .esl plugin is NOT the 255th plugin within plugins.txt. That would mean, if that's not the case (let's say the first .esl plugin is the 20th plugin within plugins.txt) that the load order index displayed within LOOT would skip the "missing" load order indices between the last .esp and the first .esl and still would display FE/FF for the .esl's.

Then I would further suggest to not leave it at that. The .esl plugins may be decoupled from the original system and only use up to 2 slots ("normally" only 1 --> FE, unlikely that even one person on this planet will go beyond 4096 .esl's), however the order in which they are listed amonst themselves within plugins.txt is as important as always. Therefore, if at least one .esl is detected within the \data\ folder, I would suggest to
- not display a circle around their load order index, to obtain more space to display additional things
- display the decimal number of the .esl plugins underneath the FE/FF index

So as an example.
> Plugin1.esl
Plugin2.esl
Plugin3.esl

Would be displayed with the following indices:
> FE
#1 

> FE
#2 

> FE
#3 


It would probably be best to add a # to the decimal, indicating a decimal number (contrary to the hexadecimal number above it). I would also say that 1 instead of 0001, 2 instead of 0002 and so forth would be better.

That way, while those decimal numbers may not be relevant for plugins.txt, LOOT users would still have an efficient way to talk about the order of their .esl plugins.


Last but not least, while it will be pretty cumbersome, it's likely best to handle the CC .esp's just as other official content and not write them to plugins.txt, right? They are hard-coded in Fallout4.exe and as such their potential entries within plugins.txt should have no effect.

**Comment by WrinklyNinja** [comment]
> So it would be correct to say that .esl plugins are like .esm plugins, with the difference that the .esl plugins won't load before .esp plugins, but after them (as they use the FE/FF slots and as such, win all conflicts against .esm's and .esp's) .. right?

Well, not exactly, because you can have a `.esp` override a `.esl`'s record, so the `.esl` must be loading first, even if that record is then given an FE/FF modIndex at runtime.

For clarity I think the best approach is to display their positions as they are in plugins.txt, but give them the load order index they'd use at runtime. That will result in out-of-sequence indices, which will look odd, but it's also the least wrong representation.

Here's your suggestion mocked up:

![screenshot 6](https://user-images.githubusercontent.com/2430738/31047774-a1214b6e-a608-11e7-810d-40158511aeec.png)

I think that looks OK, though as shown it gets a bit cramped with three digits, and four overhangs.

For my own reference, the CSS on the `item-icon` div is 

```
line-height: 12px;
width: 32px;
position: relative;
left: -3px;
border: none;
```

and it has two child divs, one for the index and another for the number.

The "Copy Load Order" output will also need adjusting, inserting another column for the ESL "sub-index" after the load order index column.

**Comment by pStyl3** [comment]
I've got another idea. What if we display the load order indices FE/FF for .esl plugins just the normal way, and put decimal numbers (representing their order) "into the editor mode", so that they are displayed in the sidebar, next to global/local priority numbers, if the editor is opened?

That way, .esl plugins would have their correct indices being displayed without "destroying the look" of the sidebar as much as my first idea, yet there would be a way to say e.g. "here the 23th .esl plugin within my load order causes X".

**Comment by WrinklyNinja** [comment]
I don't think I mind either way, it's something I'll think about when I come to do the UI, I've only just started  updating the backend components.

**Comment by WrinklyNinja** [comment]
The initial UI suggestion (that I mocked up above) has been implemented as of bc4af44ba77a6308a77ee3a6541efc7564a73644. I decided on doing it this way because it was easier than having an index that only displays sometimes.

**Comment by WrinklyNinja** [comment]
Warning messages have been added in 612af58488c2d40f29ffac96d4d29d8113371805. The ESL-depends-on-non-master warning message has been made a plugin-specific message that is output for each non-master dependency, as the extra specificity is helpful.

**Comment by WrinklyNinja** [comment]
Merged in b38ca13c197cf04ef6ef2753ba54a8e625ad6d20, so closing this.

**Comment by decopauge123** [comment]
I read what posted 4 years ago.  It was very interesting.

I apologize if this i snot the correct place or time to ask my question. .  I looked on the Tome o xEdit and couldn't a place to ask.

Is giving a non Bethesda ,ESM file the ESL flag an acceptable action?  See xEdit message scrap below.

[08] BetterDynamicAsh-DisableRefs.esm
	Can be turned into ESL by adding ESL flag in TES4 header

I've read the Creation Kit Data File page and I am still not sure whehther or not I sould add the ESL flag to this .ESM file.  Please advice, and Thank You! for your time.

**Comment by sibir-ine** [comment]
The [xEdit Discord server](https://discord.gg/mQA5Wnu) would be a more appropriate place to ask, but it should be fine to add the flag.

**Comment by decopauge123** [comment]
Ah, Thanks for the quick reply.  Asking there didn't occur to me.  I'll go find out what they say.  Thanks!
