### ISSUE TITLE
Error on reading FreesideOpen - NewVegasBountiesIII.esp's masters

### ISSUE THREAD

**Issue by Gates6689** [loot/loot#858]
Hello sorry if this is not how i seek help but i recently updated to the newest loot version and loot wont show any of the mods i had installed previously i went to the debug text file it said to look at and this is what it gave me. 

[23:04:17.813873] [warning]: Blocking load of resource at https://fonts.googleapis.com/css?family=Roboto+Mono:400,700|Roboto:400,300,300italic,400italic,500,500italic,700,700italic
[23:04:20.912026] [error]: FreesideOpen - NewVegasBountiesIII.esp : Libespm error code: 3
[23:04:24.951235] [error]: FreesideOpen - NewVegasBountiesIII.esp : Libespm error code: 3
[23:10:02.384852] [error]: Given masterlist path "C:\Users\Trevor\AppData\Local\LOOT\FalloutNV\masterlist.yaml" does not have a valid parent directory.
[23:10:03.454976] [error]: Failed to sort plugins. Details: FreesideOpen - NewVegasBountiesIII.esp : Libespm error code: 3
[23:10:07.795009] [error]: Given masterlist path "C:\Users\Trevor\AppData\Local\LOOT\FalloutNV\masterlist.yaml" does not have a valid parent directory.
[23:10:08.870632] [error]: Failed to sort plugins. Details: FreesideOpen - NewVegasBountiesIII.esp : Libespm error code: 3
[23:10:11.405973] [error]: Given masterlist path "C:\Users\Trevor\AppData\Local\LOOT\FalloutNV\masterlist.yaml" does not have a valid parent directory.

**Comment by Gates6689** [comment]
I just opened loot and everything is fine now. not sure what i did to fix it but you can close the thread sorry to bother everyone.

**Comment by Gates6689** [comment]
well nevermind now it still wont set the load order i am getting this message now

Failed to sort plugins. Details: see general messages for details

**Comment by WrinklyNinja** [comment]
Error code 3 (actually from esplugin, not libespm, I need to update that error message...) is `ESP_ERROR_STRING_CONTAINS_NUL`, which is probably happening when getting `FreesideOpen - NewVegasBountiesIII.esp`'s masters. It might be that the plugin is a little corrupt, or a bug in esplugin. Can you provide a link to where you got that plugin?

`Given masterlist path "C:\Users\Trevor\AppData\Local\LOOT\FalloutNV\masterlist.yaml" does not have a valid parent directory.` is a bit strange, it's saying `C:\Users\Trevor\AppData\Local\LOOT\FalloutNV` is not a directory, which most likely means it doesn't exist. It should have been created when LOOT initialised for that game though, but maybe the plugin issue was preventing that code from running.

As for `Failed to sort plugins. Details: see general messages for details`, what do your general messages say?

**Comment by Gates6689** [comment]
I switched back to v11, v12 was giving way too many issues for me to handle right now

**Comment by WrinklyNinja** [comment]
Well, whatever works for you, but it's a lot harder for me to fix issues without being able to replicate them or have leads on them.

**Comment by boyianpetro** [comment]
Niamam loota

**Comment by WrinklyNinja** [comment]
From #868:

> Well, FreesideOpen - NewVegasBountiesIII.esp has a master that contains an extra trailing null byte, i.e. the escaped string after removing the null terminator is FreesideOpen.esm\0. I count this as corruption, but it may work in game because the game could just see the first null and ignore how long the string is supposed to be.
> 
> I could update esplugin to behave the same way, but it might be better to flag up such corruption in case it signals more significant issues.

**Comment by WrinklyNinja** [comment]
Closing this as I've decided to err on the side of correctness over permissiveness, and not change esplugin's behaviour.

**Comment by RoyBatty64** [comment]
An extra 0 is not "corruption". The game literally doesn't care about it because strings are null terminated. Your *warning* should be unexpected byte(s) at end of string.

**Comment by WrinklyNinja** [comment]
Corruption is the wrong term, and an extra null is probably harmless, but the plugin isn't describing its own content correctly, and I think that's cause for concern. To put it another way, the subrecord length field has only simple job, to say how many data bytes there are, and it couldn't do it.

I'm not a fan of warnings for things like this, previous experience has shown that they're ambiguous to deal with and overcomplicate logic and APIs. I'd rather error or just accept it. 

In this case I'm against accepting it because the error rate is so low that it's unlikely to be due to a bug in official tools, and more likely that the plugin was created by unofficial tools that may also be screwing up more significantly in ways LOOT doesn't check, so it's a potentially useful signal.

**Comment by RoyBatty64** [comment]
In this case it simply because I have different versions of plugins and I just remove the extra underscore by hex edit.

It's likely that I will use the same technique (and others)  to watermark my plugins for larger projects to nail people stealing them and posting them on dubious sites, which is an increasing problem these days.

**Comment by WrinklyNinja** [comment]
> It's likely that I will use the same technique (and others) to watermark my plugins for larger projects to nail people stealing them and posting them on dubious sites, which is an increasing problem these days.

You mean having fields with null bytes followed by your fingerprint, so that data is stored that doesn't get interpreted by the game? What's wrong with just using the description field to store the fingerprint without null byte prefixes? In my experience mod thieves are pretty lazy, if they're wholesale copying your plugins they're probably not going to even bother changing the description, and if they're being more careful about picking only bits of your plugin, any editor they use is probably going to truncate your fingerprint away anyway...

Still, it's good to know there are reasons for extra nulls existing beyond creating plugins in broken third party tools, I'll bear it in mind.

> Null terminated strings is standard to the windows API, it is by design and Bethesda uses standard string handling functions. This particular game is old and doesn't support unicode, so utf-8 etc is not an issue.

It's by Windows API and language (I'm guessing C / C++) design, but I meant that I doubt it's something Bethesda considered as part of their design. As for Bethesda games not supporting Unicode, *Windows 2000* supported Unicode, so age isn't the reason. Anyway, I know that Skyrim partially supports it (its Japanese translation text is encoded in UTF-8), just apparently not for filesystem stuff, which is particularly irritating since the Windows filesystem stuff is UTF-16-based...

**Comment by WrinklyNinja** [comment]
After sleeping on it, I've changed esplugin to not error and just truncate to the first null in string data. If people are intentionally using nulls in string fields, I think that's the right thing to do.

**Comment by RoyBatty64** [comment]
Yeah the whole unicode thing... at least you don't need unicows.dll anymore eh? 

Also I don't think my hex editor is a broken 3rd party tool :D I'm just a hacker like Pete said.

Thanks for doing that. We've actually had an issue with a certain not so lazy set of thieves. Now I just have to get zilav to do the same thing with xEdit...
