### ISSUE TITLE
LOOT crashes on startup before UI is displayed

### ISSUE THREAD

**Issue by sporevenom** [loot/loot#930]
LOOT was working fine before standalone or through ModOrganizer, but just randomly stopped opening. I click on the application and the loading wheel comes up but then it seems that LOOT fails to initialize completely. Same in MO. There is no debug file generated, and no bugs that seem to generate. I have tried removing all instances of LOOT and reinstalling, and installing older versions. Versions 11 through 12.5 do not open or load at all. Versions 10.3 and below do open and load, but get errors and are not usable. I have MSVC 2015 redist installed.

**Comment by sporevenom** [comment]
I also have tried installing LOOT in many different areas, and running it as administrator as well.

**Comment by jaydawg55** [comment]
I am having the same problem. It will not launch at all. It was working fine yesterday, all day long. Could there be a problem with Chrome? I am having an unrelated issue with it regarding password resetting.

**Comment by jaydawg55** [comment]
FYI, I am a noob. Just a frustrated LOOT user.

**Comment by WrinklyNinja** [comment]
This kind of thing (LOOT suddenly not wanting to run) has come up before, but not in a while, and unfortunately I've never been able to find out why. My best guess is that there's something in the Chromium startup process that goes wrong, but not being able to reliably replicate the issue means it's pretty difficult to debug...

**Comment by jaydawg55** [comment]
Is there any consideration being given to ending dependency on Chromium somehow? 

Yesterday I worked out my load order "by hand" so to speak and it took hours. I have a lot of mods (185 so far including the Bash patch). The game launched fine and I played for about an hour or so before bed. With no way of tapping into the crowd wisdom of LOOT, game stability will be suspect for a while. 

Whatever you can do, it is appreciated.

**Comment by jaydawg55** [comment]
I am a Windows 10 user, if that helps.

**Comment by WrinklyNinja** [comment]
> Is there any consideration being given to ending dependency on Chromium somehow?

Only superficially, it's a hard sell due to the technologies LOOT's been built on. The UI is essentially a single-page web application because it's easy to develop web UIs, and Chromium (via CEF) is used to display the page.

- The only real alternative embedded browser is to use whatever OS browser is available, but that could be anything from IE 8 up. IE is a dead browser and a PITA to target, so that's not really a very attractive option. It would also involve rewriting thousands of lines of code because old browsers don't support the technologies the UI uses.
- Using the user's default browser (so that LOOT just looks like a website, but running on your local machine) would mean having to cater for a million little browser variations, and isn't a very user-friendly interface for what's supposed to be a desktop application.
- LOOT could use a proper desktop UI framework instead of pretending to be a browser, but that would involve throwing away > 14k lines of code and rewriting everything from scratch. Also, the only GUI framework I'd consider using would be Qt (given my experience with directly using the Win32 APIs, wxWidgets and GTK), but I've never managed to get a non-trivial Qt project to build, I always run into trouble with getting the environment how Qt wants it.

I don't think it's Chromium/CEF itself that's causing problems though, given how widely it's used. It's far more likely that there's something LOOT's doing wrong during initialisation that I just haven't caught, and unfortunately it's a complex system and C++ isn't the safest of languages, so there's a lot that could be going wrong.

**Comment by sporevenom** [comment]
I did a reset on my computer, and after doing so, I could run loot 12.5-13, but 12.5-0 was not running again. When I would close 12.5-13, I got a windows error that said that the program stopped responding and to force close it. I would also get an error within LOOT when booting up, but I do not remember what that was. I installed DirectX and MSCV 2015 (downloaded from the LOOT page), and restarted computer. After a restart, neither version on LOOT worked, and neither started. Idk if this helps, and if I can, I will try to get -13 running again and get the debug log.

**Comment by WrinklyNinja** [comment]
Don't spend much time on it, I doubt the debug log would contain anything particularly helpful, since this issue seems to occur before logging starts.

That it starts/stops working on restart suggests to me that there may be some bad memory access happening, or resources aren't getting cleared up properly (if the latter though I'd expect restarting to always work). 

- Does LOOT always start successfully the first time you run it after restarting your PC? Try running the restarting then running the v0.12.5 release and restarting then running the 0.12.5-13 build.
- If you can get LOOT to start, after closing it check in task manager if there are any LOOT.exe processes still hanging around. If there aren't, open LOOT again then close it, and repeat until it doesn't start, then check for processes. I think for this one it's OK to switch between builds.

**Comment by sporevenom** [comment]
Let me clarify lol: I did a fresh install of windows on my computer, and then it started working again. After a few days, however, it stopped working again. And as for processes, none show up in task manager. It shows up when I attempt to start LOOT but goes away quickly.

**Comment by WrinklyNinja** [comment]
I'm not really sure what the problem is, or how to solve it: the fact that it works for you sometimes but not other times makes it particularly tricky.

**Comment by truckerraycruz** [comment]
wtf wont start

**Comment by WrinklyNinja** [comment]
Well, the good news is that I'm now experiencing this issue in my local dev builds, and it looks like there's a use-after-free or something similar when calling `window->AddChildView(browser_view_);` in `WindowDelegate::OnWindowCreated()` during startup.

Unfortunately, I don't know why that's happening, as my code is very similar to the cefsimple example. LOOT does throw in shared mutable reference fields though, which is a bad idea, so maybe CEF is invalidating a reference...

**Comment by WrinklyNinja** [comment]
I may have fixed this as of 07564e8f947cae364603479117ae84c23dfd169d, anyone experiencing this issue should try [this build](https://bintray.com/loot/snapshots/download_file?file_path=loot_0.13.1-19-g07564e8_dev.7z).

**Comment by pStyl3** [comment]
Closing this issue, as the issue in `#1045` was fixed, as well as the fact that multiple libloot and LOOT versions have been released in the meantime.
