### ISSUE TITLE
Can't install latest version

### ISSUE THREAD

**Issue by mcbarker69** [loot/loot#967]
I get the following message when trying to install... 

![loot error](https://user-images.githubusercontent.com/39884856/40889861-a85788fe-673b-11e8-93df-4ba1583c3b30.jpg)

Tried uninstalling, then new install, but keep getting the same error. Can't send the requested file since Loot is no longer on my system. Using the Ignore button option results in a missing file error when trying to start the program.

**Comment by WrinklyNinja** [comment]
I can't replicate this running the installer twice. Does `C:\Program Files (x86)\LOOT\LOOT.exe` actually exist when the error is displayed?

**Comment by mcbarker69** [comment]
First attempt was an update install (overwrite previous version).
Second attempt was after uninstalling the old version. LOOT.EXE still
existed, and couldn't be deleted using administrator privileges. Also tried
deleting with administrator CMD program, without success.
Ran CCLEANER registry cleaner... no joy.
Finally, I ran REGEDIT manually, and was able to delete LOOT.EXE, along
with its .DLL and .DAT files. After a reboot, I was able to reinstall LOOT.
This happened once before. It seems that your install routine isn't able to
overwrite the old version of LOOT.EXE properly. I have to wonder why this
file is elevated to what I'm assuming is system file status.
Also, Norton Security always sees Loot as a threat, and quarantines the
executable archive, which has to be revived manually.

Regards

Tom Barclay | Photographer
*chemlabtechnician@gmail.com <chemlabtechnician@gmail.com>*

**Comment by WrinklyNinja** [comment]
> It seems that your install routine isn't able to overwrite the old version of LOOT.EXE properly.

I don't think it's got anything to do with the installer, since it's just plain Inno Setup and that's been used by all sorts of software for a very long time. In my experience being unable to delete files even as admin is just something that happens occasionally, some kind of Windows bug. I've experienced it with files I've created myself in scenarios completely unrelated to LOOT.

> Also, Norton Security always sees Loot as a threat, and quarantines the executable archive, which has to be revived manually.

Pretty much every release has virus scanner heuristics complain until LOOT's reported as a false positive and they update their databases. FWIW, Nexus scans uploads and you can view its report against a whole bunch of scanners, which came up clean.

Well, anyway, it seems your problem's sorted, so closing this.
