### ISSUE TITLE
Expose plugin locations in the UI

### ISSUE THREAD

**Issue by Freso** [loot/loot#989]
We've had `url` entries for plugins for a while now (and almost all newer entries have them!), and it was mentioned when they were introduced that they might eventually get exposed in/to the UI, but so far nothing has happened in this regard.

I was thinking that one way to expose them would be to have a menu item next to the Edit/Copy/Clear Metadata items on the individual plugin cards, possibly called "Visit Plugin Website" or "Visit Plugin URL". This would only work when there is only a single entry in the `url` list, so it could possibly additionally transform into a submenu if there are multiple items in `url` (and possibly also if the single entry in `url` has a `name` property).

I tried poking at it a bit myself, but I couldn't wrap my head around the JavaScript. I might try poking at it again, but may need some handholding. :)

**Comment by WrinklyNinja** [comment]
I've had vague thoughts of doing something similar. We don't currently include url metadata in what we send to the UI, but we can do that simply enough. The JS side is fairly simple too, but involves some Polymer magic to get it displayed.

**Comment by sibir-ine** [comment]
As I noted in https://github.com/loot/loot/issues/1638#issuecomment-996441280, one way we could implement this is a list in each plugin card titled something like _Locations_ that lists each location mapped to the plugin's `URL` key. If the location has a name, it could be displayed as a hyperlink. A filter could also be added to hide locations since it's not vital information, just useful in case a user loses track of a plugin they installed & we happen to have the location recorded. Like Bash Tags, it should probably also be hidden by default to avoid cluttering up the interface.

**Comment by pStyl3** [comment]
I've just noticed, that with the new Qt GUI you can right click on links and this window will open:
![grafik](https://user-images.githubusercontent.com/10406657/150835706-14db9941-d9f9-44de-8ce5-633d4bcc56ec.png)

It even seems to get's translated to our supported languages .. though the string isn't part of `template.pot`.

**Comment by Ortham** [comment]
I guess that's just part of the default Qt behaviour, I didn't write any code to do that.

**Comment by Ortham** [comment]
I've started to implement this in the `locations-display` branch, I think it'll need a little experimentation to find the best way to display locations. I've also yet to implement the filter.

@sibir-ine @pStyl3 what do you think of the current implementation?

**Comment by sibir-ine** [comment]
I think it works well. I was thinking of a list initially, but, now that I think about it, that would waste a lot of horizontal space. The horizontal bars work well to separate them since something like commas probably wouldn't separate them enough, & the generic names are preferable to bare URLs with this configuration. It's placement at the end is also fine considering it, like Bash Tags, isn't vital information for the average user.

We'll definitely have to make sure to add names to locations going forward 😛

**Comment by pStyl3** [comment]
I also like the horizontal arrangement. Perhaps, if only one location is known for a given plugin, we could label the link `Location` instead of `Location 1`. If there are two or more links we then could start to add numbers to them.

There's one aspect of the current implementation that I'm not so sure about, and that's if we should display the locations in a "box" within the plugin cards, just like the Bash Tags. If a plugin has both Bash Tags and location data the plugin card would contain two additional & distinct "boxes", which might be visually distracting (at least with the given styling of all the other elements). Perhaps listing them just like a normal message (with a leading bullet point) could be smoother.

**Comment by Ortham** [comment]
> I think it works well. I was thinking of a list initially, but, now that I think about it, that would waste a lot of horizontal space. The horizontal bars work well to separate them since something like commas probably wouldn't separate them enough, & the generic names are preferable to bare URLs with this configuration. It's placement at the end is also fine considering it, like Bash Tags, isn't vital information for the average user.

Yes, I tried a bullet point list first, but it wastes a lot of space. I also tried commas and it wasn't distinct enough.

> I also like the horizontal arrangement. Perhaps, if only one location is known for a given plugin, we could label the link `Location` instead of `Location 1`. If there are two or more links we then could start to add numbers to them.

Good idea, I'll do that.

> There's one aspect of the current implementation that I'm not so sure about, and that's if we should display the locations in a "box" within the plugin cards, just like the Bash Tags.

Yes, I think putting them in a box is overkill for a single line of text, but I wasn't sure how to lay them out otherwise. I'll try as a message.

**Comment by Ortham** [comment]
Here's the locations just as a single line of text at the bottom of the card, with a `Locations: ` prefix:

![image](https://user-images.githubusercontent.com/2430738/154579465-f7f179eb-d584-4ecc-9694-9c1717b556e4.png)

I feel like a prefix is necessary as things like `Beyond Reach` on its own would be pretty meaningless, but `Locations: Location` is also not great. "Location" might itself not be the best term to use, but I'm not sure what would be better... Links? Sites?

If the links are styled as a message instead, what would the message be? `This plugin can be downloaded from X, Y and Z.`? I think that might be a bit noisy.

**Comment by sibir-ine** [comment]
> I feel like a prefix is necessary as things like `Beyond Reach` on its own would be pretty meaningless, but `Locations: Location` is also not great. "Location" might itself not be the best term to use, but I'm not sure what would be better... Links? Sites?

Maybe _Sources_? I like either that or _Sites_ as I feel that _Links_ doesn't quite communicate that the links are places where you can download the plugin as well as the others.

**Comment by pStyl3** [comment]
I also like Sources, it's short and concise.

**Comment by Ortham** [comment]
I think Source / Sources looks good:

![image](https://user-images.githubusercontent.com/2430738/154652598-f4f6a6e0-7beb-464e-af20-85aeb85f03e1.png)

**Comment by Ortham** [comment]
I've pushed the formatting above and also added a Hide Sources filter that's enabled by default. Any other feedback?

**Comment by sibir-ine** [comment]
It looks good to me, & the filter works as expected 👍

**Comment by pStyl3** [comment]
I like it.  👍

**Comment by Ortham** [comment]
OK, merged as of e0565f1725980a300d342580a183d7a8cc41ff0a.
